SAP/open-ux-tools

.github/CODEOWNERS
* Add CODEOWNERS file to require reviews from `ux-tools-team-tools` and  `ux-tools-team-elements` GitHub teams.
=> chore: add github codeowners file

.github/workflows/pipeline.yml, packages/fiori-freestyle/package.json, packages/fiori-freestyle/test/basic.test.ts, packages/fiori-freestyle/test/index.test.ts, packages/fiori-freestyle/test/listdetail.test.ts, packages/fiori-freestyle/test/worklist.test.ts, packages/odata-service/test/index.test.ts, packages/ui5-application/package.json, packages/ui5-application/test/index.test.ts, packages/ui5-application/test/options.test.ts, pnpm-lock.yaml
- Adapt code due to API change in node 16.
https://github.com/nodejs/node/pull/37216/files#diff-11c13307cb334211e0d11f4e7e43bdc0a34e437779a63a6ff645e62448d973d2R1053-R1055
- Only write files to disk if UX_DEBUG environment variable is set when running unit tests.
=> Add Node V16 build and compatibility

packages/fiori-freestyle/templates/basic/add/webapp/Component.js, packages/fiori-freestyle/test/basic.test.ts
replace all occurrences of "." with "/" in `Component.js` template
=> fix: app-id creation at scaffolding time in Component.js (fixes #70)

.gitignore, packages/odata-service-writer/src/types.ts, packages/ui5-config/src/index.ts, packages/ui5-config/src/middlewares.ts, packages/ui5-config/src/types.ts, packages/ui5-config/test/index.test.ts, pnpm-lock.yaml
The net result is that we no longer include the TS 4.1 types (from yaml) when importing odata-service-writer
=> fix(odata-service): Removes ui5-config -> odata-service-writer dep

.changeset/fresh-ears-doubt.md, packages/fe-fpm-writer/src/section/index.ts, packages/fe-fpm-writer/src/section/types.ts, packages/fe-fpm-writer/templates/section/1.85/manifest.json, packages/fe-fpm-writer/templates/section/1.86/manifest.json, packages/fe-fpm-writer/test/integration/__snapshots__/index.test.ts.snap, packages/fe-fpm-writer/test/unit/__snapshots__/section.test.ts.snap, packages/fe-fpm-writer/test/unit/sample/section/webapp/manifest.json, packages/fe-fpm-writer/test/unit/section.test.ts
Part of 3rd point from #73
Main PR was - https://github.com/SAP/open-ux-tools/pull/212
According to latest documentation `name` property in `manifest.json` is deprecated since 1.86 and new approach is:
```
"NewCustomSection": {
"position": {
"anchor": "DummyFacet",
"placement": "After",
},
"template": "sapux.fe.fpm.writer.test.extensions.custom.NewCustomSection",
"title": "New Custom Section",
},
```
Old approach is(<1.86):
```
"NewCustomSection": {
"name": "sapux.fe.fpm.writer.test.extensions.custom.NewCustomSection",
"position": {
"anchor": "DummyFacet",
"placement": "After",
},
"title": "New Custom Section",
"type": "XMLFragment",
},
```
In scope of PR - we support both variants by specifying target UI5 version.
API was not changed and still accepts property `name` - similar like it is …
=> fix(fev4-fpm): Custom Section. Two 'manifest.json' generations versions for different UI5 versions below and above 1.86

package.json, pnpm-lock.yaml
This PR updates `pretty-quick` to the latest version. This has a fix for https://github.com/azz/pretty-quick/pull/143 - `pretty-quick@3.1.1` tries to format _any_ file in a folder that contains changed files, regardless of the fact that the file may be ignored or not in `.prettierignore`.
=> chore: update pretty-quick

.changeset/eleven-ads-joke.md, packages/fiori-freestyle-writer/src/packageConfig.ts, packages/fiori-freestyle-writer/test/__snapshots__/worklist.test.ts.snap, packages/fiori-freestyle-writer/test/packageConfig.test.ts
Fix for : #288
- Forgot to remove ? when building the sap-client parameter. This ? is duplicate when adding ? to the full query param. 
- Use node built-in URLSearchParams instead of using join('&') to build the full query param.
=> fix: avoid double delimiters

.changeset/angry-vans-train.md, packages/fiori-freestyle-writer/src/packageConfig.ts, packages/fiori-freestyle-writer/test/__snapshots__/basic.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/index.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/listdetail.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/worklist.test.ts.snap, packages/fiori-freestyle-writer/test/packageConfig.test.ts
#271 
Use double quotes for start commands in package.json, this will enable handling of params it in the start args with multiple params across platforms.
=> fix(fiori-freestyle-writer): use double quotes for start commands

docs/Guidelines.md
This pull request adds the 'Versioning' section to the guidelines markdown document.
=> docs: add info about versioning to guidelines

.changeset/metal-ads-tell.md, packages/fe-fpm-writer/src/common/defaults.ts, packages/fe-fpm-writer/test/unit/section.test.ts
While working on integration of custom sections(custom sections was 3rd point from https://github.com/SAP/open-ux-tools/issues/73)
Issue relates to custom extension like Custom Section, Custom Column.
Issue happens if we pass `folder` property with backslashes `ext\\fragment`, then it would resolved as:
```
"fragmentName": "project4.ext\fragment.Sefse",
```
Issue does not happen if we pass folder as `ext/fragment`.
In result extending regex for replace from `/\//g` to `/\/|\\/g`
=> fix(fe-fpm-writer): namespace resolution handle backslashes

.changeset/honest-ducks-drive.md, packages/logger/package.json, packages/logger/src/winston-logger/adapter.ts, packages/logger/src/winston-logger/logger.ts, pnpm-lock.yaml
* fixes #405 
* removed explicit dependency to `logform` (moved it to `devDependencies` for the type import)
* use `logform.format` functionality exposed by `winston`
=> Fix version incompatibility in yarn due to logform import

.changeset/five-seahorses-invite.md, packages/fe-fpm-writer/package.json, packages/fiori-elements-writer/package.json, packages/fiori-freestyle-writer/package.json, packages/odata-service-writer/package.json, packages/ui5-application-writer/package.json, packages/ui5-config/package.json, pnpm-lock.yaml
Changed increased used versions of `ejs` and `mem-fs-editor` to get rid of the vulnerabilities below
```
┌─────────────────────┬───────────────────────────────────────────────────┐
│ high                │ Prototype Pollution in async                      │
├─────────────────────┼───────────────────────────────────────────────────┤
│ Package             │ async                                             │
├─────────────────────┼───────────────────────────────────────────────────┤
│ Vulnerable versions │ <2.6.4                                            │
├─────────────────────┼───────────────────────────────────────────────────┤
│ Patched versions    │ >=2.6.4                                           │
├─────────────────────┼───────────────────────────────────────────────────┤
│ More …
```
=> switched to not vulnerable version of ejs

.changeset/dry-waves-develop.md, packages/fiori-elements-writer/test/__snapshots__/lrop.test.ts.snap, packages/fiori-elements-writer/test/lrop.test.ts, packages/fiori-freestyle-writer/test/__snapshots__/basic.test.ts.snap, packages/fiori-freestyle-writer/test/basic.test.ts, packages/fiori-freestyle-writer/test/common.ts
Recently added snapshots reference a dynamic value (the version of the `@sap-ux/fiori-elements-writer` and `@sap-ux/fiori-freestyle-writer`). This is blocking publish and would continue to break with each version. 
This PR mocks the dynamic values while maintaining the test coverage.
=> fix(f-e-w/f-f-w): Fix unstable tests relying on dynamic version

.changeset/cuddly-kiwis-vanish.md, packages/backend-proxy-middleware/src/base/proxy.ts, packages/backend-proxy-middleware/src/middleware.ts, packages/backend-proxy-middleware/test/base/proxy.test.ts
Fixes https://github.com/SAP/open-ux-tools/issues/541
=> fix(backend-proxy-middleware): Move handling of bsp to generateProxyMiddlewareOptions

.changeset/tricky-mice-whisper.md, packages/axios-extension/package.json, packages/backend-proxy-middleware/package.json, packages/btp-utils/package.json, packages/fe-fpm-writer/package.json, packages/fiori-elements-writer/package.json, packages/fiori-freestyle-writer/package.json, packages/logger/package.json, packages/odata-service-writer/package.json, packages/store/package.json, packages/ui5-application-writer/package.json, packages/ui5-config/package.json, packages/ui5-proxy-middleware/package.json, packages/yaml/package.json
Source map files are not needed in the tgz published to npm. Removing reduces the install size.
=> chore(open-ux-tools) ignore source map files when publishing to npm

.changeset/quiet-olives-scream.md, packages/fe-fpm-writer/src/action/index.ts, packages/fe-fpm-writer/src/building-block/index.ts, packages/fe-fpm-writer/src/column/index.ts, packages/fe-fpm-writer/src/page/custom.ts, packages/fe-fpm-writer/src/page/list.ts, packages/fe-fpm-writer/src/page/object.ts, packages/fe-fpm-writer/src/section/index.ts, packages/fe-fpm-writer/src/view/index.ts, packages/fiori-elements-writer/src/data/manifestSettings.ts, packages/fiori-elements-writer/src/index.ts, packages/fiori-freestyle-writer/jest.config.js, packages/fiori-freestyle-writer/src/index.ts, packages/odata-service-writer/src/updates.ts, packages/odata-service-writer/test/unit/updates.test.ts, packages/ui5-application-writer/src/index.ts
Fixes: https://github.com/SAP/open-ux-tools/issues/580
By passing an empty options object into `ejs.render()` we can avoid the `oDataService` properties being interpreted as options.  
Note: This is preferable than renaming properties on a case by case basis.
=> fix(odata-service-writer): #580 prevents oDataService properties being used as ejs render options

packages/btp-utils/test/destination.test.ts
Follow up of https://github.com/SAP/open-ux-tools/pull/609.
- Adapted missed test to use the `WebIDEAdditionalData` enum.
=> test(btp-utils): adapt missed test

CONTRIBUTING.md
This PR adds a clarification to the contributing guide to let reviewers resolve conversations. This makes sure that reviewers can track the changes they asked for and ask for further changes/clarifications if required.
=> CONTRIBUTING.md: clarify resolving conversations

.changeset/nine-seas-serve.md, .vscode/launch.json, packages/fe-fpm-writer/src/building-block/index.ts, packages/fe-fpm-writer/test/unit/__snapshots__/building-block.test.ts.snap, packages/fe-fpm-writer/test/unit/building-block.test.ts, packages/fe-fpm-writer/test/unit/sample/building-block/webapp-without-macros-ns-xml-view/ext/main/Main.view.xml, packages/fe-fpm-writer/test/unit/sample/building-block/webapp-without-macros-ns-xml-view/manifest.json
The building block generator in the `fe-fpm-writer` module does not add the `macros` namespace to the xml view or fragment file if the namespace doesn't already exist.
* Update building block generator to add the `xmlns:macros='sap.fe.macros'` namespace if the xml view or fragment file doesn't already contain it.
* Cleanup `.vscode/launch.json` to use the correct module names as prefixes and sort the configurations alphabetically.
=> fix(fe-fpm-writer): building block generator does not add macros ns

.changeset/giant-mirrors-jump.md, packages/fe-fpm-writer/templates/app/Component.js, packages/fe-fpm-writer/templates/app/Component.ts, packages/fe-fpm-writer/test/integration/__snapshots__/index.test.ts.snap, packages/fe-fpm-writer/test/integration/index.test.ts, packages/fe-fpm-writer/test/test-input/basic-ts/webapp/Component.ts, packages/fiori-freestyle-writer/src/index.ts
Feature: #621 
Required for: https://github.com/ui5-community/generator-ui5-project/pull/58
* Fixed incorrect id in `Component.ts` template when calling `enableFpm`
* Enhanced tests to cover this case
* Changed input for file ignore pattern to array to be compatible with older version of `ejs` (could happen if integrated in an older version of `yeoman`)
=> Small fixes required for `easy-ui5` integration of new TS features

.changeset/tidy-moose-doubt.md
This PR contains just a changeset to release a patch of the `fiori-freestyle-writer` because PR #645 containing the fix had an incomplete changeset.
=> just a changeset

.changeset/late-planets-cheer.md, packages/fe-fpm-writer/src/controller-extension/index.ts, packages/fe-fpm-writer/src/controller-extension/types.ts, packages/fe-fpm-writer/src/index.ts, packages/fe-fpm-writer/templates/controller-extension/Controller.js, packages/fe-fpm-writer/templates/controller-extension/Controller.ts, packages/fe-fpm-writer/templates/controller-extension/manifest.json, packages/fe-fpm-writer/test/integration/__snapshots__/index.test.ts.snap, packages/fe-fpm-writer/test/integration/index.test.ts, packages/fe-fpm-writer/test/unit/__snapshots__/controller-extension.test.ts.snap, packages/fe-fpm-writer/test/unit/controller-extension.test.ts
Support for controller extension creation using `fe-fpm-writer`.
Some special parts to mention:
1. In `manifest.json` - for controller extension we can have:
1.1. Single controller using property `controllerName` - string;
1.2. Multiple controllers using property `controllerNames` - string array;
In result we need handle cases when `controllerName` is defined in `manifest.json` and we try to add new `controllerName`, then we need apply transition from `controllerName` to `controllerNames`.
Also additional property `overwrite` is available in case user wants to replace existing with new.
2. Property `extension` - https://github.com/SAP/open-ux-tools/blob/feat/controllerExtensions/packages/fe-fpm-writer/src/controller-extension/types.ts#L35:
```
extension: ControllerExtensionPageTarget | …
```
=> feat: Controller Extension support in fe-fpm-writer

.changeset/witty-islands-refuse.md, packages/backend-proxy-middleware/src/base/proxy.ts, packages/backend-proxy-middleware/test/base/proxy.test.ts
* Make backend-proxy-middleware more robust by catching store errors and continuing the flow.
* improve unit tests by using a mocked store instead of the real one
The issue was found when running the `backend-proxy-middleware` unit tests on a machine that had matching but invalid entries in the secure store
=> Make backend-proxy-middleware more robust

.eslintrc, .prettierrc.js
While working on fixing eslint issues, I found a conflicting eslint rule.
Following example:
It tells me, that I should quote the property `default`, as it is a reserved word. The rule comes from `quote-props` -> `as-needed` ->  `keywords: true`
https://github.com/SAP/open-ux-tools/blob/83fea4a611e43a646cbd454f3382d15d491c2062/.eslintrc#L214-L221
If I change it to quoted, I get another error:
that tells me to replace `'default'` with `default`. This is caused by rule `prettier/prettier`:
https://github.com/SAP/open-ux-tools/blob/83fea4a611e43a646cbd454f3382d15d491c2062/.eslintrc#L255-L260
What helps is adding `"quoteProps": "preserve"`. The value `as-needed` doesn't do the trick, I assume it does not consider keywords, like quote-props does, but only property names that need quoting like …
=> chore: resolve conflicting eslint rule

.changeset/smart-days-camp.md, packages/odata-service-writer/.eslintignore, packages/odata-service-writer/package.json, packages/odata-service-writer/src/index.ts, packages/odata-service-writer/test/index.test.ts, packages/odata-service-writer/test/unit/index.test.ts, packages/odata-service-writer/test/unit/updates.test.ts, packages/odata-service-writer/tsconfig-build.json, packages/odata-service-writer/tsconfig.json, packages/ui5-application-writer/.eslintignore, packages/ui5-application-writer/.eslintrc, packages/ui5-application-writer/package.json, packages/ui5-application-writer/src/data/defaults.ts, packages/ui5-application-writer/test/data.test.ts, packages/ui5-application-writer/test/index.test.ts, packages/ui5-application-writer/test/options.test.ts, packages/ui5-application-writer/tsconfig-build.json, packages/ui5-application-writer/tsconfig.json
Carve out from #689 for `odata-service-writer` and `ui5-application-writer`
Main focus was on null-checks when using semver
=> linting fixes for base writers

.changeset/many-onions-hammer.md, packages/fe-fpm-writer/src/section/index.ts, packages/fe-fpm-writer/src/section/types.ts, packages/fe-fpm-writer/templates/common/Fragment.xml, packages/fe-fpm-writer/test/integration/__snapshots__/index.test.ts.snap, packages/fe-fpm-writer/test/unit/__snapshots__/section.test.ts.snap, packages/fe-fpm-writer/test/unit/section.test.ts
Add `sap.se.macros` namespace to custom section's `Fragment.xml` when ui5 version >= 1.90
I am not fully sure about `1.90`, but it is listed here as `Available since` - https://sapui5.hana.ondemand.com/sdk/#/api/sap.fe.macros.FormElement
=> fix(fe-fpm-writer): Add sap.se.macros namespace to custom section's Fragment.xml when ui5 version >= 1.90

.changeset/serious-frogs-yell.md, packages/yaml/.eslintignore, packages/yaml/package.json, packages/yaml/src/yaml-document.ts, packages/yaml/test/yaml-document.test.ts, packages/yaml/tsconfig-build.json, packages/yaml/tsconfig.json
This PR carves out a slice of https://github.com/SAP/open-ux-tools/pull/689 and takes care of the `@sap-ux/yaml` module.
It contains the following changes:
* fixes all the linter warnings
* includes linting for tests
* splits the `tsconfig` into one for CI/CD and one for local dev (source and tests)
Pending linter warnings:
```
packages/yaml/test/yaml-document.test.ts:
34:20  warning  Too many nested callbacks (4). Maximum allowed is 3  max-nested-callbacks
115:20  warning  Too many nested callbacks (4). Maximum allowed is 3  max-nested-callbacks
121:20  warning  Too many nested callbacks (4). Maximum allowed is 3  max-nested-callbacks
259:20  warning  Too many nested callbacks (4). Maximum allowed is 3  max-nested-callbacks
291:20  warning  Too many nested callbacks (4). Maximum allowed …
```
=> Fix lint warnings in @sap-ux/yaml

.prettierignore
https://github.com/SAP/open-ux-tools/issues/716 exclude file [pnpm-lock.yaml](https://github.com/SAP/open-ux-tools/blob/main/pnpm-lock.yaml) from prettier formatting.
=> chore: exclude pnpm lock from formatting

.changeset/metal-ladybugs-promise.md, packages/backend-proxy-middleware/src/base/proxy.ts, packages/backend-proxy-middleware/test/base/proxy.test.ts
In some rare cases it could happen that the `proxyReq` in https://github.com/SAP/open-ux-tools/blob/main/packages/backend-proxy-middleware/src/base/proxy.ts#L41 is missing the `path` property. If this the case then the proxy request will throw an exception. This PR introduces a check for the `path` property to make the `onProxyReq` handler more robust.
=> fix(backend-proxy-middleware): make onProxyReq handler more robust

.changeset/curvy-badgers-hang.md, packages/axios-extension/package.json, packages/fe-fpm-writer/package.json, pnpm-lock.yaml
Security vulnerability reported for the `@xmldom/xmldom` dependency - [CVE-2022-37616](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-37616)
* Upgrade `@xmldom/xmldom` dependency to `v0.8.3`
=> chore: upgrade @xmldom/xmldom dependency to v0.8.3

.changeset/rare-lies-talk.md, packages/environment-check/package.json, pnpm-lock.yaml
This is a follow up on the issue mentioned here: https://github.com/SAP/open-ux-tools/pull/725#pullrequestreview-1136572849
To reproduce the issue:
```
$ npm i @sap-ux/envcheck
$ node node_modules/.bin/envcheck
```
This results in issue:
```
Error: Cannot find module 'cross-spawn'
Require stack:
- node_modules/@sap/bas-sdk/dist/src/utils/core-utils.js
- node_modules/@sap/bas-sdk/dist/src/apis/is-app-studio.js
- node_modules/@sap/bas-sdk/dist/src/index.js
- node_modules/@sap-ux/environment-check/dist/checks/destination.js
- node_modules/@sap-ux/environment-check/dist/checks/environment.js
- node_modules/@sap-ux/environment-check/dist/cli/index.js
- node_modules/@sap-ux/environment-check/bin/envcheck
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
at …
```
=> chore(env-check): update bas-sdk dependency

.changeset/fresh-melons-marry.md, packages/store/package.json, pnpm-lock.yaml
This PR updates `keytar` from 7.8.0 to 7.9.0. Tools-suite is already on 7.9.0 and it makes sense to consolidate the versions
=> chore(store): upgrade keytar to 7.9.0

.changeset/twelve-poets-shave.md, packages/ui-components/src/components/UISection/UISplitter.scss
vscode color regression after - https://github.com/SAP/open-ux-tools/pull/759
after we removed `vscuie` variables - splitter lost its background because `vscuie` variable name was not matching vscode variable:
Adapted code to use previous variable `--vscode-debugToolBar-background`
=> fix(ui-components): apply lost background to splitter

.changeset/tiny-horses-act.md, packages/axios-extension/src/auth/connection.ts, packages/axios-extension/test/auth/connection.test.ts
https://github.com/SAP/open-ux-tools/issues/851
Reponse property is not always present on error object and throws an unwanted error - making it optional
=> fix(axios-ext): make response property on error object optional  

.changeset/sixty-years-float.md, packages/ui-components/src/components/UIFlexibleTable/UIFlexibleTable.tsx, packages/ui-components/test/unit/components/UIFlexibleTable.test.tsx
Updates cursor styling for table.
Updates this:
To this:
=> fix(ui-components): Cursor styling when doing reordering in Table

.changeset/silly-dodos-speak.md, packages/environment-check/src/checks/environment.ts, packages/environment-check/src/checks/get-installed.ts, packages/environment-check/test/checks/get-installed.test.ts
#860
https://github.com/SAP/open-ux-tools/issues/805
Provide the option to use the VSCode API and pass the installed extensions to `getEnvironment()`
Check `process.env` for indications that environment-check is being ran in VSCode Insiders, and return the correct extensions installed.
=> feat(env-check): add check for vscode insiders

.changeset/twelve-ways-unite.md, packages/ui-components/src/components/UIComboBox/UIComboBox.scss, packages/ui-components/src/components/UIComboBox/UIComboBox.tsx, packages/ui-components/src/components/UIComboBox/_mixins.scss, packages/ui-components/src/components/UIDropdown/UIDropdown.scss, packages/ui-components/src/components/UIDropdown/UIDropdown.tsx, packages/ui-components/src/components/UIDropdown/index.tsx, packages/ui-components/src/components/UIDropdown/utils.ts, packages/ui-components/src/components/UIInput/UITextInput.tsx, packages/ui-components/src/components/UITreeDropdown/UITreeDropdown.scss, packages/ui-components/src/components/UITreeDropdown/UITreeDropdown.tsx, packages/ui-components/src/styles/_variables.scss, packages/ui-components/stories/UICombobox.story.tsx, packages/ui-components/stories/UIDropdown.story.tsx, packages/ui-components/stories/UITextInput.story.tsx, packages/ui-components/stories/UITreedropdown.story.tsx, packages/ui-components/test/__snapshots__/UITextfield.test.tsx.snap, packages/ui-components/test/unit/components/UICombobox.test.tsx, packages/ui-components/test/unit/components/UIDropdown.test.tsx, packages/ui-components/test/unit/components/UITextfield.test.tsx, packages/ui-components/test/unit/components/UITreeDropdown.test.tsx
Task #801
Property `readOnly` is added or maintained for following components - `UITextInput`, `UIComboBox`, `UIDropdown`, `UITreeDropdown`
Additional changes applied to styling to match description from #801
Also added `Accessibility States` storybook examples for `UITextInput`, `UIComboBox`, `UIDropdown`, `UITreeDropdown`.
Screenshots from storybook:
Textfield:
ComboBox:
Dropdown:
TreeDropdown:
=> feat(ui-components): Tinkering with disabled and readonly input fields

packages/ui-components/src/components/UITable/UITable.tsx, packages/ui-components/test/unit/components/UITable.test.tsx
Fix for branch `jumping-cursor-in-edi-table`
- do not ignore row 0 when storing/restoring caret position
- add unit test case
=> fix: do not ignore row 0, test case

.changeset/smooth-ways-smoke.md, packages/ui-components/src/components/UIButton/UIActionButton.tsx, packages/ui-components/stories/UIButton.story.tsx, packages/ui-components/test/unit/components/UIActionButton.test.tsx
Problem reported by @aislingnoone , that color of icons in UIActionButton is always with `var(--vscode-foreground)`:
But expected is:
Updated storybook with:
=> fix(ui-components): UIActionButton. Remove forced color for inner icon

.changeset/sharp-zoos-speak.md, packages/ui-components/src/components/UIFlexibleTable/UIFlexibleTable.tsx, packages/ui-components/src/components/UIFlexibleTable/UIFlexibleTableRowNoData.tsx, packages/ui-components/test/unit/components/UIFlexibleTable.test.tsx
Fixes cursor issue on table reordering.
Issue:
Fixed:
=> fix(ui-components): Cursor styling for UIFlexibleTable

.changeset/loud-phones-kick.md, packages/ui-components/src/components/UIInput/UITextInput.tsx, packages/ui-components/test/__snapshots__/UITextfield.test.tsx.snap
Scenario is when we overwrite css with style like(maybe more cases with other style variations):
```
.ms-TextField-fieldGroup { align-items: center; }
```
then readonly field looks following:
Applying same read-only background for container as well
=> fix(ui-components): UITextInput. Background color issue for readonly fields

.changeset/lemon-humans-attack.md, packages/ui-components/src/components/UITranslationInput/UITranslationButton.tsx, packages/ui-components/src/components/UITranslationInput/UITranslationButton.types.ts, packages/ui-components/src/components/UITranslationInput/UITranslationInput.tsx, packages/ui-components/src/components/UITranslationInput/defaults.ts, packages/ui-components/test/unit/components/UITranslationInput/UITranslationInput.test.tsx
Following issues were found as different:
1. Default text of accept button should be `Apply`:
2. Following title/tooltip was missing:
3. Generate id for button with additional suffix `-navigate`
=> fix(ui-components)L UITranslationInput component wrong default accept label and missing tooltip for resolved input

.changeset/wet-planets-promise.md, packages/fiori-freestyle-writer/templates/worklist/add/webapp/controller/Worklist.controller.ts, packages/fiori-freestyle-writer/test/__snapshots__/worklist.test.ts.snap
fix #882
Fixes error
```
> ff_worklist_ts1@0.0.1 ts-typecheck
> tsc --noEmit
webapp/controller/Worklist.controller.ts:87:35 - error TS2532: Object is possibly 'undefined'.
87         if (this.byId("table") && this.byId("table").getBinding("items")) {
~~~~~~~~~~~~~~~~~~
webapp/controller/Worklist.controller.ts:88:13 - error TS2532: Object is possibly 'undefined'.
88             this.byId("table").getBinding("items").refresh(false);
~~~~~~~~~~~~~~~~~~
webapp/controller/Worklist.controller.ts:88:13 - error TS2532: Object is possibly 'undefined'.
88             this.byId("table").getBinding("items").refresh(false);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Found 3 errors in the same file, starting at: webapp/controller/Worklist.controller.ts:87
```
=> bug(ff-writer) fix worklist TS check for undefined

.changeset/thirty-walls-repair.md, packages/project-access/src/project/search.ts, packages/project-access/test/project/find-apps.test.ts
In some cases we need to perform multiple `findProjectRoot` to correctly identify project root (CDS project with multiple apps containing `package.json`) and having to wrap each call in a try-catch block makes it more difficult to use than it needs to be.
I've added another parameter `silent` which allows to suppress thrown errors. By default it is `false` and would not affect current users.
=> feat: add silent mode

.changeset/friendly-ties-decide.md, .vscode/launch.json, README.md, packages/fiori-elements-writer/test/__snapshots__/lrop.test.ts.snap, packages/fiori-elements-writer/test/alp.test.ts, packages/fiori-elements-writer/test/common.ts, packages/fiori-elements-writer/test/feop.test.ts, packages/fiori-elements-writer/test/fpm.test.ts, packages/fiori-elements-writer/test/lrop.test.ts, packages/fiori-elements-writer/test/ovp.test.ts, packages/fiori-elements-writer/test/worklist.test.ts, packages/fiori-freestyle-writer/templates/listdetail/add/webapp/controller/List.controller.js, packages/fiori-freestyle-writer/templates/listdetail/add/webapp/controller/ListSelector.js, packages/fiori-freestyle-writer/templates/listdetail/add/webapp/controller/ListSelector.ts, packages/fiori-freestyle-writer/test/__snapshots__/index.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/listdetail.test.ts.snap, packages/fiori-freestyle-writer/test/basic.test.ts, packages/fiori-freestyle-writer/test/common.ts, packages/fiori-freestyle-writer/test/listdetail.test.ts, packages/fiori-freestyle-writer/test/worklist.test.ts, packages/ui5-application-writer/src/data/defaults.ts, packages/ui5-application-writer/templates/optional/codeAssist/.eslintrc, packages/ui5-application-writer/templates/optional/eslint/.eslintrc, packages/ui5-application-writer/test/__snapshots__/options.test.ts.snap
changes for https://github.com/SAP/open-ux-tools/issues/915 
- Align FF ListDetail template between JS and TS (impacts unit tests) 
- Add `projectChecks` called in FE and FF tests when env `UX_DEBUG_FULL=true`
- runs `npm run install` , `npm run lint` or `npm run ts-typecheck` as appropriate to speed up manual regression testing
- Add `root: true`   to all template `.eslintrc` for consistency (and allow tests above to run with inheriting eslint config from above.
- "fix" ui5 version used in TS FE V2 tests to use a version that contains the types for FE V2.
- - fix TYPES_VERSION_PREVIOUS from `1.71.18` to `1.71.15` as `1.71.18` does not exist in https://www.npmjs.com/package/@sapui5/ts-types?activeTab=versions
=> Various fixes in UI5, FF and FE writers

.changeset/cyan-donkeys-fail.md, packages/project-access/test/project/ui5-config.test.ts, packages/project-access/test/test-data/project/webapp-path/custom-webapp-path-multi-yaml/src/webapp/manifest.json, packages/project-access/test/test-data/project/webapp-path/custom-webapp-path-multi-yaml/ui5.yaml, packages/yaml/src/yaml-document.ts, packages/yaml/test/yaml-document.test.ts
Issue https://github.com/SAP/open-ux-tools/issues/892
This PR fixes errors thrown in module `@sap-ux/yaml` when parsing multi document yaml strings. While it prepares for working with multiple documents, it does not provide full multi document capabilities. Full support of multi document yaml requires more technical evaluation and planing.
When running 
https://github.com/SAP/open-ux-tools/blob/41e234c0ba70425b42139a42218ece5a3562c032/packages/yaml/src/yaml-document.ts#L41-L47
with a `serializedYaml` containing [mulitple documents](https://www.yaml.info/learn/document.html), `this.document.error` contains at least one error with `code: 'MULTIPLE_DOCS'`. However, the document would still be parsed. Thus another possible fix for this would be to add an error filter to the constructor, like …
=> fix(yaml): do not throw errors for multi doc yaml

.changeset/tricky-wombats-remember.md, packages/project-access/src/project/search.ts, packages/project-access/test/project/find-apps.test.ts
Follow up to #907
The `silent` parameter was not correctly passed in recursion call.
=> fix(project-access): do not throw error in silent mode

packages/environment-check/test/checks/get-installed.test.ts, pnpm-lock.yaml
Unit tests for module `@sap-ux/environment-check` run unstable on Windows environment, e.g.:
https://cloud.nx.app/runs/ZmxKq3vkit/task/@sap-ux%2Fenvironment-check:test
I was not able to reproduce this issue locally on MacOS environment. Manual review of the code that is tested in the failed unit test brought this to my attention:
https://github.com/SAP/open-ux-tools/blob/7892e8f0d68761e06491bb6d87fe2f69e65e6bc8/packages/environment-check/src/checks/get-installed.ts#L142
While command 
```
npm root -g
```
should be fast, my assumption is, in certain cases it takes longer and exceeds the jest timeout of 5 seconds. 
With this PR command `npm root -g` is mocked. Additionally, I made sure the text to test for is also using the i18n text.
=> fix(env-check): more robust unit test

.github/workflows/pipeline.yml
* Add a Slack notification step to the CI/CD pipeline when packages are published to npmjs.com
=> chore: add slack notification to release workflow

.changeset/short-kangaroos-punch.md, packages/mockserver-config-writer/src/mockserver-config/package-json.ts, packages/mockserver-config-writer/test/unit/mockserver-config/package-json.test.ts
Issue: https://github.com/SAP/open-ux-tools/issues/934
When using `@ui5/cli` version 3 or higher, we do not need to set the `ui5.dependencies` in `package.json` anymore.
This PR adds a check for the used `@ui5/cli` version and adds or removes the mockserver middleware `ui5.dependencies` accordingly.
=> feat(mockserver-config): no ui5 dependency if cli > 2

.changeset/few-sloths-hunt.md, packages/ui-components/src/components/UITranslationInput/UITranslationInput.tsx, packages/ui-components/test/unit/components/UITranslationInput/UITranslationInput.test.tsx
#23962
allow to pass custom "title" when i18n entry resolved
=> fix: allow to pass custom title when i18n resolved

.github/workflows/pipeline.yml
The latest release commit triggered the Slack notification step in the CI/CD workflow. However, the Slack notification message did not contain any information about the packages that were published.
* Update CI/CD workflow to fix the issue with incorrect notification message
Here's a sample of how the notification should look if it works correctly.
=> fix(pipeline): incorrect notification message in slack notification step 

.changeset/two-scissors-clap.md, packages/backend-proxy-middleware/src/base/proxy.ts, packages/backend-proxy-middleware/test/base/proxy.test.ts
=> fix(backend-proxy-middleware): Enable FLP Embedded preview to load in case of encoding failure

.changeset/small-clouds-raise.md, packages/environment-check/src/archive/index.ts, packages/environment-check/test/archive/index.test.ts
See https://github.com/SAP/open-ux-tools/issues/993.
Adding option `mark: true` to `glob` does the trick, it adds `/` to directories when comparing: https://github.com/kaelzhang/node-ignore#2-filenames-and-dirnames
=> fix(env-check): ignore empty folders in archive

.changeset/funny-students-speak.md, packages/axios-extension/src/abap/message.ts, packages/axios-extension/src/abap/ui5-abap-repository-service.ts, packages/axios-extension/test/abap/message.test.ts
Fix for https://github.com/SAP/open-ux-tools/issues/1002
- updated unit tests
- added changeset
- change validated locally
Screenshot only showing the errordetails node being handled.
Sample error response;
```
{
"code": "/UI5/UI5_REP_LOAD/004",
"message":
{
"lang": "en",
"value": "Test run has indicated no problems"
},
"innererror":
{
"application":
{
"component_id": "CA-UI5-ABA-SAR",
"service_namespace": "/UI5/",
"service_id": "ABAP_REPOSITORY_SRV",
"service_version": "0001"
},
"transactionid": "0F61D5F13A6D0910F",
"timestamp": "20230480",
"Error_Resolution":
{
"SAP_Transaction": "For backend administrators: use ADT feed reader \"SAP Gateway Error Log\" or run transaction /IWFND/ERROR_LOG on SAP Gateway hub system and search for entries with the timestamp above for more details", …
```
=> fix(deploy-config): Add change set, updated unit test and code to handle error logging to support test mode

.changeset/fuzzy-spoons-chew.md, packages/ui-components/src/components/UITranslationInput/UITranslationButton.tsx, packages/ui-components/src/components/UITranslationInput/UITranslationButton.types.ts, packages/ui-components/src/components/UITranslationInput/UITranslationInput.tsx, packages/ui-components/src/components/UITranslationInput/UITranslationUtils.ts, packages/ui-components/stories/UITranslationInput.story.tsx
Issue #997
Trying to improve interface of `UITranslationInput` to avoid casting like:
Root idea is that we can pass objeect like:
```
key: {...}.
value: {...},
dummyProperty: string;
```
to `entries` property(interface of [Bundle](https://github.com/SAP/open-ux-tools/blob/main/packages/ui-components/src/components/UITranslationInput/UITranslationButton.types.ts#L32-L37)) 
In result once existing entry is found in bundle and user clicks on show button -> callback `onShowExistingEntry` returns reference to original object(with custom properties).
Current problem is that `onShowExistingEntry` is defined with strict type `TranslationEntry` as `onShowExistingEntry?: (entry: TranslationEntry) => void;`, but we need more generic type like:
```
export interface UITranslationProps<T extends …
```
=> fix(ui-components): Fix generic type for translation input entry

.changeset/clever-pants-pull.md, packages/fe-fpm-writer/test/test-input/basic-ts/.babelrc.json, packages/fe-fpm-writer/test/test-input/basic-ts/tsconfig.json, packages/fe-fpm-writer/test/test-input/basic-ts/ui5.yaml, packages/fiori-elements-writer/test/__snapshots__/feop.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/fpm.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/lrop.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/ovp.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/basic.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/listdetail.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/worklist.test.ts.snap, packages/ui5-application-writer/src/data/ui5Libs.ts, packages/ui5-application-writer/templates/optional/codeAssist/.eslintrc, packages/ui5-application-writer/templates/optional/codeAssist/tsconfig.json, packages/ui5-application-writer/templates/optional/typescript/.babelrc.json, packages/ui5-application-writer/templates/optional/typescript/package.json, packages/ui5-application-writer/templates/optional/typescript/tsconfig.json, packages/ui5-application-writer/test/__snapshots__/options.test.ts.snap, pnpm-lock.yaml
The latest version of the `ui5-middleware-transpile` is using the `.bablrc` if it exists and ignores settings from the `ui5.yaml`, however, our generated projects contain a mix of both.
This PR 
* moves all settings into the `.babelrc` and thereby fixes #1035
* updates the patch version of the `ui5-tooling-transpile`
* applies consistent indentation
=> Ui5 transpile updates

.changeset/lemon-feet-crash.md, packages/project-access/src/project/cap.ts, packages/project-access/test/project/cap.test.ts
There is an issue when loading `@sap/cds` module dynamically, because some of it's API's are exposed as getters on a class, which does not work well with transpiled import from typescript. It uses `Object.prototype.hasOwnProperty` which returns `false` for such getters and thus causes errors in runtime.
However, it also exposes the whole object as `default` property and this seems to be safe to use.
=> fix: cds dynamic import

.changeset/new-bags-obey.md, packages/fe-fpm-writer/templates/controller-extension/Controller.ts, packages/fe-fpm-writer/templates/controller-extension/ControllerExtension.d.ts, packages/fe-fpm-writer/test/integration/__snapshots__/index.test.ts.snap, packages/fe-fpm-writer/test/test-input/basic-ts/package.json, packages/fe-fpm-writer/test/test-input/basic-ts/tsconfig.json, packages/fe-fpm-writer/test/test-input/basic-ts/webapp/manifest.json, packages/fe-fpm-writer/test/unit/__snapshots__/controller-extension.test.ts.snap
Root issue https://github.com/SAP/open-ux-tools/issues/987
Root PR was [#1020](https://github.com/SAP/open-ux-tools/pull/1020)
This PR fixes follow up issue in `fpm-writer`
Generated `controller.ts` by `fpm-writer` does not work using new configuration(#1020):
```
{
"ignore": ["**/*.d.ts"],
"presets": [
[
"transform-ui5",
{
"overridesToOverride": true
}
],
"@babel/preset-typescript"
]
}
```
Old version of `controller.ts` was:
```
export default class Global2 extends ControllerExtension<ExtensionAPI> {
static override = {
onInit(this: Global2) {
const model = this.base.getExtensionAPI().getModel();
}
}
}
```
Which gets transpiled into:
such combination does not works.
Working version with `overrides` instead of `override`:
```
export default class Global2 extends …
```
=> fix(fpm-writer): update template of typescript Controller Extension after changes in 'transform-ui5' settings(.babelrc.json)

.changeset/tricky-pillows-suffer.md, packages/fiori-elements-writer/test/__snapshots__/feop.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/fpm.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/lrop.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/ovp.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/basic.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/listdetail.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/worklist.test.ts.snap, packages/ui5-application-writer/templates/optional/eslint/package.json, packages/ui5-application-writer/templates/optional/typescript/package.json, packages/ui5-application-writer/test/__snapshots__/options.test.ts.snap, packages/ui5-library-writer/templates/optional/typescript/package.json, packages/ui5-library-writer/test/__snapshots__/index.test.ts.snap
Chore - bump version of @sap-ux/eslint-plugin-fiori-tools used in templates needed after https://github.com/SAP/open-ux-tools/pull/1008
=> Chore - bump version of @sap-ux/eslint-plugin-fiori-tools used in templates

.changeset/nice-ears-push.md, packages/fiori-elements-writer/test/__snapshots__/fpm.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/lrop.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/basic.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/listdetail.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/worklist.test.ts.snap, packages/ui5-application-writer/test/__snapshots__/options.test.ts.snap, packages/ui5-application-writer/test/data.test.ts, packages/ui5-config/src/defaults.ts, packages/ui5-config/src/utils.ts, packages/ui5-config/test/utils.test.ts
A few months ago we implemented an algorithm to detect the best possible UI5 types library version based on internal knowledge of fixes and downports to specific versions. The problematic versions are now out of support so that the downports are not required anymore and that we can use the latest available version.
This PR removes that algorithm and goes back to a simple version mapping.
=> Removing types version workaround

.changeset/odd-knives-swim.md, packages/cap-config-writer/src/cap-config/package-json.ts, packages/cap-config-writer/test/unit/cap-config/index.test.ts
Related ticket: https://github.com/SAP/open-ux-tools/issues/1041
Module `cds-plugin-ui5` is used in CAP projects to be able to include app-specific UI5 middlewares when previewing an application. It can be added via command `npm @sap-ux/create add cds-plugin-ui5` or via the fiori generator when generating an application into a CAP project. This PR updates the minimum version of `cds-plugin-ui5` to `0.1.4`.
=> chore(cap-config-writer): update min version of cds-plugin-ui5

.changeset/hungry-games-hug.md, packages/environment-check/src/archive/index.ts, packages/environment-check/test/archive/index.test.ts
#1087 
Ignores `.git` folder in project when archiving.
=> fix(environment-check): ignore `.git` folder for archive

.changeset/friendly-countries-remain.md, packages/project-access/src/project/cap.ts, packages/project-access/test/project/cap.test.ts
Add utils method for getting absolute and reference uri for cap resources
- toAbsoluteUri
- toReferenceUri
- 
These methods are required for OS annotation api package
=> add methods to get absolute and reference uri

.changeset/tricky-panthers-bathe.md, packages/project-access/src/project/cap.ts, packages/project-access/test/project/cap.test.ts
Similar change to #1043.
Fixed issue where `getCapModelAndServices` was crashing when used in project with `@sap/cds` version 7.
Starting with version `7.0.0` of `@sap/cds` functions are only available under `default` export. In order try avoiding similar issues I created a utility function that properly loads the CDS module.
=> fix: cds v7 dynamic loading

.changeset/smart-crabs-cross.md, packages/deploy-tooling/src/base/deploy.ts, packages/deploy-tooling/test/unit/base/deploy.test.ts
https://github.com/SAP/open-ux-tools/issues/1089#issuecomment-1614595199
In the case the config does not specify `--cloud` and the target returns a abap cloud system, return an informative error.
=> tbi(deploy-tooling): improve abap service provider error handling

.changeset/grumpy-maps-press.md, packages/project-access/src/index.ts, packages/project-access/src/project/cap.ts, packages/project-access/src/project/index.ts, packages/project-access/test/project/cap.test.ts
https://github.com/SAP/open-ux-tools/issues/1098
Add 
```typescript 
async function readCapServiceMetadataEdmx(root: string, uri: string, version: 'v2' | 'v4' = 'v4'): Promise<string>
```
to module `@sap-ux/project-access`, which allows to convert a given service by `uri` from a CDS project into [EDMX](http://docs.oasis-open.org/odata/odata-csdl-xml/v4.01/odata-csdl-xml-v4.01.html).
This allows to have tools working in the same manner on project using EDMX and projects using CDS as data description format.
=> fix(project-access): function to convert cds to edmx

.changeset/calm-walls-run.md, .changeset/curly-wombats-drop.md, packages/axios-extension/src/auth/uaa.ts, packages/axios-extension/test/auth/uaa.test.ts
#1100
The token request config hardcodes a `/` at the end of the uaa-url, e.g ```url: `${this.url}/oauth/token```, with the issue arising when the uaa-url passed to the axios-extension already has a trailing slash
=> fix(axios-ext): remove trailing slash in uaa url

.changeset/angry-frogs-rush.md, packages/project-access/src/project/search.ts
Adds `readonly` for `WorkspaceFolder` in methods that are using `WorkspaceFolder` as input parameter. This is explicitly required when using newer versions of `@types/vscode`.
=> fix(project-access): add readonly for WorkspaceFolder

.changeset/poor-lions-serve.md, packages/deploy-tooling/src/cli/config.ts, packages/deploy-tooling/test/unit/cli/config.test.ts
Fix for https://github.com/SAP/open-ux-tools/issues/1128
- Updated test cases
- Applied changset
- Reverting the `process.env.SERVICE_USERNAME` code since the correct way to use dotenv is to explicity request it using the `--username` cli param and unblock cloud target deployments which use the SERVICE_USERNAME env variable
- Correct flow, which is currently supported and is not impacted;
Sample .env file
```
XYZ_USER=<my_username>
XYZ_PASSWORD=<my_password>
```
Sample CLI deploy command
```bash
./bin/deploy --name ZJLONG0205 --package '$tmp' --transport '' --url 'https://myapi.hanavlab.ondemand.com/' --username  env:XYZ_USER  --password  env:XYZ_PASSWORD
```
=> fix(deploy-tooling): Handle cli credentials

packages/create/README.md
I have noticed that if you use `npm init @sap-ux` it might use a previous version that you used before, therefore, it is best to add `@latest` to ensure the latest version is used.
This PR is just an update of the `README` , however, a follow up investigation is needed to better understand why and how and maybe improve it differently.
=> Improving the @sap-ux/create readme

.changeset/thick-books-poke.md, packages/deploy-tooling/src/base/deploy.ts, packages/deploy-tooling/test/unit/base/deploy.test.ts
#1112
Improves handling of retry for 401 errors. 
`createTransportRequest` still throws the error but no longer logs `Transport request could not be created for application ${config.app.name}. Please create it manually and re-run deployment configuration for this project.`, this error could be logged prematurely, in the case of NoAuth destinations, or if credentials are initially incorrect. 
The consuming code can handle the 401 and then pass the updated credentials to successfully create the TR.
=> fix(deploy-tooling): handle 401 error for creating transport requests

.changeset/many-singers-tease.md, packages/preview-middleware/README.md, packages/preview-middleware/src/base/flp.ts, packages/preview-middleware/src/types/index.ts, packages/preview-middleware/templates/flp/locate-reuse-libs.js, packages/preview-middleware/templates/flp/sandbox.html, packages/preview-middleware/test/fixtures/multi-app/package.json, packages/preview-middleware/test/fixtures/multi-app/ui5.yaml, packages/preview-middleware/test/unit/base/__snapshots__/flp.test.ts.snap, packages/preview-middleware/test/unit/base/flp.test.ts, packages/preview-middleware/test/unit/ui5/middleware.test.ts
This PR fixes the usage of the `preview-middleware` in a CAP project using the `cds-plugin-ui5`. In such a setup, the app is not hosted at the root but at a subfolder, so references to UI5 or the app need to be relative from the html file.
Also enables loading the `locate-reuse-libs.js` script on-the-fly when programmatically configured.
=> Use relative path to work with cds-plugin-ui5

.changeset/ninety-students-yawn.md, packages/adp-tooling/package.json
Feature: #971
Issue:when you execute `npm init @sap-ux@latest generate adaptation-project` and enter all data correctly, the following error is displayed: `Trying to copy from a source that does not exist: /xxx/.npm/_npx/b4bdc7e504f3256c/node_modules/@sap-ux/adp-tooling/templates/**/*.*`
=> fix: Trying to copy from a source that does not exist error

.changeset/lovely-plums-exist.md, packages/project-access/src/index.ts, packages/project-access/src/project/dependencies.ts, packages/project-access/src/project/index.ts, packages/project-access/src/project/module-loader.ts, packages/project-access/src/project/mta.ts, packages/project-access/test/file/file-search.test.ts, packages/project-access/test/project/cap.test.ts, packages/project-access/test/project/dependencies.test.ts, packages/project-access/test/project/find-apps.test.ts, packages/project-access/test/project/info.test.ts
https://github.com/SAP/open-ux-tools/issues/1153
Fix to avoid internal caching when calling `require.resolve()`. This pull requests implements the option, that check first if the module is installed before executing `require.resolve()` to get the module location. 
For details see description in ticket #1153
=> fix(project-access): load module, avoid caching of non existing files

.changeset/old-knives-roll.md, .eslintrc, packages/ui-components/src/components/UITable/UITable-helper.tsx, packages/ui5-proxy-middleware/src/ui5/middleware.ts, packages/ui5-proxy-middleware/test/ui5/middleware.test.ts
#1159
Sonar Qube bugs:
1. Promise returned in function argument where a void return was expected.
Promises should not be misused [typescript:S6544](https://sonarcloud.io/organizations/sap-1/rules?open=typescript%3AS6544&rule_key=typescript%3AS6544)
`packages/.../src/components/UITable/UITable-helper.tsx`
https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=BUG&id=SAP_open-ux-tools&open=AYfrPj_2SN0lrgwATVOw
2. Promise-returning function provided to property where a void return was expected.
Promises should not be misused [typescript:S6544](https://sonarcloud.io/organizations/sap-1/rules?open=typescript%3AS6544&rule_key=typescript%3AS6544)
`packages/ui5-proxy-middleware/src/ui5/middleware.ts`
https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&t …
=> fix(sonar): promises should not be misused

.changeset/young-waves-draw.md, packages/deploy-tooling/src/ui5/index.ts, packages/deploy-tooling/test/unit/ui5/index.test.ts
Fix for https://github.com/SAP/open-ux-tools/issues/1160
- added tests to ensure dotenv is called when task is called
=> fix(deploy-tooling): Load dotenv when UI5 task is called

.changeset/tidy-balloons-confess.md, packages/project-access/src/project/cap.ts, packages/project-access/test/project/cap.test.ts
The service details return from module `@sap/cds` looks different on Windows than on MacOS or Linux:
**Windows**
**MacOS, Linux**
While we did already a conversion from `\` -> `/` and removed double slashes, the leading slash was still in result of function call `getCapModelAndServices()`. The search for service removes leading and trailing slashes, so the mostly used function `readCapServiceMetadataEdmx()` was working as expected. This pull requests fixes the returned service of call `getCapModelAndServices()` and adds unit tests for the case with backslashes.
By the way the team of `@sap/cds` is informed and will provide a fix soon, goal is to return the service URL with forward slashes on any operating system.
=> fix(project-access): usage of cds on windows

.changeset/slow-kings-eat.md, packages/ui5-proxy-middleware/src/base/utils.ts, packages/ui5-proxy-middleware/test/base/utils.test.ts
When using the dev-approuter (https://www.npmjs.com/package/dev-approuter) to run UI5 and CAP applications inside the @sap/router from a monorepo then the server is using connect and not express. In those scenarios, similar like with livereload only the basic http response object from Node.js is available and the status function is not available which leads to an INTERNAL SERVER ERROR. By using the writeHead, write and end function of the response object the function is agnostic to the used server and works in both scenarios.
=> fix(ui5-proxy-middleware): support usage inside connect servers

.changeset/empty-turkeys-live.md, packages/fe-fpm-writer/src/common/defaults.ts, packages/fe-fpm-writer/src/section/index.ts, packages/fe-fpm-writer/templates/common/FragmentWithForm.xml, packages/fe-fpm-writer/test/integration/__snapshots__/basic-lrop-app.test.ts.snap, packages/fe-fpm-writer/test/unit/__snapshots__/header-section.test.ts.snap
Wrapped contents of `templateEdit` default fragment for header custom section with `FormElement`, because VBox is not valid for that.
Error in console:
=> fix(fe-fpm-writer): Edit for custom header section

.changeset/old-apricots-exist.md, packages/ui-components/src/components/UICreateSelect/UICreateSelect.tsx, packages/ui-components/stories/UICreateSelect.story.tsx
Add the `noOptionsMessage` props to UICreateSelect, to display information message when options menu is empty.
=> feat(ui-components) add the noOptionsMessage to UICreateSelect

.changeset/short-snakes-perform.md, packages/environment-check/src/checks/destination.ts, packages/environment-check/test/checks/destination.test.ts
#945 
Update to use `listDestinations` from  `@sap-ux/btp-utils` rather than the `@sap/bas-sdk` api.
=> fix(env-check): use btp-utils to retrieve destinations

.changeset/eleven-dryers-hear.md, .changeset/pretty-radios-tickle.md, packages/adp-tooling/src/writer/index.ts, packages/adp-tooling/templates/package.json, packages/adp-tooling/test/unit/writer/__snapshots__/index.test.ts.snap, packages/preview-middleware-client/.eslintrc.js, packages/preview-middleware-client/jest.config.js, packages/preview-middleware-client/package.json, packages/preview-middleware-client/src/adp/init.ts, packages/preview-middleware-client/src/cpe/init.ts, packages/preview-middleware-client/src/flp/init.ts, packages/preview-middleware-client/test/__mock__/sap/ui/rta/RuntimeAuthoring.ts, packages/preview-middleware-client/test/__mock__/window.ts, packages/preview-middleware-client/test/unit/adp/init.test.ts, packages/preview-middleware-client/test/unit/cpe/init.test.ts, packages/preview-middleware-client/test/unit/flp/init.test.ts, packages/preview-middleware-client/tsconfig.json, packages/preview-middleware-client/types/sap.ui.rta.d.ts, packages/preview-middleware/README.md, packages/preview-middleware/package.json, packages/preview-middleware/src/base/flp.ts, packages/preview-middleware/src/types/index.ts, packages/preview-middleware/src/ui5/middleware.ts, packages/preview-middleware/templates/flp/editor.html, packages/preview-middleware/test/fixtures/adp/ui5.yaml, packages/preview-middleware/test/unit/base/__snapshots__/flp.test.ts.snap, packages/preview-middleware/test/unit/base/flp.test.ts, packages/preview-middleware/test/unit/ui5/middleware.test.ts, packages/preview-middleware/tsconfig.json
Please note this is a breaking change because the possibility to change the generated html based on url parameter to use one endpoint for preview and editing has been removed. Instead, from now on, only the yaml configuration affects the generated templates and url parameters affect the runtime behavior.
* `preview-middleware-client`
* added placeholder for `adp` (adaptation projects) and `cpe` (control property editor) 
* improved the jest test setup
*  `preview-middleware`
* remove modification of the generated html based on url parameter
* enhance config with an `rta` object allowing to define mount points for editing 
* `adp-tooling`
* updated the generator template to use the new `preview-middleware` version and configuration
=> Enhancing the preview-middleware to support edit modes 

.changeset/large-bikes-matter.md, packages/ui5-proxy-middleware/README.md, packages/ui5-proxy-middleware/src/base/utils.ts, packages/ui5-proxy-middleware/src/ui5/middleware.ts, packages/ui5-proxy-middleware/test/base/utils.test.ts, packages/ui5-proxy-middleware/test/ui5/middleware.test.ts
@zdravko-georgiev @cfg74 , as discussed, here are the improvements for the `ui5-proxy-middleware`.
* use `debug` logging for the logging of forwarded files because it is otherwise so chatty that you don't see any other logs from other middlewares
* use a default setting for ui5 so that for the default case nothing needs to be provided as config in the yaml
```js
{
url: 'https://ui5.sap.com',
path: ['/resources', '/test-resources']
}
```
* fix for https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&types=BUG&id=SAP_open-ux-tools&open=AYfrPkWISN0lrgwATVQm
* changed log level for each loaded file from `info` to `debug`
* set default config if none is provided
* updated the readme
=> Proposal for improvements for ui5-proxy

.changeset/stale-bears-switch.md, packages/preview-middleware/README.md, packages/preview-middleware/src/base/flp.ts, packages/preview-middleware/src/types/index.ts, packages/preview-middleware/test/unit/base/__snapshots__/flp.test.ts.snap, packages/preview-middleware/test/unit/base/flp.test.ts
Adds a configuration option for setting the UI5 theme. This is useful when one wants to use the `preview-middleware` in an application with an older UI5 version that e.g. doesn't support the `sap_horizon` theme.
=> feat(preview-middleware): add an option for setting the UI5 theme

.changeset/quiet-icons-accept.md, packages/preview-middleware/src/ui5/middleware.ts, packages/preview-middleware/test/unit/ui5/middleware.test.ts
It was possible to configure the middleware to run an edit mode on a Fiori elements application that would result in incorrect and unsupported changes. This PR disables that possibility.
=> Disable unsupported configuration

.changeset/sweet-pianos-fry.md, packages/adp-tooling/package.json, packages/control-property-editor/package.json, packages/preview-middleware/package.json, pnpm-lock.yaml
- Adds `express` as `dependency` in the `preview-middleware`
- Adds `express` as `dependency` in the `adp-tooling`
- Removes `express` as devDependency from `control-property-editor` since it is not used anywhere
=> fix(middlewares): fix express dependency

.changeset/tidy-seahorses-move.md, packages/fe-fpm-writer/src/filter/index.ts, packages/fe-fpm-writer/test/unit/filter.test.ts
Issue #1336
Problem, if we have existing fragment.xml file in project and we pass path to such existing file using `generateCustomFilter`, then existing fragment file is overwritten with new content.
We avoid overwrite of existing fragments like codes here:
1. custom section -> https://github.com/SAP/open-ux-tools/blob/main/packages/fe-fpm-writer/src/section/index.ts#L166 https://github.com/SAP/open-ux-tools/blob/main/packages/fe-fpm-writer/src/section/index.ts#L115
2. custom page -> https://github.com/SAP/open-ux-tools/blob/main/packages/fe-fpm-writer/src/page/custom.ts#L92
3. handler files -> https://github.com/SAP/open-ux-tools/blob/main/packages/fe-fpm-writer/src/common/event-handler.ts#L90
=> fix(fpm-writer): Custom filter field. Custom filter field overwrites existing extension fragment file

.changeset/serious-bobcats-listen.md, packages/ui-components/src/components/UIList/UIList.tsx
Enhance props type for UIList -> ListProps.
ListProps should be extended from IGroupedListProps, because it allows to pass any property from IGroupedListProps -> https://github.com/SAP/open-ux-tools/blob/main/packages/ui-components/src/components/UIList/UIList.tsx#L138
=> fix(ui-components): UIList. ListProps interface should be extended from fluent-ui IGroupedListProps

.changeset/bright-fishes-fix.md, packages/adp-tooling/src/writer/index.ts, packages/adp-tooling/templates/project/package.json, packages/adp-tooling/test/unit/writer/__snapshots__/index.test.ts.snap
If you generate an adaptation project with the `npm init @sap-ux generate adpatation-project` command then you will have the following two problems:
Problem: The `npm run editor` is showing a 404
Reason: missing `/` in the `ui5.yaml`
Fix: add `/` to `ui5.yaml`
Problem: After adding a custom fragment to the project, `npm run build` will fail with an error when executing the `generateFlexChangesBundle` task
Reason: the task is not made for adaptation project
Fix: exclude task
Problem: After running `npm run build` the `dist` folder contains a useless `Component-preload.js` file
Reason: the `generateComponentPreload` task generates it
Fix: exclude task
=> fix: build and editor script

.changeset/lazy-hotels-applaud.md, packages/deploy-tooling/src/base/deploy.ts, packages/deploy-tooling/test/unit/base/deploy.test.ts
Fix for https://github.com/SAP/open-ux-tools/issues/1396
- tests updated
```
2023-10-23 22:49:46 info    abap-deploy-task: Please maintain correct credentials to avoid seeing this error
(see help: https://www.npmjs.com/package/@sap/ux-ui5-tooling#setting-environment-variables-in-a-env-file) 
2023-10-23 22:49:46 info    abap-deploy-task: Please enter your credentials. 
✔ Username: … myusername
✔ Password: … *********************
2023-10-23 22:49:49 warn    abap-deploy-task: You chose not to validate SSL certificate. Please verify the server certificate is trustful before proceeding. See documentation for recommended configuration (https://help.sap.com/viewer/17d50220bcd848aa854c9c182d65b699/Latest/en-US/4b318bede7eb4021a8be385c46c74045.html). 
2023-10-23 22:49:49 debug   abap-deploy-task: …
```
=> fix(deploy-tooling): Update provider with credentials after a failed auth request

.changeset/beige-glasses-act.md, packages/preview-middleware/src/base/flp.ts, packages/preview-middleware/test/unit/base/__snapshots__/flp.test.ts.snap
Fixes: #1395 
When multiple connectors are used, then one needs to define also which connector is responsible for which layer. The `WorkspaceConnector` is responsible for the `VENDOR` and `CUSTOMER_BASE` layers by default. Since the `LocalStorageConnector` is responsible for all layers by default, the layers `VENDOR` and `CUSTOMER_BASE` needs to be excluded for the LocalStorageConnector. This done by setting `"layers": ["CUSTOMER", "USER"]` for the `LocalStorageConnector`
=> fix(preview-middleware): set layers configuration for the LocalStorageConnector

.changeset/sour-monkeys-joke.md, packages/ui-components/src/components/UICallout/UICallout.tsx, packages/ui-components/src/components/UIComboBox/UIComboBox.scss, packages/ui-components/src/components/UIContextualMenu/UIContextualMenu.scss, packages/ui-components/src/components/UIContextualMenu/_variables.scss, packages/ui-components/src/components/UIDialog/UIDialog.tsx, packages/ui-components/test/unit/components/UICallout.test.tsx, packages/ui-components/test/unit/components/UIDialog.test.tsx
Issue #1406 
Changes requested by @gpeuc
To be sync with VSCode updates/latest changes:
1. UIDialog, UICallout, UITooltip - border-radius 4px; https://github.com/SAP/open-ux-tools/pull/1407/commits/8e78d9ae3941ab8e83ca69b543df7aa20e6efb02
2. Dropdown menues and contextual menues - border-radius 2px; https://github.com/SAP/open-ux-tools/pull/1407/commits/5552aaf0a1ded6e27b5aad91b482a89584f9efc1
=> fix(ui-components): Update dialogs/callout border radius to follow latest VSCode

.changeset/stale-papayas-do.md, packages/preview-middleware-client/src/adp/controllers/BaseDialog.controller.ts, packages/preview-middleware-client/src/adp/controllers/ControllerExtension.controller.ts, packages/preview-middleware-client/test/unit/adp/controllers/AddFragment.controller.test.ts, packages/preview-middleware-client/test/unit/adp/controllers/ControllerExtension.controller.test.ts
Bug fix for #1419 
- Added proper functionality to display error when name is over 64 characters long
=> Fixed controller extension name longer than 64 chars error not showing up

.changeset/strange-frogs-sit.md, packages/ui5-library-inquirer/README.md, packages/ui5-library-inquirer/package.json, packages/ui5-library-inquirer/src/index.ts, packages/ui5-library-inquirer/src/types.ts, packages/ui5-library-inquirer/test/unit/prompts/prompts.test.ts, packages/ui5-library-inquirer/test/unit/ui5-library-inquirer.test.ts, pnpm-lock.yaml
https://github.com/SAP/open-ux-tools/issues/1444
- Extends `prompt()` signature to allow caller to pass prompting module reference (`InquirerAdaptor`) thereby allowing the calling module to integrate the prompts more easily. Especially useful for calling Yeoman generators when running in a UI environment rather than CLI.
- Adds tests to cover
=> feat(ui5-library-inquirer): Support caller prompt module integration

.changeset/quiet-jars-warn.md, packages/project-access/src/project/cap.ts, packages/project-access/test/project/cap.test.ts
Error:
```
TypeError: Cannot read properties of undefined (reading 'odata-v4')
```
When loading different versions of `@sap/cds` dynamically, this error can occur. Affected are versions >= `@sap/cds@7.3`. It seems `global.cds`, which might remains in global node environment space, causes this issue. Assigning `global.cds` to newly loaded cds versions fixes the issue.
=> fix(project-access): load different cds versions

.changeset/short-pumpkins-switch.md, packages/odata-vocabularies/tsconfig.build.json
changed the rootDir path to "src" instead of ".", to generate the correct files order in dist folder
=> fix: update tesconfig to generate correct files order in dist

.changeset/cool-gorillas-march.md, packages/odata-vocabularies/src/vocabulary-service.ts
Enabled the parameter `uppercaseNameMap` in vocabularies_service which was removed by mistake.
=> fix: enable uppercaseNameMap property in vocabulary service

.changeset/thin-sheep-tie.md, packages/odata-vocabularies/src/vocabulary-service.ts
Change the access type of "upperCaseNameMap" property from Private to public,
=> fix: change access type of uppercaseNameMap prop

.changeset/weak-parrots-dress.md, packages/control-property-editor/src/components/ThemeSelectorCallout.scss, packages/control-property-editor/src/components/ThemeSelectorCallout.tsx, packages/control-property-editor/test/unit/components/ThemeSelector.test.tsx
This PR consumes the fix from first part mentioned below which was originally reported by [Sonar](https://sonarcloud.io/project/issues?resolved=false&severities=BLOCKER%2CCRITICAL%2CMAJOR%2CMINOR&sinceLeakPeriod=true&types=BUG&id=SAP_open-ux-tools&open=AYtswOQV4zj9YHX0JpwV) for no support for keyboard events for ThemeSelector Callout. 
First part of the [fix](https://github.com/SAP/open-ux-tools/pull/1474) is merged on ui-components Thanks @815are
=> Fix Missing Keyboard support for theme callout reported by Sonar

.changeset/wise-snails-nail.md, packages/preview-middleware/templates/flp/sandbox.html
Fix for: #1523 
- Save and Exit button is the same on UI5 versions lower than 1.110
=> Fix: show save button on UI5 versions lower than 1.110

.changeset/big-ducks-boil.md, packages/preview-middleware-client/src/adp/controllers/BaseDialog.controller.ts, packages/preview-middleware-client/src/adp/controllers/ControllerExtension.controller.ts, packages/preview-middleware-client/test/unit/adp/controllers/AddFragment.controller.test.ts, packages/preview-middleware-client/test/unit/adp/controllers/ControllerExtension.controller.test.ts
Bug fix for #1520 
- Removed trim for name inputs for Controller extension and Fragment so as to have validation by regexf
=> Fix: White spaces behind the ConExt/Fragment name are not validated/trimmed

packages/preview-middleware/playwright.config.ts
This PR fix:
* The job running on runner GitHub Actions 2 has exceeded the maximum execution time of 15 minutes.
**Explanation** 
Long `expect` timeout plus number of retries can cause exceed of maximum execution
=> fix: correct  playwright config to avoid timeout on failure

.changeset/soft-apples-clap.md, packages/preview-middleware-client/src/flp/init.ts, packages/preview-middleware-client/test/unit/flp/init.test.ts
Follow-up of https://github.com/SAP/open-ux-tools/issues/1557.
If for some reason the registering of the reuse libs fails, then the application should not be blocked from loading.
=> fix(preview-middleware): do not block app loading if registering of reuse libs fails

packages/create/test/unit/tracing/trace.test.ts
Unit test `packages/create/test/unit/tracing/trace.test.ts` -> `Modified yaml file` sometimes fails in Windows due to different sequence of changes. This happens sometimes the test runs the first time, subsequent runs of the test are successful. 
As shown in the screenshot, the differences are correct, but the sequence is wrong.
Seems the module [`diff`](https://www.npmjs.com/package/diff) is causing the issue as the array of differences returned by the call `diffTrimmedLines()` controls the output. I've checked the module and there have been been changes in the GitHub repository to address bugs on Windows, but no new version was released, yet. I'm also not certain that the issue we are facing would really be addressed by the fixes. 
As a workaround I've changed the unit test to test for …
=> fix: ignore sequence of changes in unit test

packages/create/test/unit/tracing/trace.test.ts
Even after https://github.com/SAP/open-ux-tools/pull/977 we get unit test failures on windows, e.g. https://github.com/SAP/open-ux-tools/actions/runs/7473778321/job/20340697749?pr=1578
I was able to reproduce the issue on Windows, after removing the line ending `${lr}` which it `\r` the expect:
```typescript
expect(loggerMock.debug).toBeCalledWith(expect.stringContaining(`[31mrootProperty: 'prop on root'[39m${ls}`));
```
Went through, failed at another point though. By now I'm pretty confident, that the issue is related to different line endings on Windows and MacOS/Linux. 
Probably found the issue, with https://github.com/SAP/open-ux-tools/pull/1554 file `.gitattributes` was introduce unifying the line endings. **-> Adjusted the test case.**
=> fix(create): unit test for trace changes

.changeset/seven-emus-dress.md, packages/project-access/src/project/search.ts, packages/project-access/test/project/find-apps.test.ts, packages/project-access/test/test-data/project/find-all-apps/CAP/CAPJava_mix/app/fiori_elements_with_ui5tooling_and_localyaml/package.json, packages/project-access/test/test-data/project/find-all-apps/CAP/CAPJava_mix/app/fiori_elements_with_ui5tooling_and_localyaml/webapp/manifest.json
Function `findFioriArtifacts()` from `@sap-ux/project-access` does not detect an app correctly, if 
- embedded into CAP
- has entry `@sap/ux-ui5-tooling` in `devDependencies` of package.json and file `ui5-local.yaml`
The project root path was pointing to the application root instead of the CAP project root.
=> fix(project-access): detecting apps that are part of CAP

.changeset/young-insects-hug.md, packages/odata-vocabularies/src/resources/com.sap.cds.vocabularies.AnalyticsDetails.ts, packages/odata-vocabularies/src/resources/com.sap.cds.vocabularies.ObjectModel.ts
odata-vocabularies for CDS analytics: use `IsFLags` for collection of enums, remove empty lines
=> odata-vocabularies for CDS analytics: use IsFLags for collection of enums, remove empty lines

packages/fe-fpm-writer/test/common/index.ts, packages/fe-fpm-writer/test/unit/action.test.ts, packages/fe-fpm-writer/test/unit/column.test.ts, packages/fe-fpm-writer/test/unit/filter.test.ts, packages/fe-fpm-writer/test/unit/section.test.ts, packages/fe-fpm-writer/test/unit/view.test.ts
I noticed following difference running on Windows:
vs
Run was on fresh clone vs old clope of `fpm-writer`.
Adjusting tests by handling both cases - detecting if new line in existing file is `\n`(1 symbol) or `\r\n`(2 symbols). Method -> `getEndOfLinesLength`
=> fix(fpm-writer): adjust fpm writer tests to avoid test failure on windows

.changeset/early-moles-jam.md, packages/ui-components/src/components/UISection/UISection.tsx, packages/ui-components/src/components/UISection/UISections.tsx, packages/ui-components/src/components/UIToolbar/UIToolbar.tsx, packages/ui-components/src/components/UIToolbar/UIToolbarColumn.tsx, packages/ui-components/stories/UISections.story.tsx, packages/ui-components/test/unit/components/UISection.test.tsx, packages/ui-components/test/unit/components/UISections.test.tsx, packages/ui-components/test/unit/components/UIToolbar.test.tsx
issue #1629
Allow to pass custom `data-*` attributes for `UISections`, `UISection`, `UIToolbar` and `UIToolbarColumn` components, like:
```
<UISections.Section height="100%" cleanPadding={true} hidden={!leftSectionVisible} data-test="test-value">
<div></div>
</UISections.Section>
```
=> fix: Allow to pass custom data-* attributes for UISections, UISection, UIToolbar and UIToolbarColumn components

.changeset/fast-chefs-speak.md, packages/ui-components/src/components/Icons.tsx
Fixed typo in variable definition of 'ExpandGroup'
=> Update Icons.tsx to fix typo 

.changeset/sharp-cats-compare.md, packages/axios-extension/src/abap/ui5-abap-repository-service.ts, packages/axios-extension/test/abap/ui5-abap-repository-service.test.ts, packages/deploy-tooling/src/base/deploy.ts, packages/deploy-tooling/test/unit/base/deploy.test.ts
#1615
Removed `showAddInfo` and the order of messages displayed as: 
```
info abap-deploy-task YY1_TESTIAN334 App available at https://my301102.s4hana.ondemand.com/sap/bc/ui5_ui5/sap/yy1_testian334
info abap-deploy-task YY1_TESTIAN334 Deployment Successful
info abap-deploy-task YY1_TESTIAN334 (Note: As the destination is configured using an On-Premise SAP Cloud Connector, you will need to replace the host in the URL above with the internal host)
```
=> fix(axios-ext): fix message order, remove showAddInfo flag

.changeset/nasty-trainers-sort.md, packages/backend-proxy-middleware/src/base/proxy.ts, packages/backend-proxy-middleware/test/base/proxy.test.ts, pnpm-lock.yaml
This PR removes the `Partitioned` property if it is present in a cookie. `Partitioned` needs to be used together with `Secure`. If `Secure` is missing then the cookie is considered invalid and it is not set.
=> fix(backend-proxy): remove Partitioned from the cookies

.changeset/brown-nails-wonder.md, packages/fe-fpm-writer/templates/controller-extension/Controller.ts, packages/fe-fpm-writer/templates/page/custom/1.84/ext/Controller.ts, packages/fe-fpm-writer/templates/page/custom/1.94/ext/Controller.ts, packages/fe-fpm-writer/test/unit/__snapshots__/controller-extension.test.ts.snap, packages/fe-fpm-writer/test/unit/page/__snapshots__/custom.test.ts.snap, packages/fe-fpm-writer/test/unit/page/custom.test.ts, packages/fiori-elements-writer/test/__snapshots__/fpm.test.ts.snap
Issue #1552
Wrong namespace was created for new controller extension in typescript project:
```
/**
* @namespace project1.ext.controller.Test
* @controller
*/
export default class Test extends ControllerExtension<ExtensionAPI> {
```
is compiled as:
```
var Test = ControllerExtension.extend("project1.ext.controller.Test.Test", {
```
Both proposed solutions from Christian works:
```
Solution
The fpm writer should either define
@namespace <%- ns %>
or
@name <%- ns %>.<%- name %>
```
Additionally - I noticed that custom page's controller does not look optimal as well:
```
/**
* @namespace project1.ext.view.Aaaaaaaa.controller
*/
export default class Aaaaaaaa extends Controller {
```
compiles as:
```
var Aaaaaaaa = Controller.extend("project1.ext.view.Aaaaaaaa.controller.Aaaaaaaa", {
```
If we …
=> fix(fpm-writer): use correct namespace when generating typescript controllers of controller extension and custom page controllers

.changeset/slow-ads-sleep.md, packages/i18n/README.md, packages/i18n/package.json, packages/i18n/web.d.ts, packages/i18n/web.js, packages/project-access/src/index.ts, packages/project-access/src/project/access.ts, packages/project-access/src/project/index.ts, packages/project-access/src/types/access/index.ts, packages/project-access/src/types/i18n/index.ts
This PR contains:
* expose getI18nPropertiesPaths
* remove of reexport type from `@sap-ux/i18n`
* include `exports` in `package.json` file of `@sap-ux/i18n`
=> fix: expose getI18nPropertiesPaths and include web.js

.changeset/six-candles-dream.md, packages/jest-file-matchers/src/index.ts
#1664 
Export types from jest matchers to avoid importing as deeply nested dist references
=> fix(jest-matchers): export types from jest matchers

.changeset/fair-vans-complain.md, packages/axios-extension/src/abap/adt-catalog/services/transportcheck-service.ts, packages/axios-extension/test/abap/abap-adt-service.test.ts, packages/axios-extension/test/abap/mockResponses/transportChecks-6.xml
#1671
Rather than showing the raw XML in the case of errors, parse the XML and extract the messages to be displayed clearly as errors
=> tbi(axios-ext): log error msg for transport check xml response

.changeset/beige-timers-buy.md, packages/fe-fpm-writer/src/common/event-handler.ts, packages/fe-fpm-writer/src/common/types.ts, packages/fe-fpm-writer/test/unit/__snapshots__/action.test.ts.snap, packages/fe-fpm-writer/test/unit/action.test.ts
Added `controllerPrefix` property to custom action event handlers. Use it when resolving event handler namespace.
=> feat: Controller prefix for event handler

.changeset/wet-ducks-cough.md, packages/adp-tooling/src/preview/adp-preview.ts, packages/adp-tooling/test/unit/preview/adp-preview.test.ts
Instead of trying to handle the loading of local files in the preview middleware, just redirect to root so that the other UI5 middleware can handle the loading.
=> FIX: preview of adp projects with controller extensions written in typescript

.changeset/slow-shoes-exercise.md, .eslintrc, packages/axios-extension/src/abap/adt-catalog/services/adt-service.ts, packages/axios-extension/src/auth/reentrance-ticket/redirect.ts, packages/axios-extension/src/base/odata-service.ts, packages/axios-extension/src/base/service-provider.ts, packages/control-property-editor/src/panels/properties/PropertyDocumentation.tsx, packages/environment-check/src/types.ts, packages/project-access/src/project/access.ts, packages/project-access/src/project/i18n/read.ts, packages/project-access/src/types/access/index.ts, packages/project-access/src/types/cap/index.ts, packages/project-access/src/types/i18n/index.ts, packages/project-access/test/project/access.test.ts, packages/project-access/test/project/i18n/read.test.ts, packages/ui-components/src/components/UIComboBox/UIComboBox.tsx, packages/ui-components/src/components/UIDropdown/UIDropdown.tsx, packages/ui-components/src/components/UIToolbar/UIToolbar.tsx, packages/ui-components/src/components/UITreeDropdown/UITreeDropdown.tsx
This PR address:
* improvement in `getI18nBundles` 
Currently `getI18nBundles` throw exception if it fails for any bundle it tries to retrieve. This PR enhances to be more tolerant and tries all bundles. If there is any exception, it is captured in optional errors object.
* enhance eslint for JSDoc
Report on  missing  of JSDoc for `TSMethodSignature`
=> fix: getI18nBundles and add JSDoc

.changeset/brave-crabs-work.md, packages/ui5-info/src/constants.ts, packages/ui5-info/src/index.ts, packages/ui5-info/src/ui5-version-fallback.ts, packages/ui5-info/src/ui5-version-info.ts, packages/ui5-info/test/__snapshots__/ui5-version-info.test.ts.snap, packages/ui5-info/test/commands.test.ts
#1699 
- Export `supportedUi5VersionFallbacks`
- Updates fallbacks to todays available versions
- Updates tests
=> Adds supported ui5 version fallback export

.changeset/weak-ladybugs-sparkle.md, packages/ui-components/src/components/UIButton/UIIconButton.tsx, packages/ui-components/stories/UIButton.story.tsx, packages/ui-components/test/unit/components/UIIconButton.test.tsx
Issue - #1703
When we use `UIIconButton` with `checked=true`, like:
```
<UIIconButton
id="btn1"
iconProps={{ iconName: UiIcons.Undo }}
checked={true}
title="Undo" />
```
2. It looks following:
Problem is that colors are hardcoded from fluent-ui and does not support vscode themming.
After fix:
=> fix(ui-components): Support VSCode theme color styling for UIIconButton property 'checked'

.changeset/funny-dodos-deny.md, packages/telemetry/src/tooling-telemetry/telemetry-settings.ts, packages/telemetry/test/telemetrySettings/init-settings.test.ts
Fix for assigning resource id in telemetry settings , introduced with https://github.com/SAP/open-ux-tools/pull/1698
=> fix(telemetry): assigning resource id in telemetry settings

.changeset/four-kids-bathe.md, .changeset/seven-months-type.md, packages/telemetry/example/index.ts, packages/telemetry/package.json, packages/telemetry/src/tooling-telemetry/telemetry-settings.ts, packages/telemetry/src/tooling-telemetry/types.ts, packages/telemetry/test/telemetrySettings/init-settings.test.ts, packages/telemetry/test/tools-suite-telemetry/index.test.ts, pnpm-lock.yaml
https://github.com/SAP/open-ux-tools/issues/1417
- Adds `watchTelemetrySettingStore` as a required option to ToolsSuiteTelemetryInitSettings. Using a watch on the store is not always desirable
- Bump `applicationinsights` to `2.9.2` to incorporate fix https://github.com/microsoft/ApplicationInsights-node.js/pull/1241 displaying `ApplicationInsights:Invalid JSON config file when using APPLICATIONINSIGHTS_CONNECTION_STRING` error 
- Increasing timeout for tests due to instabilities. Also making paths dynamic so they can be ran with tools like jest-runner
=> tbi(telemetry): update init settings, bump azure applicationinsights and stablise tests

.changeset/ninety-kids-stare.md, packages/ui-components/src/components/UIButton/UIIconButton.tsx, packages/ui-components/stories/UIButton.story.tsx, packages/ui-components/test/unit/components/UIIconButton.test.tsx
Use example as:
1. Use `UIIconButton`, like:
```
<UIIconButton
iconProps={{ iconName: UiIcons.LayoutLeft }}
checked={true}></UIIconButton>
```
Previously it looked following:
After correction:
=> fix(ui-components): UIIconButton. Some button icons(which are not 16x16) are not vertically centered.

.changeset/plenty-hairs-smell.md, packages/ui5-application-inquirer/src/index.ts, packages/ui5-application-inquirer/test/unit/ui5-application-inquirer.test.ts
#1724
- Fixes wrong arg ordering when internally calling `getPrompts(...)`
- Removes in-line `exports` which was only added to support test mocking
- Removes unnecessary clone, remnant of previous implementation when prompt options were cleaned
- Add test to cover
=> fix(ui5-application-inquirer): Wrong arg order

.changeset/late-phones-love.md, packages/preview-middleware/src/base/flp.ts
Issue found by @heimwege while working on #1726.
=> Preview middleware doesn't work on windows if the custom url is multiple folders deep

.changeset/lucky-panthers-provide.md, packages/telemetry/package.json, pnpm-lock.yaml
There is a unused dependency to `@sap/ux-specification` in `@sap-ux/telemetry`. This pull request removes it.
=> chore(telemetry): remove unused dependency to @sap/ux-specification

.changeset/fair-fireants-arrive.md, packages/control-property-editor/src/panels/properties/StringEditor.tsx
text input focus out do not trigger empty change
=> fix: text input focus out do not trigger empty change

.changeset/silly-emus-melt.md, packages/project-access/src/project/cap.ts, packages/project-access/test/project/cap.test.ts
Removes the setting of `cds.root`, which was introduced in https://github.com/SAP/open-ux-tools/pull/1563. Setting of `cds.root` has unforeseen side effects when using `require.resolve`. Instead set the project root when calling `cds.load`.
=> fix(project-access): remove setting of cds.root

.changeset/green-windows-yell.md, packages/inquirer-common/package.json, packages/inquirer-common/src/prompts/utility.ts, packages/inquirer-common/test/unit/prompts/utility.test.ts, packages/ui5-application-inquirer/src/prompts/prompts.ts, packages/ui5-application-inquirer/test/unit/prompts/prompts.test.ts, pnpm-lock.yaml
Fix for #1770 
- Adds new function `getDefaultUI5VersionChoice` which will return the closest match from a known list of ui5 versions
- Updates `@sap-ux/ui5-application-inquirer` to use the new function, instead of adding anyway (system versions may not be available generally)
- Adds/updates tests to cover
=> fix(ui5-application-inquirer): Bug fix #1770 - use available ui5 versions only

.changeset/new-squids-remember.md, packages/deploy-tooling/src/base/validate.ts, packages/deploy-tooling/test/unit/base/validate.test.ts
Fixes BUG - deploy-test displays stack trace if authentication is required #1758
Change to what is logged in console when `getSystemPrefix` throws an error.
Fix confirmed locally, full stack trace is no longer shown:
```
npm run deploy-test
> sampleproj1@0.0.1 deploy-test
> npm run build && fiori deploy --config ui5-deploy.yaml --testMode true
> sampleproj1@0.0.1 build
> ui5 build --config=ui5.yaml --clean-dest --dest dist
info ProjectBuilder Preparing build for project sampleproj1
info ProjectBuilder   Target directory: dist
info ProjectBuilder Cleaning target directory...
info Project 1 of 1: ❯ Building application project sampleproj1...
info sampleproj1 › Running task escapeNonAsciiCharacters...
info sampleproj1 › Running task replaceCopyright...
info sampleproj1 › Running task …
```
=> fix(deploy-tooling): change logging in validation for deploy-test

.changeset/kind-owls-act.md, packages/mockserver-config-writer/src/mockserver-config/ui5-mock-yaml.ts, packages/mockserver-config-writer/test/unit/mockserver-config/__snapshots__/ui5-mock-yaml.test.ts.snap, packages/mockserver-config-writer/test/unit/mockserver-config/ui5-mock-yaml.test.ts
#1735
If ui5-mock.yaml exists, updates existing ui5-mock.yaml config with annotations. 
If ui5-mock.yaml doesn't exist but ui5.yaml exists, creates it based on ui5.yaml and updates with annotations
=> fix(mock-server-config): Updates ui5-mock.yaml with annotations

.changeset/dry-spiders-warn.md, packages/project-access/src/project/cap.ts, packages/project-access/test/project/cap.test.ts
Partially reverts SAP/open-ux-tools#1748
It was reported that #1748 causes follow up issues regarding `cds.root` - reason of revert.
Additionally we found reason of why there was error of failing `require.resolve` - it was not issue on `open-ux-side`.
We had call for `require.resolve` outside of `open-ux-tools` source.
=> fix: revert cds root set

.changeset/cool-years-deny.md, packages/project-access/src/project/cap.ts, packages/project-access/test/project/cap.test.ts
Reverts SAP/open-ux-tools#1774
After investigation we found that following code is executed if we change `cds.root`:
It is executed in following scope:
1. project path(changed value of `cds.root`) had `spec` dependency;
2. there no `spec` dependency in node_modules yet(install is in progress);
3. then there is call for `require.resolve` for `spec` with cds, which creates cached value with failure state(package.json reader cache);
Then we try to access dependency on next round(when node_modules is installed) - `resolve` throws error based on failure state
=> Revert "fix: revert cds root set"

.changeset/stale-pumpkins-teach.md, packages/deploy-tooling/src/base/validate.ts, packages/deploy-tooling/test/unit/base/validate.test.ts
Fixes: Additional bug from #1758 where stack trace from axios was still shown.
- Fix for internal issue no: 27150
=> fix(deploy-tooling): hide stack trace on error

.changeset/serious-pets-rush.md, docs/version-overrides.md, package.json, pnpm-lock.yaml
Fix for:
```
┌─────────────────────┬────────────────────────────────────────────────────────┐
│ high                │ Path traversal in webpack-dev-middleware               │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Package             │ webpack-dev-middleware                                 │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Vulnerable versions │ >=6.0.0 <6.1.2                                         │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Patched versions    │ >=6.1.2                                                │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Paths               │ packages/ui-components > …
```
=> fix(security): update webpack-dev-middleware

.changeset/six-eggs-eat.md, packages/adp-tooling/package.json, packages/adp-tooling/src/preview/routes-handler.ts, packages/adp-tooling/tsconfig.json, packages/preview-middleware-client/src/adp/api-handler.ts, packages/preview-middleware-client/src/adp/controllers/ControllerExtension.controller.ts, packages/preview-middleware-client/test/unit/adp/controllers/ControllerExtension.controller.test.ts, pnpm-lock.yaml
Fix for #1750.
- Enhance route to return environment in the response to then dynamically show/hide button in the Controller dialog.
=> fix: "Open in VS Code" button for Controller Extension dialog does not work in BAS

.changeset/many-cycles-drop.md, packages/eslint-plugin-fiori-tools/eslintrc-typescript.js, packages/eslint-plugin-fiori-tools/package.json, packages/fiori-elements-writer/test/__snapshots__/feop.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/fpm.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/lrop.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/ovp.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/basic.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/listdetail.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/worklist.test.ts.snap, packages/preview-middleware-client/.eslintrc.js, packages/preview-middleware-client/src/adp/api-handler.ts, packages/preview-middleware-client/src/adp/controllers/ExtensionPoint.controller.ts, packages/preview-middleware-client/src/adp/init.ts, packages/preview-middleware-client/src/cpe/changes/service.ts, packages/preview-middleware-client/src/cpe/control-data.ts, packages/preview-middleware-client/src/cpe/documentation.ts, packages/preview-middleware-client/src/cpe/logger.ts, packages/preview-middleware-client/src/cpe/outline/nodes.ts, packages/preview-middleware-client/src/cpe/selection.ts, packages/preview-middleware-client/src/flp/WorkspaceConnector.ts, packages/preview-middleware-client/src/flp/common.ts, packages/ui5-application-writer/templates/optional/eslint/package.json, packages/ui5-application-writer/templates/optional/typescript/package.json, packages/ui5-application-writer/test/__snapshots__/options.test.ts.snap, packages/ui5-library-writer/templates/optional/typescript/package.json, packages/ui5-library-writer/test/__snapshots__/index.test.ts.snap
Enable type checking for TS projects from Eslint in the Fiori project
- Update minor version and consumption in project templates
- Update eslint config in `preview-middleware-client` and address some eslint issues in the code.
=> Enable type checking for TS projects from eslint 

.changeset/polite-needles-sleep.md, packages/deploy-tooling/src/base/deploy.ts, packages/deploy-tooling/test/unit/base/deploy.test.ts
https://github.com/SAP/open-ux-tools/issues/1821
Change the default TR description to include the name of the ABAP repo used in deploy config so that users can more easily see what the TR relates to. The suggested new default text should be:
`Created by SAP Open UX Tools for ABAP repository <repository name>`
=> feat(deploy-tooling): 1821 change TR description

.changeset/slimy-gifts-rescue.md, packages/project-access/src/project/cap.ts, packages/project-access/test/project/cap.test.ts
To retrieve service definitions for CAP project we load module `@sap/cds` from the CAP project. As fallback, we try to load `@sap/cds` from global modules, which will be available in the common case that developer cli tools `@sap/cds-dk` is installed. This is required especially for CAP Java projects.
There is a flaw in this approach, in case the CAP project specifies a dependency to `@sap/cds` e.g. to version 7, but the node modules are not installed yet, so `npm install` was not executed.In this case the fallback to global installed `@sap/cds-dk` applies. However, the version of global installed `@sap/cds` could differ from the one specified in the project, e.g. version 6. This can lead to issues due to incompatible changes of different major versions.
This pull request addresses this …
=> fix(project-access): detect mismatch of global and project installed @sap/cds

.changeset/late-avocados-stare.md, packages/ui5-info/src/ui5-version-fallback.ts, packages/ui5-info/test/__snapshots__/ui5-version-info.test.ts.snap, packages/ui5-info/test/commands.test.ts
Fixes https://github.com/SAP/open-ux-tools/issues/1835
- Dont return invalid sem ver as fallback, `Latest` would need to be resolved anyway and this doesnt make sense in an offline environment.
- Updates fallback to today
- Updates tests
=> fix(ui5-info): Fix for UI5 version offline fallbacks

.changeset/brave-games-rest.md, packages/axios-extension/src/auth/reentrance-ticket/index.ts, packages/axios-extension/test/auth/reentrance-ticket/index.test.ts
Renames `SCENARIO` to `FIORI_TOOLS_SCENARIO` in order to be consistent to other env variables expected by the middlewares.
=> fix(axios-extension): rename SCENARIO to FIORI_TOOLS_SCENARIO

.changeset/brown-lies-allow.md, .changeset/tame-nails-grin.md, packages/project-access/src/library/helpers.ts, packages/project-access/test/library/helpers.test.ts, packages/ui5-config/src/ui5config.ts, packages/ui5-config/test/__snapshots__/index.test.ts.snap, packages/ui5-config/test/index.test.ts, packages/ui5-library-reference-writer/src/helpers.ts, packages/ui5-library-reference-writer/test/index.test.ts
#1856
- `@sap-ux/project-access` : Fix the paths returned for libraries / components i.e the directory rather than a file.
- `@sap-ux/ui5-config`: If there is exisiting config, the new paths need to be merged to `fiori-tools-servestatic` custom middleware 
- `@sap-ux/ui5-library-reference-writer` : The library path (as it is passed in) should be used to determine the relative path written to the yaml files.
=> fix(ui5-lib-ref-writer): fix paths and config writers for ui5 lib reference

.changeset/big-geese-ring.md, packages/fe-fpm-writer/src/common/defaults.ts, packages/fe-fpm-writer/src/common/types.ts, packages/fe-fpm-writer/src/section/index.ts, packages/fe-fpm-writer/src/section/types.ts, packages/fe-fpm-writer/templates/common/FragmentWithForm.xml, packages/fe-fpm-writer/templates/common/FragmentWithVBox.xml, packages/fe-fpm-writer/test/unit/__snapshots__/header-section.test.ts.snap, packages/fe-fpm-writer/test/unit/__snapshots__/section.test.ts.snap, packages/fe-fpm-writer/test/unit/__snapshots__/subsection.test.ts.snap, packages/fe-fpm-writer/test/unit/header-section.test.ts
Issue #1855
Previous version generated fragment content like:
```
<core:FragmentDefinition xmlns:core="sap.ui.core" xmlns="sap.m" xmlns:macros="sap.fe.macros">
<VBox>
<Button core:require="{ handler: 'project1/ext/fragment/Fsefsf'}" text="Fsefsf" press="handler.onPress" />
</VBox>
</core:FragmentDefinition>
```
Then if we add new button without `core:require` then press will not work:
```
<core:FragmentDefinition xmlns:core="sap.ui.core" xmlns="sap.m" xmlns:macros="sap.fe.macros">
<VBox>
<Button core:require="{ handler: 'project1/ext/fragment/Fsefsf'}" text="Fsefsf" press="handler.onPress" />
<Button text="Fsefsf" press="handler.onPress" />
</VBox>
</core:FragmentDefinition>
```
To improve usability - move `core:require` from inner element to wrapper element like:
``` …
```
=> fix(fpm-writer): Improve custom section fragments with event handler. Move 'core:require' attribute from inner element(Button) to wrapper(VBox)

.changeset/violet-pianos-own.md, packages/axios-extension/src/abap/abap-service-provider.ts, packages/axios-extension/src/abap/types/adt-types.ts, packages/axios-extension/test/abap/abap-service-provider.test.ts, packages/axios-extension/test/abap/catalog/v2-catalog-service.test.ts, packages/axios-extension/test/abap/catalog/v4-catalog-service.test.ts, packages/axios-extension/test/abap/mockResponses/atoSettingsNotS4C.xml
This PR fixes an incorrect implementation of the `isS4Cloud` function in the `axios-extension`. The function was incorrectly returning false if the client is configured for development (embedded Steampunk) and not extensibility.
While fixing it, I also removed a variable that was only exposed for testing and fixed the corresponding tests.
=> fix: isS4Cloud

.changeset/fuzzy-eagles-glow.md, packages/odata-service-inquirer/README.md, packages/odata-service-inquirer/src/index.ts, packages/odata-service-inquirer/test/unit/index-api.test.ts, packages/odata-service-inquirer/test/unit/prompts/prompt-helpers.test.ts
https://github.com/SAP/open-ux-tools/issues/1911
- Wait for load of i18n texts when calling `getPrompts` otherwise we may not have texts
- Add tests to cover
- Add tests for `prompt-helper`
- Update readme example
=> fix(odata-service-inquirer): Ensure prompt texts are loaded

.changeset/short-badgers-hear.md, packages/odata-service-writer/src/index.ts, packages/odata-service-writer/test/unit/index.test.ts
Fix for #1793 
- added `fs` for `await getWebappPath(basePath, fs)` to support memfs
=> fix(odata-service-writer): fs param mockserver logic

.changeset/ten-mails-lay.md, packages/odata-service-inquirer/src/index.ts
#1932 
Exports, for use in not-yet-moved datasources (to remove duplication):
- `ErrorHandler`
- `ERROR_TYPE`
=> `@sap-ux/odata-service-inquirer` adds additional exports

.changeset/smart-ads-melt.md, packages/preview-middleware-client/src/adp/init.ts, packages/preview-middleware-client/test/__mock__/sap/ui/core/Element.ts, packages/preview-middleware-client/test/unit/adp/init.test.ts
fixes #1929 
I successfully tested with UI5 Versions lower and bigger than 1.120
=> fix: CPE does not start UI Adaptation for ui5 versions lower than 1.120 for Adaptation Projects

.changeset/spicy-vans-lick.md, packages/ui5-config/package.json, packages/ui5-config/src/middlewares.ts, packages/ui5-config/src/types/middlewares.ts, packages/ui5-config/src/ui5config.ts, packages/ui5-config/test/__snapshots__/index.test.ts.snap, packages/ui5-config/test/index.test.ts, packages/ui5-config/tsconfig.json, packages/yaml/src/yaml-document.ts, packages/yaml/test/yaml-document.test.ts, pnpm-lock.yaml
#1965
- (`ui5-config`): Adds new property `authenticationType` to `FioriToolsProxyConfigBackend` interface
- (`ui5-config`): Adds function `getBackendComments` to retrieve comments for backend values
- (`ui5-config`): Updates `addBackendToFioriToolsProxydMiddleware` to check provided backend value for applicable comments and add them to the config
- (`yaml`): adds method `createNode` which creates a `Node` from the provided value and adds any relevant comments to the values
- (`yaml`): updates `toPathArray` to convert index values passed as strings to numbers, to be enable adding or updating config items within an array
=> tbi(ui5-config): add authType option and comments to yaml config

.changeset/six-buttons-build.md, packages/axios-extension/src/factory.ts, packages/axios-extension/test/abap/abap-adt-service.test.ts
#1977 
Adds cookies to the instance of the abap service provider returned for embedded steampunk
=> fix(axios-ext): add cookies for embedded steampunk service providers

.changeset/dirty-flies-develop.md, packages/project-access/src/index.ts, packages/project-access/src/project/cap.ts, packages/project-access/src/project/index.ts, packages/project-access/test/project/cap.test.ts
Issue #1975
We noticed issues:
1. app -> https://github.com/SAP-samples/btp-lcnc-capex
2. Please note - this app does not have any annotation in https://github.com/SAP-samples/btp-lcnc-capex/tree/main/app
3. When we call `getCapModelAndService` - then it gets cached following:
4. Then after generating new CAP app in `app` folder, calls for `cds.compile` does not return compiled result from newly added app from `app`
1st solution(not in PR anymore - 4b3d877611ee8066cfd9a10067d3f80f1b3439ba):
1. We have hardcoded `modelPaths` -> https://github.com/SAP/open-ux-tools/blob/main/packages/project-access/src/project/cap.ts#L147-L151
2. Validate those paths after `cds.load` calls
3. If modelPath had cached as `undefined`, then delete such cached entry
2nd solution(in PR):
1. export new method …
=> fix(project-access): export 'clearCdsModuleCache ' to allow clear project's cds cache from outside

.changeset/serious-lizards-hunt.md, packages/deploy-tooling/README.md, packages/deploy-tooling/src/cli/index.ts, packages/deploy-tooling/test/unit/cli/index.test.ts
Add `--authentication-type` to the available CLI params in deploy tooling (considerations for reentrance tickets)
=> feat(deploy-tooling): add auth type to cli params

packages/preview-middleware/test/unit/base/__snapshots__/flp.test.ts.snap
#1993 did not properly update snapshots after changes and PR build did not catch that.
No changeset needed as this only affects tests and the other PR already has the required changeset.
=> test: update snapshots

.changeset/cool-tables-fetch.md, packages/fe-fpm-writer/src/action/index.ts, packages/fe-fpm-writer/test/unit/__snapshots__/action.test.ts.snap
Fixes path for custom action when it is generated within custom section.
Previously it was generated in:
page.settings.body.CustomSection.actions.CustomAction
Now:
page.settings.body.**sections**.CustomSection.actions.CustomAction
Sections part was missing.
=> fix: Custom action path within custom section

.changeset/red-emus-play.md, packages/fe-fpm-writer/src/action/index.ts, packages/fe-fpm-writer/test/unit/__snapshots__/action.test.ts.snap
After some manual testing, I found out that custom actions under custom section are not generated in correct position:
page.settings.body.sections.CustomSection.actions.CustomAction
is not correct path, it should be (similarly like for header/footer actions under content property):
page.settings.**content**.body.sections.CustomSection.actions.CustomAction
=> fix: Generated custom action path

.changeset/chilled-mangos-appear.md, packages/axios-extension/src/factory.ts, packages/axios-extension/test/factory.test.ts
https://github.com/SAP/open-ux-tools/issues/2026
- Apply existing Axios config params
- Adds test to cover
=> fix(axios-entension): Prevent `createServiceForUrl` param over-writing

.changeset/loud-melons-hope.md, packages/odata-service-inquirer/src/prompts/prompts.ts, packages/odata-service-inquirer/test/unit/prompts/prompts.test.ts
https://github.com/SAP/open-ux-tools/issues/2060
- Remove not-yet-implemented message for now inplemented `odata service url` datasource
- Update test to cover
=> Remove unimplemented message for implemented datasource

.changeset/twelve-walls-teach.md, packages/create/README.md, packages/create/src/cli/add/html.ts, packages/create/src/cli/add/index.ts, packages/create/test/unit/cli/add/html.test.ts, packages/preview-middleware/src/base/config.ts, packages/preview-middleware/test/unit/base/__snapshots__/config.test.ts.snap, packages/preview-middleware/test/unit/base/config.test.ts
Adds support for #2089 
Improvements for #1332:
* improved README
* more meaningful function names
* more flexible internal functions
* handles the previously ignored `apps` config
=> Enhancing the `generatePreviewFiles` to support all configurations and CAP

.changeset/mean-ladybugs-try.md, packages/axios-extension/src/abap/adt-catalog/generators/ui-service-generator.ts, packages/axios-extension/test/abap/abap-adt-service.test.ts, packages/axios-extension/test/abap/mockResponses/generateResponse.json, packages/axios-extension/test/abap/mockResponses/generateResponse.xml
https://github.com/SAP/open-ux-tools/issues/2087
Fix parsing of ui service generation response, use `parseResponse` instead of json.parse
=> fix(axios-extension): parsing of service gen response

.changeset/perfect-peas-rest.md, .changeset/pretty-carrots-smoke.md, packages/adp-tooling/templates/project/webapp/manifest.appdescr_variant, packages/adp-tooling/test/unit/writer/__snapshots__/index.test.ts.snap, packages/create/src/cli/generate/adaptation-project.ts, packages/create/test/unit/cli/generate/adaptation-project.test.ts
fix for: https://github.com/SAP/open-ux-tools/issues/2080
- Remove  i18n model from template and only handle it dynamically in code
=> fix: Duplicate i18n model in manifest.appdescr_variant for Adp Project

.changeset/chilly-hounds-beg.md, packages/fiori-generator-shared/package.json
#2111
Added missing templates folder to the files array in the `package.json` of `fiori-generator-shared` to be included in installation of package.
=> Fix: Include Templates in 'files' Array of fiori-generator-shared Package.json

.changeset/young-garlics-smell.md, packages/project-access/src/index.ts, packages/project-access/src/project/index.ts, packages/project-access/src/project/module-loader.ts, packages/project-access/src/project/specification.ts, packages/project-access/test/project/specification.test.ts
#2066
- With rework of spec handling, this adds function `getSpecificationPath` to retrieve the specification path, depending if installed in project or cache.
- If installed in project, path is in `$project/node_modules/@sap/ux-specification`
- If provided by cache, path will be in `~/.fioritools/module-cache/@sap/ux-specification/$version/node_modules/@sap/ux-specification'`
=> feat: add `getSpecificationPath` to retrieve specification path

.changeset/tender-wombats-mix.md, packages/adp-tooling/src/types.ts, packages/adp-tooling/src/writer/options.ts, packages/adp-tooling/src/writer/project-utils.ts, packages/adp-tooling/test/unit/writer/__snapshots__/index.test.ts.snap
Fix for #2151.
- Removes safeMode from `AdpProjectData` interface because it is no longer needed.
- Changes the order of the blocks in ui5.yaml where customConfiguration is at the top for clearer structure.
=> fix: Remove safeMode from `adp-tooling` types and change order of ui5.yaml custom configuration

.changeset/good-waves-boil.md, packages/project-access/src/project/module-loader.ts, packages/project-access/test/project/module-loader.test.ts
Issues happens in Windows and MACOS
Scenario from #2170
1. install `@sap/ux-specification` in `C:\Users\{USER}` folder(replace with your user or adjust to OS) by running
```
npm install @sap/ux-specification
```
2. delete folder `C:\Users\{USER}\.fioritools\module-cache`(replace with your user or adjust to OS) by running
3. simulate `module-loader` to install `@sap/ux-specification` in  `C:\Users\{USER}\.fioritools` folder
In 3rd step code runs:
```
npm install @sap/ux-specification@1.120.14
```
and with such setup - it does not install dependencies in `C:\Users\{USER}\.fioritools\module-cache\@sap\ux-specification\{version}`
Proposal fixes:
1. use --prefix during install -  - https://stackoverflow.com/questions/14469515/how-to-npm-install-to-a-specified-directory, like:
```
npm install …
```
=> fix: module-loader does not install specification dependency in `.fioritools` folder when node_modules exists on C:\Users\{User} level

.changeset/warm-shirts-warn.md, packages/fe-fpm-writer/package.json, pnpm-lock.yaml
With #2175, functions (not only types any longer) from `@sap-ux/project-access` were added to fe-fpm-writer: https://github.com/SAP/open-ux-tools/pull/2175/files#diff-128f273a33ffbb49ddbdff27138d11ef5be6d7deaedcb60e65b52aba00f7932bR6
During consumption of `@sap-ux/fe-fpm-writer` that dependency is now required.
Adding to `dependencies` to add the required module.
=> fix(fe-fpm-writer): add `@sap-ux/project-access` to dependencies

.changeset/mighty-meals-divide.md, packages/odata-service-inquirer/src/prompts/connectionValidator.ts, packages/odata-service-inquirer/src/prompts/datasources/sap-system/abap-on-prem/questions.ts, packages/odata-service-inquirer/src/prompts/datasources/sap-system/new-system/questions.ts, packages/odata-service-inquirer/src/prompts/datasources/sap-system/validators.ts, packages/odata-service-inquirer/src/translations/odata-service-inquirer.i18n.json, packages/odata-service-inquirer/test/unit/prompts/connectionValidator.test.ts, packages/odata-service-inquirer/test/unit/prompts/sap-system/abap-on-prem/questions.test.ts
https://github.com/SAP/open-ux-tools/issues/2193
Fixes for :
- failed basic auth allows user to continue
- changing sap-client does not re-authenticate
- new system name is allowing an empty string which breaks storage
- new system names gets overwritten when changing client or system url
=> Fixes for multiple abap-on-prem new system prompts

.changeset/gorgeous-boats-look.md, packages/odata-service-inquirer/src/prompts/datasources/sap-system/new-system/questions.ts, packages/odata-service-inquirer/test/unit/prompts/sap-system/new-system/questions.test.ts
Fixes issue where the backend system is not added to the Prompt state when the default system name is used
=> fix(odata-service-inquirer): fix adding backend system to prompt state

.changeset/bright-cows-grab.md, packages/cds-odata-annotation-converter/package.json, packages/fiori-annotation-api/package.json, pnpm-lock.yaml
it is required to fix following warning in consumer package(in my case consumer of  `fpm-writer`):
=> chore: update "@sap/ux-cds-compiler-facade" from "1.14.0" to "1.14.1"

.changeset/tasty-plants-kick.md, packages/fiori-annotation-api/test/data/cds/layering/package.json, packages/fiori-annotation-api/test/unit/virtual-fs.ts
CDS layering test started failing after dce8838a2dcd93fc9922ade4e2a8118f9d950f9a. It was caused due to some changes in `node_modules`. However, since we're now using `mem-fs-editor` in the tests we can remove the logic that pre-fills file caches and just use the `Editor` object.
Adding changeset from #2230, since it failed to publish.
=> test: simplify virtual fs logic

.changeset/selfish-forks-relax.md, packages/fe-fpm-writer/src/building-block/index.ts, packages/fe-fpm-writer/test/unit/__snapshots__/building-block.test.ts.snap, packages/fe-fpm-writer/test/unit/building-block.test.ts, packages/fe-fpm-writer/test/unit/sample/building-block/webapp-prompts-cap/app/incidents/webapp/manifest.json, packages/fe-fpm-writer/test/unit/sample/building-block/webapp-prompts/webapp/manifest.json, packages/fe-fpm-writer/test/unit/sample/building-block/webapp/manifest.json
Issue #2241 
When adding a building block validate minimum required `sap.fe.core` library in manifest.json, not `sap.fe.templates`.
=> Fix(fpm-writer): change building block required library to sap.fe.core

.changeset/gentle-ligers-allow.md, packages/store/src/index.ts
allow getFioriToolsDirectory, FioriToolsSettings to be used by other modules in place of common utils in tools suite
=> export getFioriToolsDirectory, FioriToolsSettings from store

.changeset/five-onions-draw.md, packages/abap-deploy-config-inquirer/package.json, packages/abap-deploy-config-inquirer/src/index.ts, packages/abap-deploy-config-inquirer/src/prompts/conditions.ts, packages/abap-deploy-config-inquirer/src/prompts/defaults.ts, packages/abap-deploy-config-inquirer/src/prompts/questions/config/package.ts, packages/abap-deploy-config-inquirer/src/service-provider-utils/abap-service-provider.ts, packages/abap-deploy-config-inquirer/src/service-provider-utils/transport-config.ts, packages/abap-deploy-config-inquirer/src/service-provider-utils/transport-list.ts, packages/abap-deploy-config-inquirer/src/types.ts, packages/abap-deploy-config-inquirer/test/prompts/conditions.test.ts, packages/abap-deploy-config-inquirer/tsconfig.json, pnpm-lock.yaml
#2128
- Removes use of feature toggle and adds `useAutocomplete` as an option
- Add return type to functions to fix lint warnings
=> fix(abap-deploy-config): add autocomplete option and tidy add return types

.changeset/nine-weeks-cry.md, packages/abap-deploy-config-inquirer/src/constants.ts, packages/abap-deploy-config-inquirer/src/prompts/validators.ts, packages/abap-deploy-config-inquirer/test/prompts/defaults.test.ts, packages/abap-deploy-config-inquirer/test/prompts/validators.test.ts
#2128
Convert packages to upper case for verifying when it is a local package
=> fix(abap-deploy-config): fix for local pkg verification

.changeset/weak-peaches-battle.md, packages/fe-fpm-writer/templates/page/custom/1.84/ext/Controller.js, packages/fe-fpm-writer/templates/page/custom/1.84/ext/Controller.ts, packages/fe-fpm-writer/templates/page/custom/1.94/ext/Controller.js, packages/fe-fpm-writer/templates/page/custom/1.94/ext/Controller.ts, packages/fe-fpm-writer/test/unit/page/__snapshots__/custom.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/fpm.test.ts.snap
The current template don't include any example of calling back super.onInit() or PageController.prototype.onInit.apply(this, arguments).
This is mandatory for application otherwise the controllers are not properly instantiated :)
=> fix: ensure that the controller template include an example call to super

.changeset/stale-falcons-cry.md, packages/ui-components/src/components/UIContextualMenu/UIContextualMenu.tsx, packages/ui-components/test/unit/components/UIContextualMenu.test.tsx
During updating `ui-components` to latest version, we noticed that method `getUIContextualMenuItemStyles` expects first param `props` to be required. 
It was introduced during -> https://github.com/SAP/open-ux-tools/pull/2234
but according to code - method can be adjusted to make `props` as optional.
=> fix(ui-components): UIContextualMenu.getUIContextualMenuItemStyles - make `props` param option

.changeset/dull-pillows-grab.md, .changeset/eleven-scissors-mate.md, packages/i18n/src/utils/resolve.ts, packages/i18n/src/write/cap/create.ts, packages/i18n/test/unit/utils/resolve.test.ts, packages/project-access/src/project/access.ts, packages/project-access/src/project/i18n/write.ts, packages/project-access/src/types/access/index.ts
We noticed that method `getCapI18nFolder` expects that second parameter `path` should be relative path to cds file, while other methods and also `ApplicationStructure` expects/contains absolute paths, then proposal is to adjust function `getCapI18nFolder` to same expectation.
=> fix(i18n): CAP scenario. `getCapI18nFolder` -> handle absolute path instead of relative path to resolve i18n folder

.changeset/moody-frogs-battle.md, packages/ui-components/src/components/UIContextualMenu/UIContextualMenu.tsx, packages/ui-components/test/unit/components/UIContextualMenu.test.tsx
During updating `ui-components` to latest version, we noticed that method `getUIcontextualMenuCalloutStyles` expects first param `props` to be required. 
It was introduced during -> https://github.com/SAP/open-ux-tools/pull/2234
but according to code - method can be adjusted to make `props` as optional. 
Additionally - as only `styles` are used from `props`, then changed param from `props` to `styles` to allow pass styles without required properties like `items`
=> fix(ui-components): UIContextualMenu.getUIcontextualMenuCalloutStyles- change `props` param to `styles` param and make it as optional

.changeset/bright-spiders-carry.md, packages/odata-service-inquirer/jest.config.js, packages/odata-service-inquirer/src/prompts/connectionValidator.ts, packages/odata-service-inquirer/src/prompts/datasources/service-url/questions.ts, packages/odata-service-inquirer/src/prompts/datasources/service-url/validators.ts, packages/odata-service-inquirer/test/unit/prompts/service-url/questions.test.ts, packages/odata-service-inquirer/test/unit/prompts/service-url/validators.test.ts
Fix for: https://github.com/SAP/open-ux-tools/issues/2309
- Reverts behaviour to earlier version when annotations were retrieved
- Updates unit tests
=> fix(odata-service-inquirer): #2309 fix for annotations not retrieved using service url prompt

.changeset/wet-bats-shake.md, packages/abap-deploy-config-inquirer/package.json, pnpm-lock.yaml
Fix for https://github.com/SAP/open-ux-tools/issues/2128
- package.json missing dependencies when loading independently.
=> fix(abap-deploy-config-inquirer ): add missing dependencies

.changeset/four-roses-pull.md, packages/preview-middleware-client/src/adp/quick-actions/load.ts, packages/preview-middleware-client/src/messagebundle.properties, packages/preview-middleware-client/test/unit/adp/quick-actions/fe-v2.test.ts, packages/preview-middleware-client/test/unit/adp/quick-actions/fe-v4.test.ts, packages/preview-middleware-client/test/unit/adp/quick-actions/load.test.ts
Use correct case in quick action titles.
Also added feature toggle to enable quick actions. By default they will be disabled.
=> fix(cpe): quick action titles

.changeset/rich-carrots-pump.md, packages/abap-deploy-config-inquirer/src/prompts/conditions.ts, packages/abap-deploy-config-inquirer/src/prompts/questions/config/package.ts, packages/abap-deploy-config-inquirer/src/prompts/validators.ts, packages/abap-deploy-config-inquirer/test/prompts/conditions.test.ts, packages/abap-deploy-config-inquirer/test/prompts/validators.test.ts
Fix for https://github.com/SAP/open-ux-tools/issues/2128
Two issues found
1. bug found with manual package being shown if package choice is a list
- tests updated to confirm flow
2. Issue with abap state not being updated with the target URL so transport request is returning incorrect error as `createAbapServiceProvider` was throwing the exception `'Unable to handle the configuration in the current environment.'` since the URL was empty.
- tests to cover state change
=> fix(abap-deploy-config-inquirer): bug found with showing manual package prompt

.changeset/rotten-hotels-fry.md, packages/abap-deploy-config-inquirer/src/prompts/questions/abap-target.ts, packages/abap-deploy-config-inquirer/src/prompts/validators.ts, packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json, packages/abap-deploy-config-inquirer/test/prompts/questions/abap-target.test.ts, packages/abap-deploy-config-inquirer/test/prompts/validators.test.ts
Fix for https://github.com/SAP/open-ux-tools/issues/2128
Two issues found
- mandatory field not required
- translation misconfigured
=> fix(abap-deploy-config-inquirer ): remove manadatory field, cleanup translation text

.changeset/twelve-lemons-joke.md, packages/cap-config-writer/package.json, pnpm-lock.yaml
https://github.com/SAP/open-ux-tools/issues/2365
Moves dep only types are consumed
=> tbi(cap-config-writer): Move type only dependency -> dev dependency

packages/odata-service-writer/src/index.ts, packages/odata-service-writer/src/types.ts, packages/ui5-config/src/middlewares.ts, packages/ui5-config/src/ui5config.ts, packages/ui5-config/test/__snapshots__/index.test.ts.snap, packages/ui5-config/test/index.test.ts
https://github.com/SAP/open-ux-tools/issues/2326
- `odata-service-writer`
Extended the `OdataService` interface to include the `ignoreCertError` property.
- `ui5-config`
Added logic to include `ignoreCertError` value in yaml file if provided.
=> Add ignore cert error to odata-service-writer 

.changeset/neat-poems-boil.md, packages/abap-deploy-config-inquirer/src/prompts/validators.ts, packages/abap-deploy-config-inquirer/test/prompts/validators.test.ts
Verify the destination prompt has input rather than automatically returning true
=> fix(abap-delploy-config): verify destination input

.changeset/five-pans-glow.md, packages/odata-service-inquirer/src/prompts/datasources/metadata-file/validators.ts, packages/odata-service-inquirer/test/unit/prompts/metadata-file/fixtures/validatorTest.xml, packages/odata-service-inquirer/test/unit/prompts/metadata-file/validators.test.ts
Fix for https://github.com/SAP/open-ux-tools/issues/2397
- Correctly escapes and assigns result
- Adds test to cover
=> Fixes ampersand escaping

.changeset/rude-walls-clap.md, packages/ui-components/src/components/UILink/UILink.tsx, packages/ui-components/stories/UILink.story.tsx, packages/ui-components/test/unit/components/UILink.test.tsx
It was reported that when UIlink is disabled using property `disabled`, then there no any visual difference that link is disabled.
Changes:
1. Apply styles for link when property 'disabled' is 'true';
2. Update storybook with option to disable links in example
=> fix(ui-components): Applied missing styles for the disabled state of UILink.

.changeset/cold-hotels-marry.md, packages/launch-config/src/debug-config/config.ts, packages/launch-config/src/launch-config-crud/create.ts, packages/launch-config/src/translations/launch-config.i18n.json, packages/launch-config/src/types/types.ts, packages/launch-config/test/debug-config/config.test.ts, packages/launch-config/test/launch-config-crud/create.test.ts
This update removes the `ProjectDataSourceType` from `DebugConfig` and introduces the use of a new flag, `skipLiveScripts`. Now, live scripts are only generated when `skipLiveScripts` is set to false.
=> Add skipLiveScripts flag to `DebugConfig` options 

.changeset/popular-bees-sip.md, packages/nodejs-utils/src/commandRunner.ts, packages/nodejs-utils/test/unit/commandRunner.test.ts
https://github.com/SAP/open-ux-tools/issues/2433
CommandRunner was executing `npm -g root` without the option `shell = true` on Windows resulting in extension generator packages not being found.
=> Fix for CommandRunner not spawning child processes on Windows with shell opt

.changeset/chilly-dragons-call.md, packages/ui-components/src/components/UIContextualMenu/UIContextualMenu.scss
Fix for Sass warning about deprecate usage of '/' for division outside of calc:
=> fix: Sass warning about deprecate usage of '/' for division outside of calc

.changeset/mighty-impalas-sit.md, packages/ui-prompting/src/components/Question/Question.tsx, packages/ui-prompting/src/components/Questions/Questions.tsx, packages/ui-prompting/test/unit/components/Questions.test.tsx
Do not show the translation input if the translation props are not provided - if there no I18N bundle and no translation event handler
=> fix:(ui-prompting) Do not show the translation input if the translation props are not provided

.changeset/rotten-dolls-try.md, packages/abap-deploy-config-inquirer/src/prompts/helpers.ts, packages/abap-deploy-config-inquirer/src/prompts/index.ts, packages/abap-deploy-config-inquirer/test/index.test.ts, packages/abap-deploy-config-inquirer/test/prompts/helpers.test.ts
Introduced in https://github.com/SAP/open-ux-tools/pull/2449 .. when no backend target exists an error is thrown trying to replace trailing slash
=> fix(abap-deploy-config): fix backend target choices check

.changeset/many-carrots-notice.md, packages/project-access/src/project/cap.ts, packages/project-access/test/project/cap.test.ts
In some cases such as Data Editor it is only expected to compile the db model and not the full CAP model. 
Updating `getCapModelAndServices` to optionally pass `pathSelection`
=> TBI - Allow filtering folder(s) to compile CAP model from

.changeset/empty-carpets-stare.md, packages/control-property-editor/src/panels/properties/HeaderField.tsx, packages/control-property-editor/src/panels/properties/PropertiesList.tsx
Removed popup for control id and added tooltip for control id and control type values.
=> fix: refactor control id and control type

.changeset/witty-carrots-give.md, packages/ui-components/src/components/UIComboBox/UIComboBox.tsx, packages/ui-components/src/components/UIDropdown/UIDropdown.tsx, packages/ui-components/test/unit/components/UICombobox.test.tsx, packages/ui-components/test/unit/components/UIDropdown.test.tsx
We noticed problem with `UIComboBox`, `UIDropdown` - if we pass callout props to them, then all `calloutProperties` are overwritten instead of merging it with properties defined within `UIComboBox`, `UIDropdown` components
=> fix(ui-components): UIComboBox, UIDropdown: Allow extending 'calloutProps' instead of overwriting.

.changeset/fresh-hotels-tap.md, packages/ui-components/src/components/UIDropdown/UIDropdown.scss, packages/ui-components/src/styles/_variables.scss
BUG - Values in the UI.Dropdown control is not centered aligned (vertically)
issue #2140
=> fix(ui-components): #2140 - fix dropdown vertical align input field

.changeset/gorgeous-melons-develop.md, packages/ui-components/.storybook/preview.js, packages/ui-components/src/index.tsx, packages/ui-components/src/theme/index.ts, packages/ui-components/stories/UICallout.story.tsx, packages/ui-components/stories/UICalloutCollisionTransform.story.tsx, packages/ui-components/stories/UICheckbox.story.tsx, packages/ui-components/stories/UIChoiceGroup.story.tsx, packages/ui-components/stories/UICombobox.story.tsx, packages/ui-components/stories/UIContextualMenu.story.tsx, packages/ui-components/stories/UICreateSelect.story.tsx, packages/ui-components/stories/UIDatePicker.story.tsx, packages/ui-components/stories/UIDialog.story.tsx, packages/ui-components/stories/UIDropdown.story.tsx, packages/ui-components/stories/UIFlexibleTable.story.tsx, packages/ui-components/stories/UIIcon.story.tsx, packages/ui-components/stories/UILabel.story.tsx, packages/ui-components/stories/UILoader.story.tsx, packages/ui-components/stories/UIQuickNavigation.story.tsx, packages/ui-components/stories/UISearchBox.story.tsx, packages/ui-components/stories/UITextInput.story.tsx, packages/ui-components/stories/UIToggleGroup.story.tsx, packages/ui-components/stories/UITooltip.story.tsx, packages/ui-components/stories/UITranslationInput.story.tsx, packages/ui-components/stories/Utilities.story.tsx, packages/ui-components/test/unit/theme/Theme.test.ts
#2474
changes:
1. new API method `initTheme`, which overwrites default fluent-ui theme styles by removing  `-webkit-font-smoothing: antialiased`
2. update storybook to do not call `initIcons` in each story separately, but run within `preview.js` once + same with `initTheme`
=> feat(ui-components): new API method `initTheme` to override default Fluent UI styles, removing `-webkit-font-smoothing: antialiased`.

.changeset/lazy-planets-accept.md, packages/ui-components/src/components/UIComboBox/UIComboBox.tsx, packages/ui-components/stories/UICombobox.story.tsx, packages/ui-components/test/unit/components/UICombobox.test.tsx
We noticed that we can have keys in combobox option different than text, and we need allow to find such entries by searching by key.
LIke options:
```
[
{ 'key': 'test1', 'text': 'test1' },
{ 'key': 'dummy', 'text': 'dummy' },
{ 'key': 'customer', 'text': 'customer' },
{ 'key': 'name', 'text': 'name' },
{ 'key': 'employee', 'text': 'employee' },
{ 'key': 'ID', 'text': 'ID' },
{ 'key': 'tripEndDate', 'text': 'tripEndDate' },
{ 'key': 'bookings', 'text': 'bookings', 'itemType': UISelectableOptionMenuItemType.Divider },
{ 'key': 'bookings', 'text': 'bookings', 'itemType': UISelectableOptionMenuItemType.Header },
{ 'key': 'bookings/airlines', 'text': 'airlines' },
{ 'key': 'bookings/bookingDate', 'text': 'bookingDate' },
{ 'key': 'bookings/DateOnBookings', 'text': 'DateOnBookings' },
{ 'key': …
```
=> UICombobox: Added new property 'searchByKeyEnabled' to allow searching by the option's "key" in addition to "text".

.changeset/witty-seas-battle.md, packages/preview-middleware-client/src/adp/quick-actions/fe-v2/change-table-columns.ts, packages/preview-middleware-client/src/adp/quick-actions/fe-v2/create-page-action.ts, packages/preview-middleware-client/src/adp/quick-actions/fe-v2/create-table-action.ts, packages/preview-middleware-client/src/adp/quick-actions/fe-v4/change-table-columns.ts, packages/preview-middleware-client/src/adp/quick-actions/load.ts, packages/preview-middleware-client/test/unit/adp/quick-actions/fe-v2.test.ts, packages/preview-middleware-client/test/unit/adp/quick-actions/fe-v4.test.ts
Enables quick actions by default. The following quick actions are still behind feature flag:
- Custom Action
- Custom Table Columns
=> feat: enable quick actions

.changeset/smart-pears-build.md, packages/inquirer-common/src/i18n.ts, packages/inquirer-common/src/index.ts, packages/ui5-application-inquirer/src/i18n.ts, packages/ui5-application-inquirer/test/unit/i18n.test.ts, packages/ui5-library-inquirer/src/i18n.ts, packages/ui5-library-inquirer/test/unit/i18n.test.ts
https://github.com/SAP/open-ux-tools/issues/2496
Exposes function to add the resource bundle for the `@sap-ux/inquirer-common` module
This allows consuming modules to call this after initialising i18next and ensuring all translations are loaded at the time of prompting
=> fix(inquirer): adding i18n bundle of common module in consumers

.changeset/cyan-eggs-swim.md, packages/ui-components/src/components/UIChoiceGroup/UIChoiceGroup.tsx, packages/ui-components/src/components/UIComboBox/UIComboBox.tsx, packages/ui-components/src/components/UIDropdown/UIDropdown.tsx, packages/ui-components/src/components/UIInput/UITextInput.tsx, packages/ui-components/src/components/UILabel/UILabel.tsx, packages/ui-components/src/components/types.ts, packages/ui-components/stories/UITextInput.story.tsx, packages/ui-components/test/__snapshots__/UITextfield.test.tsx.snap, packages/ui-components/test/unit/components/UIChoiceGroup.test.tsx, packages/ui-components/test/unit/components/UICombobox.test.tsx, packages/ui-components/test/unit/components/UIDropdown.test.tsx, packages/ui-components/test/unit/components/UITextfield.test.tsx
ignore asterisk for screen readers. Speech history when issue appears:
solution -> https://a11ysupport.io/tests/tech__css__css_generated_content_alt
after solution, speech history:
=> fix(ui-components): ignore asterisk for screen readers

.changeset/young-coins-marry.md, packages/preview-middleware-client/src/adp/quick-actions/fe-v2/create-table-custom-column.ts
Fixed bug. Click on quick action doesn't work with Analytical/Grid/Tree tables in v2
=> fix: Create Custom Table Column quick action bug fix

.changeset/fuzzy-toes-talk.md, packages/ui5-info/src/ui5-version-fallback.ts, packages/ui5-info/src/ui5-version-info.ts, packages/ui5-info/test/__snapshots__/ui5-version-info.test.ts.snap, packages/ui5-info/test/ui5-version-info.test.ts
With changes in https://github.com/SAP/open-ux-tools/pull/2189 to move from using `versionoverview` the try/catch + fallback for offline or errors was removed. 
Updates in this PR : 
- `supportedUi5VersionFallbacks` now also returns property `support` as it is useful for the consumer (for labelling and grouping versions)
-  when the option `includeMaintained` is passed, the call to `retrieveUI5VersionsCache` is wrapped in a try/catch and will fallback to `supportedUi5VersionFallbacks`
=> fix(ui5-info): fix fallback logic for retrieving maintained versions

.changeset/perfect-seals-try.md, packages/ui-components/src/components/UITranslationInput/UITranslationInput.tsx, packages/ui-components/src/components/UITreeDropdown/UITreeDropdown.tsx, packages/ui-components/stories/UITreedropdown.story.tsx, packages/ui-components/test/unit/components/UITreeDropdown.test.tsx
Issue -> #2545
UITreeDropdown change callback being triggered twice on first selection:
1. First call with empty value
2. Second call with selected value
screenshot where `console.log` placed within change callback:
=> fix(ui-components): UITreeDropdown change callback being triggered twice on first selection:

.changeset/cold-pumas-hear.md, packages/ui-components/src/components/UIComboBox/UIComboBox.tsx, packages/ui-components/stories/UICombobox.story.tsx, packages/ui-components/test/unit/components/UICombobox.test.tsx
We have a requirement to display certain custom ComboBox items that do not match the current search query. To accomplish this, we need to extend the UIComboBox interface by adding a new property, `customSearchFilter`, which allows passing a custom filter function to apply additional filtering logic on top of the default search.
Screenshots from storybook based on filter -> https://github.com/SAP/open-ux-tools/blob/feat/allowPassCustomFilterForCombobox/packages/ui-components/stories/UICombobox.story.tsx#L500
=> feat(ui-components): allow to pass custom filter function for combobox search

.changeset/swift-kids-laugh.md, packages/control-property-editor-common/src/api.ts, packages/control-property-editor/src/panels/changes/ConfigChange.tsx, packages/control-property-editor/src/panels/properties/InputTypeWrapper.tsx, packages/control-property-editor/test/unit/panels/changes/ChangesPanel.test.tsx, packages/preview-middleware-client/src/cpe/changes/service.ts
After #2458 Adaptation Editor crashes if there are personalisation changes in the project.
Also removed expression change option for configuration changes.
=> fix: adaptation editor crash

.changeset/light-suits-crash.md, packages/abap-deploy-config-inquirer/src/utils.ts, packages/btp-utils/src/app-studio.ts, packages/btp-utils/src/destination.ts, packages/btp-utils/test/app-studio.test.ts, packages/btp-utils/test/mockResponses/destinations.json, packages/cf-deploy-config-inquirer/src/prompts/prompt-helpers.ts, packages/cf-deploy-config-writer/src/utils.ts, packages/odata-service-inquirer/src/prompts/datasources/sap-system/system-selection/prompt-helpers.ts
#2555 
Adds options `ListDestinationOpts` for btp-utils API `listDestinations`
- `stripS4HCApiHosts` removes `-api` from host name
=> feat(btp-utils): adds options for list destination api

.changeset/chatty-chefs-smile.md, packages/cf-deploy-config-writer/src/mta-config/index.ts, packages/cf-deploy-config-writer/src/utils.ts, packages/cf-deploy-config-writer/test/unit/utils.test.ts
Fix for https://github.com/SAP/open-ux-tools/issues/2007
- allow `_` to be written to mta configuration
=> fix(cf-deploy-config-writer): allow underscore as a supported character

.changeset/nice-brooms-grab.md, packages/fiori-annotation-api/src/avt/to-internal.ts, packages/fiori-annotation-api/test/unit/__snapshots__/fiori-service.test.ts.snap, packages/fiori-annotation-api/test/unit/avt/__snapshots__/to-internal.test.ts.snap, packages/fiori-annotation-api/test/unit/avt/to-internal.test.ts, packages/fiori-annotation-api/test/unit/fiori-service.test.ts
#2530 contains inaccurate type update for collection values which does not match the parser and converter implementation. `StringExpression` is expected, but parser and converter only create regular string values. So we need to make sure that this case is also correctly handled.
=> fix: writing collections with string values

.changeset/light-crabs-camp.md, packages/preview-middleware-client/src/adp/quick-actions/fe-v2/lr-enable-semantic-date-range-filter-bar.ts, packages/preview-middleware-client/src/adp/quick-actions/fe-v2/lr-enable-table-filtering.ts, packages/preview-middleware-client/src/adp/quick-actions/fe-v2/utils.ts, packages/preview-middleware-client/test/unit/adp/quick-actions/fe-v2.test.ts, packages/preview-middleware-client/types/sap.ui.rta.d.ts
hide the manifest change actions from the quick action list, if the manifest of the underlying app has array structure.
=> fix: hide quick action if the application has old manifest structure

.changeset/silver-rabbits-beam.md, packages/ui5-application-inquirer/src/i18n.ts, packages/ui5-application-inquirer/test/unit/prompts/prompt-helpers.test.ts
Fix for: https://github.com/SAP/open-ux-tools/issues/2590
- Loads bundles explicitly
=> fix(ui5-application-inquirer): Fix non-loaded i18n texts

.changeset/pretty-ghosts-cough.md, packages/odata-service-writer/src/index.ts, packages/odata-service-writer/src/updates.ts, packages/odata-service-writer/test/unit/index.test.ts, packages/odata-service-writer/test/unit/updates.test.ts
After introduction of multiple services for `odata-service-writer` (https://github.com/SAP/open-ux-tools/pull/2499), existing services for previously generated applications should be checked and adapted if necessary.
Previously whenever service was generated, service files were always generated in localService folder. Currently multiple services are supported so each service should have its own folder.
For example:
>       "mainService": {
>         "uri": "/sap/opu/odata4/dmo/sb_travel_mdsk_o4/srvd/dmo/sd_travel_mdsk/0001/",
>         "type": "OData",
>         "settings": {
>           "annotations": [
>             "annotation"
>           ],
>           "localUri": "localService/metadata.xml",
>           "odataVersion": "4.0"
>         }
>       }
`localUri` of the existing OData …
=> fix: Modify existing services

.changeset/clever-chicken-grab.md, packages/jest-environment-ui5/test/unit/__snapshots__/ui5MappingStrategy.test.js.snap, packages/jest-environment-ui5/test/unit/ui5MappingStrategy.test.js
The snapshot refers to the version of the package, which then is bumped ... stupid me :)
=> fix: impossible snapshots

.changeset/new-hornets-taste.md, packages/odata-service-inquirer/src/prompts/connectionValidator.ts, packages/odata-service-inquirer/test/unit/prompts/connectionValidator.test.ts
Fix for : https://github.com/SAP/open-ux-tools/issues/2673
- Lowercase dest name before replacing to portable format as `btp-utils.getDestinationUrlForAppStudio` returns inconsistent origin casing (lowercases origin if path passed,  but not otherwise)
- Modify test to cover
=> fix(odata-service-inquirer): Wrong dest url format in yamls

.changeset/giant-garlics-tan.md, packages/axios-extension/src/abap/catalog/v4-catalog-service.ts, packages/axios-extension/src/base/odata-service.ts, packages/axios-extension/test/abap/catalog/v4-catalog-service.test.ts
Fixes :https://github.com/SAP/open-ux-tools/issues/2679
- Odata control info was not being returned by the `parseODataResponse` function and so `@odata.nextlink` was not available for paging request construction
- Adds optional inclusion of odata control info (`@odata` annotations) to get `@odata.nextlink` control info
- Fixes tests which were returning false positives
- Adds support for `URLSearchParams` when passing axios config to `get` url since axios supports params as `object` or `URLSearchParams`
=> fix(axios-extension): listing v4 odata services only returns first page

.changeset/tough-poems-smile.md, packages/odata-service-writer/src/types.ts, packages/odata-service-writer/templates/extend/manifest.json, packages/odata-service-writer/test/test-data/manifest-json/edmx-manifest-local-annotation.ts, packages/odata-service-writer/test/test-data/manifest-json/edmx-manifest-local-annotations.ts, packages/odata-service-writer/test/unit/updates.test.ts
1. Improved manifest.json template.
JSON parsing error was thrown for case with `annotations: []` and defined `localAnnotationsName`.
2. Updated `localAnnotationsName` type to also allow to use local annotations defined in array.
=> fix: Manifest template for services

.changeset/fifty-nails-search.md, packages/ui-components/src/components/UIChoiceGroup/UIChoiceGroup.tsx, packages/ui-components/src/components/UIList/UIList.tsx, packages/ui-components/src/components/UILoader/UILoader.tsx, packages/ui-components/src/components/index.tsx, packages/ui-components/src/utilities/Focus.ts
Add missing exports:
- `UIChoiceGroup` - export interface `IChoiceGroup`
- `UIList` - export interfaces `UIGroup`, `UIGroupedListProps`, `UIGroupHeaderProps`, `UIGroupRenderProps`
- `UILoader` - export enum `UISpinnerSize `
- `UIStack` - export component `UIStack`
- focus utility functions - export method `isElementTabbable`
=> feat(ui-components): add multiple missing exports

.changeset/empty-turtles-complain.md, packages/odata-service-writer/src/updates.ts, packages/odata-service-writer/test/test-data/manifest-json/edmx-manifest-older-services.ts, packages/odata-service-writer/test/unit/updates.test.ts
Instead of updating existing services in manifest and then reading manifest file again to enhance with new service, now it will only write changes to manifest after existing services are modified and new services added.
In summary, writeJSON calls reduced by one.
=> chore: Improved service updates in manifest

.changeset/loud-mangos-love.md, packages/jest-environment-ui5/src/index.js
Node.js introduced a readonly global.navigator property with Node.js 21. That is, attempting to (re-)assign the property now breaks.
It turns out that the global.navigator object is not used in the Jest environment. window.navigator is, but that property is unaffected by this change.
Replaces #2748
=> fix(@sap-ux/jest-environment-ui5): Do not reassign global.navigator

.changeset/two-wasps-sort.md, packages/app-config-writer/src/preview-config/ui5-yaml.ts
prevent crash in case a ui5 yaml config has a preview middleware config without `configuration` property.
🙈 _Thou shall always use the correct type_ 🙈 
```
Cannot read properties of undefined (reading 'configuration')
TypeError: Cannot read properties of undefined (reading 'configuration')
at updateDefaultTestConfig (<local path here>\npm-cache\_npx\b4bdc7e504f3256c\node_modules\@sap-ux\app-config-writer\dist\preview-config\ui5-yaml.js:273:31)
at async convertToVirtualPreview (<local path here>\npm-cache\_npx\b4bdc7e504f3256c\node_modules\@sap-ux\app-config-writer\dist\preview-config\index.js:39:9)
at async convertPreview (<local path here>\npm-cache\_npx\b4bdc7e504f3256c\node_modules\@sap-ux\create\dist\cli\convert\preview.js:37:20)
at async Command.<anonymous> (<local path …
```
=> fix(app-config-writer): preview config update default configs

.changeset/flat-readers-buy.md, packages/ui-components/src/components/UIToggle/UIToggle.tsx, packages/ui-components/test/unit/components/UIToggle.test.tsx
This update introduces hover styles for the UIToggle component's thumb when in a checked state. It improves the visual feedback for users interacting with the toggle.
=> feat: add hover styles for UIToggle in checked state

.changeset/spicy-lizards-juggle.md, packages/preview-middleware-client/src/cpe/changes/service.ts, packages/preview-middleware-client/src/cpe/connector-service.ts, packages/reload-middleware/src/base/livereload.ts, packages/reload-middleware/test/unit/base/livereload.test.ts
Fix for #2763.
- Adds the change type `appdescr_ui_gen_app_changePageConfig.change` for the reload middleware to set the `__SAP_UX_MANIFEST_SYNC_REQUIRED__` to true to then sync the merged manifest.
=> fix: Manifest change for enabling semantic date range has no effect on running app with UI5 latest snapshot (=>1.132)

.changeset/rich-horses-mix.md, packages/axios-extension/src/abap/ui5-abap-repository-service.ts, packages/axios-extension/test/abap/ui5-abap-repository-service.test.ts
#2776 
Adds entry to `abapUrlReplaceMap` to accomodate s4 hana cloud systems with `.lab`
=> feat(axios-ext): add entry for s4 hana cloud urls with .lab

.changeset/tidy-frogs-joke.md, packages/ui5-library-writer/templates/common/1.120.0/src/baselibrary/themes/sap_belize/library.source.less, packages/ui5-library-writer/templates/common/1.120.0/src/baselibrary/themes/sap_belize_hcb/library.source.less, packages/ui5-library-writer/templates/common/1.120.0/src/baselibrary/themes/sap_belize_hcw/library.source.less, packages/ui5-library-writer/templates/common/1.120.0/src/baselibrary/themes/sap_belize_plus/library.source.less, packages/ui5-library-writer/test/__snapshots__/index.test.ts.snap
https://github.com/SAP/open-ux-tools/issues/2779
- remove belize theme template files when UI5 version >1.120.0
- fixing failing deployment for generated library
- updated snapshots
=> fix(ui5-lib-writer): remove belize template files for 1.120.0

.github/workflows/pipeline.yml
Testing just updating version. Dont think `overwrite` option is required as the playwright reports seem to be retained and therefore must be using a rolling file name.
=> Update pipeline.yml with actions/upload-artifact@v4

.changeset/wise-carrots-dance.md, packages/odata-service-inquirer/src/prompts/edmx/entity-helper.ts, packages/odata-service-inquirer/test/unit/prompts/edmx/entity-helper.test.ts, packages/odata-service-inquirer/test/unit/prompts/edmx/test-data/metadataV4WithAliasAggregateTransforms.xml
#2798
As `@sap-ux/annotation-converter` resolves the alias, the only additional logic is needed is to add a check on the entity type for aggregation apply supported annotations (as a fallback).
=> fix(odata-inq): add check on entity type for aggregation annotation

.changeset/silly-zoos-lick.md, packages/abap-deploy-config-sub-generator/src/app/index.ts, packages/abap-deploy-config-sub-generator/test/app.test.ts, packages/abap-deploy-config-sub-generator/test/fixtures/samplelib/package.json, packages/abap-deploy-config-sub-generator/test/fixtures/samplelib/ui5.yaml, packages/abap-deploy-config-writer/src/config.ts, packages/abap-deploy-config-writer/test/sample/test.ui5.lib/base-config.yaml
- Removes prompting for the generation of index.html during deployment for libraries
- Also adds library test (there is a tests for libs in the writer)
- Checks the custom task `ui5-task-flatten-library` is not already present in base config (ui5.yaml) before adding it
=> fix(abap-deploy): fix support for library deployment

.changeset/three-olives-brake.md, packages/jest-environment-ui5/package.json, packages/jest-environment-ui5/src/env/mockXHR.js, packages/jest-environment-ui5/src/env/ui5Environment.js, packages/jest-environment-ui5/src/index.js, packages/jest-environment-ui5/test/unit/mockXHR.test.js
When doing component based testing it might be useful to refer to an actual mockserver. 
Furthermore if we want to leverage more complex snapshot (including screenshots), being able to load CSS is desired, so an option was added for that.
=> feat: add support for external HTTP calls

.changeset/long-lions-cheat.md, packages/flp-config-inquirer/src/prompts/prompts.ts, packages/flp-config-inquirer/src/prompts/questions/advanced.ts, packages/flp-config-inquirer/src/prompts/questions/basic.ts, packages/flp-config-inquirer/test/index.test.ts, packages/flp-config-inquirer/test/prompts/questions/advanced.test.ts, packages/flp-config-inquirer/test/prompts/questions/basic.test.ts
Related to https://github.com/SAP/open-ux-tools/issues/2756
To prevent default methods being ran, and answers automatically populated, if the `hide` prompt option is set for a specific prompt it should not be returned from `getPrompts`
This will also enhance performance in YUI so that conditions e.g `when` `default` are not ran everytime
=> fix(flp-inquirer): fix hiding flp prompts

.changeset/shy-oranges-tell.md, packages/preview-middleware/src/base/flp.ts, packages/preview-middleware/test/unit/base/__snapshots__/flp.test.ts.snap, packages/preview-middleware/test/unit/base/flp.test.ts, packages/preview-middleware/test/unit/ui5/middleware.test.ts
The `sap-ui-xx-viewCache=false` URL parameter ensures that changes made during development are reflected in the applications preview. Some projects and scripts are missing this parameter - In that case a reroute will happen and the parameter will be added.
=> feat(preview-middleware): reroute missing url param viewCache

.changeset/rude-lobsters-punch.md, packages/ui5-config/src/ui5config.ts, packages/ui5-config/test/index.test.ts
Replaced deletion logic from `filter` in `removeBackendFromFioriToolsProxydMiddleware` method to `findIndex` and `splice` combination to allow to delete only one backend instance for `fiori-tools-proxy middleware`.
Reason: Possible duplicated backend entries for multiple services from same system and filter deletes all of them.
=> feat: Delete one backend per service

.changeset/early-squids-buy.md, packages/abap-deploy-config-writer/src/constants.ts, packages/abap-deploy-config-writer/src/file.ts, packages/abap-deploy-config-writer/src/index.ts, packages/abap-deploy-config-writer/test/sample/test.ui5.lib/test/ui5/lib/.library, packages/abap-deploy-config-writer/test/sample/test.ui5.typescript.library1/package.json, packages/abap-deploy-config-writer/test/sample/test.ui5.typescript.library1/src/test/ui5/typescript/library1/.library, packages/abap-deploy-config-writer/test/sample/test.ui5.typescript.library1/src/test/ui5/typescript/library1/library.ts, packages/abap-deploy-config-writer/test/sample/test.ui5.typescript.library1/src/test/ui5/typescript/library1/messagebundle.properties, packages/abap-deploy-config-writer/test/sample/test.ui5.typescript.library1/tsconfig.json, packages/abap-deploy-config-writer/test/sample/test.ui5.typescript.library1/ui5.yaml, packages/abap-deploy-config-writer/test/unit/__snapshots__/index.test.ts.snap, packages/abap-deploy-config-writer/test/unit/index.test.ts, packages/ui5-library-sub-generator/test/unit/expected-output/library1/package.json, packages/ui5-library-sub-generator/test/unit/expected-output/tslibrary1/package.json, packages/ui5-library-writer/templates/common/1.120.0/package.json, packages/ui5-library-writer/templates/common/1.71.0/package.json, packages/ui5-library-writer/test/__snapshots__/index.test.ts.snap
#2819 
- Updates `@sap-ux/ui5-library-writer`, adding the scripts to for deploy config
- Updates `@sap-ux/abap-deploy-config-writer`, adding the .Ui5RepositoryIgnore file for typescript libraries
=> tbi(ui5-libs): support for deploying ui5 libs

.changeset/short-knives-clean.md, packages/project-access/src/project/cap.ts, packages/project-access/test/project/cap.test.ts
Accomodate change in `@sap/cds@8.5.0` where services might not have a urlPath or `endpoints property in the serviceinfo 
```
@protocol: 'websocket'
service CatalogService {
entity Books {
key ID : Integer;
title  : String;
stock  : Integer;
}
}
```
now results in:
$  cds c srv -2 serviceinfo
```
[
{
name: 'CatalogService',
destination: 'srv-api',
runtime: 'Node.js',
location: {
file: 'srv/cat-service.cds',
line: 2,
col: 9
}
}
]
```
=> project-access - filter CAP services to only include odata services

.changeset/late-plants-accept.md, packages/project-integrity/src/fiori-project/index.ts, packages/project-integrity/src/index.ts, packages/project-integrity/test/unit/fiori-project/index.test.ts, packages/project-integrity/test/unit/index.test.ts
When using module `@sap-ux/project-integrity`, there is currently no way to check if a Fiori project has enabled integrity check. The only way is with try and error. 
This pull request adds function `isFioriProjectIntegrityInitialized(projectRoot: string): boolean` to check, whether integrity has been enabled for a Fiori project without the need of `try`/`catch`.
=> fix: add check for initialized fiori integrity

.changeset/pretty-rats-change.md, packages/preview-middleware-client/src/cpe/selection.ts
Feat for #2873.
- Calls the `scrollIntoView` method on the dom element of the control.
=> feat: Scroll into view when clicking on a `control` that is not currently visible in the `iframe`

.changeset/cyan-islands-look.md, packages/odata-service-writer/src/index.ts, packages/odata-service-writer/test/unit/index.test.ts, packages/ui5-config/src/ui5config.ts, packages/ui5-config/test/index.test.ts
Issue - https://github.com/SAP/open-ux-tools/issues/2885
`ignoreCertError` is a part of OData service interface and also a part of proxy `middlware.configuration`.
If `ignoreCertError` in middleware differs from the `ignoreCertError` of the service that is being added, `addBackendToFioriToolsProxydMiddleware` will also update the `middlware.configuration.ignoreCertError`.
=> fix: Handling of ignoreCertError property from service in proxy middleware

.github/workflows/pipeline.yml, package.json, packages/playwright/package.json, packages/preview-middleware/playwright.config.ts, pnpm-lock.yaml
This PR
* Bump playwright version
* Adapt Github action to only install Chrome browser - as this is the only browser UI integration tests are running.
=> fix: bump playwright and use chrome as browser

.changeset/spicy-coats-build.md, packages/preview-middleware-client/src/adp/quick-actions/fe-v2/utils.ts, packages/preview-middleware-client/test/unit/adp/quick-actions/fe-v2.test.ts
Enable quick action for v2 for app descriptor changes where manifest pages has array strucure.
=> fix: enable manifest actions for v2 apps with array page structure

.changeset/friendly-colts-play.md, packages/odata-service-inquirer/src/prompts/datasources/sap-system/abap-on-btp/questions.ts, packages/odata-service-inquirer/src/prompts/datasources/sap-system/new-system/questions.ts, packages/odata-service-inquirer/src/prompts/datasources/sap-system/system-selection/prompt-helpers.ts, packages/odata-service-inquirer/src/utils/prompt-state.ts, packages/odata-service-inquirer/test/unit/prompts/sap-system/abap-on-btp/questions.test.ts
https://github.com/SAP/open-ux-tools/issues/2911
- Re-adds the setting of connected system for CF flows, this was lost in a recent update (2.0.0)
- Adds tests to cover
- Ensure the `PromptState.connectedSystem` is reset everytime a new connection is validated to prevent stale data
=> fix(odata-service-inquirer): set connected system CF prompts

.changeset/nine-dancers-greet.md, packages/preview-middleware-client/src/adp/quick-actions/fe-v2/utils.ts, packages/preview-middleware-client/src/adp/quick-actions/fe-v4/utils.ts, packages/preview-middleware-client/src/cpe/changes/service.ts, packages/preview-middleware-client/src/utils/fe-v4.ts, packages/preview-middleware-client/test/unit/adp/quick-actions/fe-v2.test.ts, packages/preview-middleware-client/test/unit/cpe/changes/service.test.ts, packages/preview-middleware-client/test/unit/utils/fe-v4/utils.test.ts, packages/preview-middleware-client/types/sap.suite.ui.generic.template.d.ts
When v2 manifest changes created via quick actions are undone(by undo) they still get written to file system on save(rta save).
=> fix: undo redo issue for v2 manifest changes

.changeset/nervous-tables-shake.md, packages/preview-middleware-client/src/adp/quick-actions/fe-v2/create-table-action.ts, packages/preview-middleware-client/src/messagebundle.properties, packages/preview-middleware-client/test/unit/adp/quick-actions/fe-v2.test.ts
v2 table custom action  "QA" not working when headerToolBar is undefined/null
=> fix: create custom table action v2 app

.changeset/red-mails-carry.md, packages/preview-middleware/src/base/flp.ts, packages/preview-middleware/src/base/index.ts, packages/preview-middleware/src/index.ts, packages/preview-middleware/test/unit/base/flp.test.ts
re-routing currently ignores the namespace from cds-plugin-ui5
Besides that `sanitizeRtaConfig` method is being exposed for usage outside of preview-middleware (e.g. to be used in fiori-tools-preview)
=> fix: re-route issue with cds-plugin-ui5

.changeset/fifty-crabs-film.md, packages/adp-tooling/src/preview/change-handler.ts, packages/adp-tooling/templates/rta/common/grid-tree-custom-column.xml, packages/adp-tooling/test/unit/preview/change-handler.test.ts, packages/preview-middleware-client/src/adp/controllers/AddFragment.controller.ts, packages/preview-middleware-client/test/unit/adp/controllers/AddFragment.controller.test.ts
Fixed bug - Create Custom Column quick action generates incorrect column fragment for Grid and Tree tables
=> fix: Create Custom Column quick action generates incorrect fragment for Grid and Tree table 

.changeset/wild-chicken-perform.md, packages/fe-fpm-writer/src/building-block/types.ts, packages/fe-fpm-writer/templates/building-block/filter-bar/View.xml, packages/fe-fpm-writer/test/unit/__snapshots__/building-block.test.ts.snap, packages/fe-fpm-writer/test/unit/building-block.test.ts
Issue #2952
Added support for missing 'showClearButton', 'showMessages', and 'liveMode' properties in FilterBar building block generation.:
Documentation - https://sapui5.hana.ondemand.com/sdk/#/api/sap.fe.macros.FilterBar%23controlProperties
Generation example:
```
<mvc:View xmlns:core="sap.ui.core" xmlns:mvc="sap.ui.core.mvc" xmlns="sap.m" xmlns:html="http://www.w3.org/1999/xhtml" controllerName="com.test.myApp.ext.main.Main" xmlns:macros="sap.fe.macros">
<Page title="Main">
<content>
<macros:FilterBar id="testFilterBar" search="onSearch" filterChanged="onFilterChanged" liveMode="true" showClearButton="false" showMessages="true"/>
</content>
</Page>
</mvc:View>
```
=> fix: Added support for missing 'showClearButton', 'showMessages', and 'liveMode' properties in FilterBar building block generation.

.changeset/long-panthers-deliver.md, packages/cf-deploy-config-sub-generator/src/app/index.ts, packages/cf-deploy-config-sub-generator/src/app/questions.ts, packages/cf-deploy-config-sub-generator/test/app.test.ts
- found when testing locally in tools-suite
- init should only be called when run standalone
- add tests to cover this change
=> fix(cf-deploy-sub-gen): handle flow when loaded as sub-gen

.changeset/happy-bananas-knock.md, packages/ui5-test-writer/src/fiori-freestyle-opa-writer.ts
Bug fix related to [PR](https://github.com/SAP/open-ux-tools/pull/2928)
- The previous logic for filtering files based on the ui5 template version was not platform-compatible, causing the `webapp/integration` and `webapp/test` folders to not be generated on Windows. 
- This fix replaces hardcoded path separators with platform-specific functions, ensuring consistent behaviour across all platforms.
=> Fix: Path Compatibility for Windows in FF Test Template Generation

.changeset/thick-fishes-invite.md, packages/project-access/src/project/cap.ts, packages/project-access/test/project/cap.test.ts
method 'getCapModelAndServices' not returning 'odata-v4' services.
According to documentation - https://cap.cloud.sap/docs/node.js/cds-serve#trace
```
odata is a shortcut for odata-v4.
```
=> fix: method 'getCapModelAndServices' not returning 'odata-v4' services

.changeset/young-months-develop.md, packages/adp-tooling/templates/rta/ts-controller.ejs
Fix for #2964.
- Refactores `onInit` method to accept a `this` parameter that causes problems during controller extension loading.
=> fix: TypeScript template causes the iframe to break when controller extension is loaded

.changeset/cuddly-rabbits-invent.md, packages/fiori-generator-shared/src/index.ts
Chore: Exported function is using an not-exported interface.
=> chore(fiori-generator-shared): Export type used by exported function

.changeset/pretty-years-know.md, packages/cf-deploy-config-sub-generator/test/cap-app.test.ts
Fix for https://github.com/SAP/open-ux-tools/actions/runs/13628636855/job/38091306473?pr=2981
```
Expected: ObjectContaining {"addCapMtaContinue": true, "mtaId": "capmtaid", "mtaPath": "/output/capmissingmta", "routerType": "managed"}, Anything, Anything
Received: {"addCapMtaContinue": true, "mtaId": "capmtaid", "mtaPath": "\\output\\capmissingmta", "routerType": "managed"}, {"store": {"_events": {"change": [[Function anonymous], [Function anonymous], [Function bound onceWrapper]]}, "_eventsCount": 1, "_maxListeners": 0, Symbol(shapeMode): false, Symbol(kCapture): false}}, {}
```
=> fix(cf-deploy-sub-generator): fix failing windows test

.changeset/beige-days-applaud.md, packages/fiori-annotation-api/package.json, packages/i18n/package.json, packages/preview-middleware-client/jest.config.js, pnpm-lock.yaml
Update `vscode-languageserver-textdocument` to match language server.
This update was causing tests to fail in `preview-middleware-client`, because `vscode-languageserver-textdocument` now includes `exports` field in package.json which is used to determine package entry points. When using `jsdom` environment Jest uses `browser` entry point which defaults to ESM, but that it is not compatible with the current test setup, so we need to override the module import logic. 
https://jest-archive-august-2023.netlify.app/docs/28.x/upgrading-to-jest28/#packagejson-exports
=> chore: update dependencies

.changeset/neat-grapes-design.md, packages/mockserver-config-writer/src/mockserver-config/ui5-mock-yaml.ts, packages/mockserver-config-writer/test/unit/mockserver-config/ui5-mock-yaml.test.ts, packages/odata-service-writer/test/unit/index.test.ts, packages/ui5-config/src/middlewares.ts, packages/ui5-config/src/ui5config.ts, packages/ui5-config/test/__snapshots__/index.test.ts.snap, packages/ui5-config/test/index.test.ts
Adds `webappPath` and `basePath` parameters to resolve service paths during mockserver generation/update.
Fixes cases when custom webapp paths are used.
=> feat: use webappPath for mockserver generation

.changeset/tiny-kids-film.md, packages/fiori-freestyle-writer/src/generateOPATests.ts, packages/fiori-freestyle-writer/src/index.ts, packages/fiori-freestyle-writer/src/translations/fiori-freestyle-writer.i18n.json, packages/fiori-freestyle-writer/test/generateOPATests.test.ts, packages/fiori-freestyle-writer/test/worklist.test.ts
Refactor conditional logic for test generation in FF writer
related to open source [PR](https://github.com/SAP/open-ux-tools/pull/2928)
=> Refactor conditional logic for test generation in FF writer

.changeset/nine-shoes-protect.md, packages/project-integrity/src/integrity/persistence.ts, packages/project-integrity/test/unit/integrity/persistence.test.ts
When using `disableProjectIntegrity()` or `enableProjectIntegrity()` the content of integrity data was written not encoded. 
This pull request fixes this issue.
=> fix(project-integrity): ensure encoded write for project-integrity

.changeset/short-penguins-explain.md, packages/deploy-config-sub-generator/src/app/index.ts, packages/deploy-config-sub-generator/test/app.test.ts, packages/deploy-config-sub-generator/test/fixtures/mta1/app1/ui5.yaml
When the deployment generator is ran standalone, against a project with no existing backend configuration, the generator is throwing an undefined error when trying to read `backendConfig.destination`
=> fix(deploy-gen): fix undefined error when no backend config found

.changeset/strange-otters-sleep.md, packages/deploy-config-sub-generator/src/utils/config.ts, packages/deploy-config-sub-generator/test/app.test.ts
Fix for https://github.com/SAP/open-ux-tools/issues/3010
- ensure the destination passed from another generator is appended to backend config
- add unit tests to cover change
=> fix(deploy-config-sub-generator): append destination to backendconfig

.changeset/itchy-students-retire.md, packages/ui-components/src/components/UISection/UISections.tsx, packages/ui-components/test/unit/components/UISections.test.tsx
Part of #2971
Regression after https://github.com/SAP/open-ux-tools/pull/2979
There was missing check for `undefined`:
```
const size = sizes[i].size ?? 0;
```
In case if previous/original sizes from state are not set yet.
=> fix(ui-components): UISections. Error `Cannot read properties of undefined (reading 'size')` is throws for section on initial rendering 

packages/preview-middleware/playwright.config.ts, packages/preview-middleware/test/integration/preview/preview.spec.ts, packages/preview-middleware/test/integration/utils/constant.ts
Problem:
Timeout was set in config which effects all tests timeout.[More on timeout](https://playwright.dev/docs/test-timeouts). 
If there was any failure, playwright would re-try one more time after waiting `5 min + 30 second` and this caused timeout in pipeline which has only [30 min](https://github.com/SAP/open-ux-tools/blob/main/.github/workflows/pipeline.yml#L15). Playwright report artifacts were not uploaded due to pipeline time out.
Possible solution:
Add time out only in `beforeAll` which affects only before all. [More on this check.](https://playwright.dev/docs/test-timeouts#change-timeout-for-beforeallafterall-hook).
=> fix: set timeout in before all

.changeset/early-ligers-beam.md, packages/ui-components/src/components/UISection/UISections.tsx, packages/ui-components/test/unit/components/UISections.test.tsx
issue/regression after https://github.com/SAP/open-ux-tools/pull/2979
Scenario of issue:
1. Two sections with initial size `[400, available_space]` and with min sizes `minSectionSize={[400, 400]}` and window size `1000px x 600px`;
2.  Make screens size less than 800px in width to trigger full screen toggle - hide one of section;
3. Then make screen wider to toggle non-fullscreen mode back and restore visibility of section back;
Problem - size of restored section is wrong.
=> fix(ui-components): UISections. Issue with window resize hiding section on fullscreen toggle event

.changeset/twelve-colts-rest.md, packages/ui-service-inquirer/src/prompts/configuration/questions.ts, packages/ui-service-inquirer/test/prompts.test.ts
https://github.com/SAP/open-ux-tools/issues/3035
- update condition logic to ensure correct value is passed to getContent request
- update test to cover flow
=> fix(ui-service-inq): ensure correct package value is used for getContent request

.changeset/dirty-needles-sin.md, packages/project-input-validator/package.json, packages/project-input-validator/src/index.ts, packages/project-input-validator/src/translations/project-input-validator.i18n.json, packages/project-input-validator/src/ui5/project-path-validators.ts, packages/project-input-validator/test/project-validators.test.ts, packages/project-input-validator/tsconfig.json, packages/ui5-application-inquirer/src/prompts/prompt-helpers.ts, packages/ui5-application-inquirer/src/prompts/prompts.ts, packages/ui5-application-inquirer/src/prompts/validators.ts, packages/ui5-application-inquirer/test/unit/prompts/prompt-helpers.test.ts, packages/ui5-application-inquirer/test/unit/prompts/prompts.test.ts, packages/ui5-application-inquirer/test/unit/prompts/validators.test.ts, pnpm-lock.yaml
- Move `validateTargetFolder` from `ui5-application-inquirer` to `project-input-validator` for improved reuse
- Updated tests
=> Move validate Target Folder path logic to `project-input-validator`

.changeset/many-ties-impress.md, packages/adp-tooling/src/preview/adp-preview.ts, packages/adp-tooling/src/preview/routes-handler.ts, packages/adp-tooling/test/unit/preview/adp-preview.test.ts
Issue: When Adaptation Editor is started for a project using a re-entrance ticket authentication, there are multiple authentication tabs opened on each interaction with the application.
Fix: Reuse already created service provider instead of creating a new provider on each request.
=> fix: Adaptation Editor opens multiple re-entrance ticket tabs for Cloud systems

.changeset/healthy-tips-wave.md, packages/project-input-validator/src/ui5/project-path-validators.ts, packages/project-input-validator/test/project-validators.test.ts, packages/ui5-application-inquirer/src/prompts/prompts.ts, packages/ui5-application-inquirer/test/unit/prompts/prompts.test.ts
Addressed comments in [PR](https://github.com/SAP/open-ux-tools/pull/3042)
=> Rename `validateTargetFolderForFioriApp` to `validateFioriAppTargetFolder`

.changeset/tasty-islands-nail.md, packages/cf-deploy-config-writer/src/mta-config/index.ts, packages/cf-deploy-config-writer/test/unit/index-cap.test.ts
- when generating mta on windows getting an error;
```
Error: Something went wrong creating mta.yaml!
```
The `cds` binary is not being inherited from the shell.
=> fix(cf-deploy-config-writer): spawn options required for windows

.changeset/wise-feet-warn.md, packages/odata-service-inquirer/src/prompts/connectionValidator.ts, packages/odata-service-inquirer/test/unit/prompts/connectionValidator.test.ts
#3066 
Change only lowers the case of the destination name within the URL and leave the service path as it is. 
Some backends return a 404 for the service path as lower case
=> fix(odata-inq): prevent changing service path casing

.changeset/spicy-kids-develop.md, packages/abap-deploy-config-inquirer/src/prompts/conditions.ts, packages/abap-deploy-config-inquirer/src/prompts/validators.ts, packages/abap-deploy-config-inquirer/src/service-provider-utils/transport-config.ts, packages/abap-deploy-config-inquirer/src/utils.ts, packages/abap-deploy-config-inquirer/test/service-provider-utils/transport-config.test.ts, packages/abap-deploy-config-inquirer/test/utils.test.ts
Current implementation does not initiliase the abap service provider for SCP systems at selection,
but only created if they are needed later in the flow - for packages, and transports
However with the change to validate packages (if they are local or not) coming in regardless if the package is entered manually, it makes sense to start initialising the transport when we do the init for on prem
This prevents multiple browsers opening for BTP systems (for every character entered in package manual) as the service provider will already be in the state
=> fix(abap-inq): init transport config for scp systems

.changeset/curly-dolls-look.md, packages/cf-deploy-config-sub-generator/src/app/index.ts, packages/cf-deploy-config-sub-generator/test/cap-app.test.ts
Fix for https://github.com/SAP/open-ux-tools/issues/3069
- Completion message should be shown to the user if no issues were found
- Should only be shown to the user if loaded as root generator
=> fix(cf-deploy-config-sub-generator): ensure completion message is shown to user

.changeset/clever-ducks-refuse.md, packages/cf-deploy-config-writer/src/mta-config/index.ts, packages/cf-deploy-config-writer/test/unit/index-cap.test.ts
Based on changes in CDS, the following CLI commands are now required when adding an mta to a CAP project;
```
cds init meme && cd meme && npm install && cds add sample && cds add hana && cds add mta && npm update --package-lock-only
```
In order to build the mta.yaml `npm update --package-lock-only` is now required.
=> fix(cf-deploy-config-writer): update the mta post install script

.changeset/hungry-terms-pretend.md, packages/preview-middleware-client/src/adp/controllers/ExtensionPoint.controller.ts
Fix for #3078.
- Changes the order of execution inside the handler to capture the event before calling the base class.
=> fix: Cannot create a Extension Point fragment when clicking create button in the dialog

.changeset/pink-guests-peel.md, packages/preview-middleware-client/src/adp/quick-actions/add-new-subpage-quick-action-base.ts, packages/preview-middleware-client/src/adp/quick-actions/fe-v2/add-new-subpage.ts, packages/preview-middleware-client/src/adp/quick-actions/fe-v4/add-new-subpage.ts, packages/preview-middleware-client/test/unit/adp/quick-actions/fe-v4.test.ts, packages/preview-middleware-client/types/sap.fe.templates.d.ts
Fixed CPE Add Subpage quick action bug. The action is not shown when current page has context path defined in page settings in manifest
=> fix: CPE Add Subpage quick action bug fix in v4 projects

.changeset/spotty-ravens-agree.md, packages/abap-deploy-config-inquirer/src/prompts/validators.ts, packages/abap-deploy-config-inquirer/src/service-provider-utils/abap-service-provider.ts, packages/abap-deploy-config-inquirer/test/prompts/validators.test.ts
Add check that connection has been made for cloud systems before validating package (otherwise validator will run for every character entered, which in turns means a browser window opens for every character opened)
=> fix(abap-inq): check cloud systems are connected before making backend call

.changeset/lemon-lizards-provide.md, packages/cf-deploy-config-writer/src/mta-config/index.ts, packages/cf-deploy-config-writer/test/unit/index-cap.test.ts
Current issue;
when `mta.yaml` is added, CDS expects the following command to be run;
```
npm update --package-lock-only
```
However, we are appending `devDependencies` that are putting the `package.json` and `package-lock.json` out of sync.
This can be replicated;
```
step1. Remove existing mta.yaml
step2. Add mta running `cds add mta`
step3. update the package.json with a new devDep i.e. "@ui5/logger": "^4.0.1"
step4. run the command `npm update --package-lock-only`
step5. build the mta.yaml `npm run build`
Build fails when `npm ci` is run
```
To fix the issue;
```
step1. Remove existing mta.yaml
step2. Add mta running `cds add mta`
step3. update the package.json with a new devDep i.e. "@ui5/fs": "^4.0.1",
step4. run the command …
```
=> fix(cf-deploy-config-writer): append install script

.changeset/smooth-trees-attack.md, packages/cf-deploy-config-writer/src/utils.ts, packages/cf-deploy-config-writer/test/unit/__snapshots__/cap.test.ts.snap, packages/cf-deploy-config-writer/test/unit/cap.test.ts, packages/cf-deploy-config-writer/test/unit/index-cap.test.ts
During the deployment generator flow, the `cds` binary appends a devDep `"@sap/cds-dk": "^8" ` to the package.json, for example;
```
"devDependencies": {
"@cap-js/cds-types": "^0.8.0",
"@cap-js/sqlite": "^1",
"@sap/cds-dk": "^8" 
},
```
However, the `addPackageDevDependency` exposed from `project-access` is not reading the latest modifications, so overwrites the devDep since deployment-generator is appending its own, for exmaple;
```
"devDependencies": {
"@cap-js/cds-types": "^0.8.0",
"@cap-js/sqlite": "^1",
"rimraf": "^5.0.5",
"mbt": "^1.2.29"
},
```
The correct result should include both the CDs, rimraf and mbt depdencies, as shown;
```
"devDependencies": {
"@cap-js/cds-types": "^0.8.0",
"@cap-js/sqlite": "^1",
"@sap/cds-dk": …
```
=> fix(cf-deploy-config-writer): remove fs from addPackageDevDependency

.changeset/tricky-spiders-sniff.md, packages/adp-tooling/src/base/prompt.ts, packages/adp-tooling/src/types.ts, packages/adp-tooling/src/writer/project-utils.ts, packages/adp-tooling/src/writer/writer-config.ts, packages/adp-tooling/test/unit/writer/writer-config.test.ts, packages/generator-adp/src/app/index.ts, packages/generator-adp/src/utils/deps.ts, packages/generator-adp/test/__snapshots__/app.test.ts.snap, packages/generator-adp/test/app.test.ts, packages/generator-adp/test/unit/utils/deps.test.ts
Fix for #3015.
- Fixes the mocking of package.json retrieval and the snapshot having dynamic value instead of mocked.
=> fix: ADP Generator integration test mocking

.changeset/seven-plants-grin.md, packages/odata-service-inquirer/src/utils/index.ts, packages/odata-service-inquirer/test/unit/utils/utils.test.ts
Fixes reference to `serviceProvider.services` and optionally chains in case of undefined in function `removeCircularFromServiceProvider `
=> fix(odata-service-inquirer): `removeCircularFromServiceProvider` undefined ref

.changeset/stale-ghosts-matter.md, packages/repo-app-download-sub-generator/test/utils/download-utils.test.ts
- Fixing failing test in windows for `repo-app-download-sub-generator`
=> Fixing failing test in windows for `repo-app-download-sub-generator`

.changeset/eleven-coats-teach.md, packages/cf-deploy-config-inquirer/src/prompts/prompts.ts, packages/cf-deploy-config-inquirer/test/prompts.test.ts, packages/cf-deploy-config-sub-generator/src/app/index.ts, packages/cf-deploy-config-sub-generator/src/app/questions.ts, packages/cf-deploy-config-sub-generator/test/app.test.ts, packages/deploy-config-sub-generator/test/app/app.test.ts
Fix for https://github.com/SAP/open-ux-tools/issues/3022
- text label using incorrect property
- options passed to subgenerator not being used
- pass logger to cf-inquirer
=> fix(cf-deploy-config-sub-generator): issues found when testing

.changeset/witty-suns-whisper.md, packages/cds-odata-annotation-converter/src/printer/csdl-to-cds.ts, packages/cds-odata-annotation-converter/test/printer/__snapshots__/csdl-to-cds.test.ts.snap, packages/cds-odata-annotation-converter/test/printer/csdl-to-cds.test.ts, packages/fiori-annotation-api/test/unit/__snapshots__/fiori-service.test.ts.snap, packages/fiori-annotation-api/test/unit/fiori-service.test.ts
Fixes writing empty path values in CDS files.
CDS does not support empty paths, so we need to use empty string values which later gets translated into empty path value by the compiler.
=> fix(fiori-annotation-api): empty path values

.changeset/real-emus-reply.md, packages/ui-components/src/components/UIFlexibleTable/UIFlexibleTable.scss
Fixes space between empty table and add button.
Occurs when `noDataText` is undefined and `rows` length is 0. 
From:
To:
=> fix: Space between empty table and add button

.changeset/friendly-countries-applaud.md, packages/repo-app-import-sub-generator/src/app/app-config.ts, packages/repo-app-import-sub-generator/test/app-config.test.ts
Related to https://github.com/SAP/open-ux-tools/pull/3110
- Add logic to handle local UI5 version to ensure the downloaded app from ADT, works in local preview mode
- added test case
=> fix to enable local preview for adt downloaded app

.changeset/rich-years-matter.md, packages/cf-deploy-config-writer/src/cf-writer/app-config.ts, packages/cf-deploy-config-writer/src/mta-config/mta.ts, packages/cf-deploy-config-writer/test/sample/appfrontendbase/lrop/package.json, packages/cf-deploy-config-writer/test/sample/appfrontendbase/lrop/ui5.yaml, packages/cf-deploy-config-writer/test/sample/appfrontendbase/lrop/webapp/manifest.json, packages/cf-deploy-config-writer/test/sample/appfrontendbase/mta.yaml, packages/cf-deploy-config-writer/test/sample/appfrontendbase/xs-security.json, packages/cf-deploy-config-writer/test/unit/__snapshots__/index-appfront.test.ts.snap, packages/cf-deploy-config-writer/test/unit/index-appfront.test.ts
Fix for https://github.com/SAP/open-ux-tools/issues/3022
- issue found was related the ` name: appfrontend-app-content` being duplicated
- when an existing App Frontend project exists and you append a HTML5 app to the project the existing app frontend router should be udpated
- added tests to cover change
- complexity has increased by 1 but there is another PR coming with cleanups that will address this
=> fix(cf-deploy-config-writer): handle duplicate app frontend services

.changeset/spicy-cups-agree.md, packages/launch-config/src/index.ts, packages/repo-app-import-sub-generator/src/app/index.ts
Export `handleWorkspaceConfig` from launch-config and reuse in ADT App download sub-generator
=> Refactor: Reuse handleWorkspaceConfig in ADT App Download

.changeset/tame-frogs-remain.md, packages/repo-app-import-sub-generator/src/prompts/prompts.ts, packages/repo-app-import-sub-generator/test/prompts/prompts.test.ts
This PR addresses a crash in the generator occurring when invalid destinations are encountered in BAS.
=> Repo App Import Invalid dest Fix

.changeset/grumpy-olives-relate.md, packages/fe-fpm-writer/src/page/object.ts, packages/fe-fpm-writer/test/unit/page/__snapshots__/object.test.ts.snap, packages/fe-fpm-writer/test/unit/page/object.test.ts
Issue #3170
Scenario:
1. Use `manifest.json` with routing like:
```
"routing": {
"config": {
"flexibleColumnLayout": {
"defaultTwoColumnLayoutType": "TwoColumnsBeginExpanded",
"defaultThreeColumnLayoutType": "ThreeColumnsMidExpanded"
},
"routerClass": "sap.f.routing.Router"
},
"routes": [
{
"pattern": ":?query:",
"name": "TripsList",
"target": [
"TripsList"
]
},
{
"name": "TripsObjectPage",
"pattern": "Trips({TripsKey}):?query:",
"target": [
"TripsList",
"TripsObjectPage"
]
}
],
"targets": {
"TripsList": {
"type": "Component",
"id": "TripsList",
"name": "sap.fe.templates.ListReport",
"options": {
"settings": {
"contextPath": "/Trips",
"variantManagement": "Page",
"initialLoad": "Enabled",
"navigation": {
"Trips": {
"detail": {
"route": "TripsObjectPage"
}
}
}
}
},
"controlAggregation": …
```
=> fix: correct control aggregation for object page when fcl is enabled

.changeset/nine-cows-tell.md, packages/fiori-app-sub-generator/src/fiori-app-generator/fioriAppGenerator.ts, packages/fiori-app-sub-generator/test/unit/fiori-app-generator/fioriAppGenerator-lifecycle2.test.ts
If enable typescript prompt is answered as true, it is required that the CAP project will be updated to use NPM workspaces
=> fix(fiori-sub-gen): check enable typescript answer to determine use of npm workspaces

.changeset/old-timers-greet.md, .changeset/quiet-dolphins-shop.md, packages/fiori-annotation-api/jest.setup.js, packages/fiori-annotation-api/src/xml/adapter.ts, packages/fiori-annotation-api/test/unit/__snapshots__/fiori-service.test.ts.snap, packages/fiori-annotation-api/test/unit/fiori-service.test.ts, packages/fiori-annotation-api/test/unit/raw-metadata-serializer.ts, packages/odata-annotation-core/src/paths/normalization.ts, packages/odata-annotation-core/test/paths/normalization.test.ts
UI5 runtime also works with annotations files without references to the metadata, so we should not prevent tools from working in such cases either. We should still report this as warning since it does not conform with the OData spec, but currently we can only throw errors.
=> feat(fiori-annotation-api): relax metadata reference check

.changeset/loud-beers-know.md, packages/abap-deploy-config-inquirer/src/utils.ts, packages/abap-deploy-config-inquirer/test/utils.test.ts
#3194 
- Replace `??` with logical OR `||` for correct behaviour (thx Sonar 😞  )
- Update test to replicate real world scenario where the bug occurred
=> fix(abap-deploy-config-inquirer): Re-auth should not be required

.changeset/light-dryers-jump.md, packages/odata-service-writer/src/data/annotations.ts, packages/odata-service-writer/src/data/manifest.ts, packages/odata-service-writer/test/__snapshots__/index.test.ts.snap, packages/odata-service-writer/test/test-data/manifest-json/edmx-manifest-multiple-annotations.ts, packages/odata-service-writer/test/test-data/manifest-json/edmx-manifest-multiple-services.ts
We noticed that service annotation files are written with sub folder like:
after correction it looks following:
=> fix(odata-service-writer): Write service annotations using `name` instead of `technicalName` to avoid sub folders

.changeset/wise-kids-unite.md, packages/cf-deploy-config-sub-generator/test/fixtures/sap-ux-test/package.json, packages/cf-deploy-config-writer/src/mta-config/mta.ts, packages/cf-deploy-config-writer/src/utils.ts, packages/cf-deploy-config-writer/templates/package.json, packages/cf-deploy-config-writer/test/unit/__snapshots__/index-app.test.ts.snap, packages/cf-deploy-config-writer/test/unit/__snapshots__/index-appfront.test.ts.snap, packages/cf-deploy-config-writer/test/unit/__snapshots__/index-base.test.ts.snap
Fix for https://github.com/SAP/open-ux-tools/issues/3097
Ensure the `package.json` created references the mta ID used to generate the mta configuration, these are normally aligned. 
Note, this is part of cleanup job and its a rare situation to have a HTML5 app without a package.json
- updated snapshots
- updated jsdoc
- updated template
=> fix(cf-deploy-config-writer): ensure package.json is created using mta ID

.changeset/weak-planets-mix.md, packages/ui5-application-inquirer/src/prompts/prompts1.ts, packages/ui5-application-inquirer/test/unit/prompts/prompts.test.ts
- there was a bug when a project has the CdsUi5Plugin installed and hasMinCdsVersion but was not getting the option for Typescript
- update typescript prompt condition to show prompt when only hasMinCdsVersion is true
- current logic was hiding the prompt when the CdsUi5Plugin was installed but workspaces were not enabled. User should be given the option to select Typescript here as they have the plugin and we enable workspaces at generation.
- Warning is still shown to state we enable workspaces when Typescript is selected, if workspaces are not already enabled.
- Tests mostly cover the flow already, added an explicit test for `when` if only `hasMinCdsVersion ` is true (the flow for the bug)
=> fix(ui5-app-inquirer): fix 'when' condition for Typescript prompt

.changeset/fresh-boxes-kneel.md, packages/preview-middleware-client/src/adp/controllers/AddTableColumnFragments.controller.ts, packages/preview-middleware-client/src/utils/additional-change-info.ts, packages/preview-middleware-client/test/__mock__/sap/ui/fl/Change.ts, packages/preview-middleware-client/test/unit/adp/controllers/AddTableColumnFragments.controller.test.ts, packages/preview-middleware-client/test/unit/utils/additional-change-info.test.ts
Fix regression introduced by #3091.
Move `templateName` data to the new data transfer mechanism also for adding table column dialog.
We can't use plugin, because it only creates one fragment, but we need to create two at the same time.
=> fix(preview-middleware): new column is not visible after using `Add Custom Table Column` Quick Action

.changeset/tricky-turkeys-smile.md, packages/odata-service-inquirer/src/prompts/datasources/service-url/validators.ts, packages/odata-service-inquirer/test/unit/prompts/service-url/validators.test.ts
Follow-up to fix for: https://github.com/SAP/open-ux-tools/issues/3228
- Add `ignoreCertError` property to prompt state in case if this is referenced by a caller instead of using `prompt()` function which returns the answers object including all prompt answers
- Updates test
=> fix(odata-service-inquirer): Set `ignoreCertError` to PromptState

.changeset/short-snakes-exist.md, packages/ui5-application-inquirer/src/prompts/prompts1.ts, packages/ui5-application-inquirer/test/unit/prompts/prompts.test.ts
https://github.com/SAP/open-ux-tools/issues/3230
- remove workspace warning for non cap projects/data sources
- add additional tests
=> fix(ui5-app-inquirer): remove typescript workspace warning for non cap

.changeset/lazy-colts-shave.md, packages/odata-service-inquirer/src/prompts/datasources/sap-system/service-selection/questions.ts, packages/odata-service-inquirer/src/prompts/datasources/sap-system/service-selection/service-helper.ts, packages/odata-service-inquirer/src/types.ts, packages/odata-service-inquirer/test/unit/prompts/sap-system/service-selection/questions.test.ts
- In some cases, the list of services returned from the catalog may require filtering, the new property `serviceFilter` on `ServiceSelectionPromptOptions` will facilitate the filtering of services returned from the catalog, based on the service ID.
=> feat(odata-inq): service filter prompt option

.changeset/quick-jokes-arrive.md, packages/ui5-application-inquirer/src/prompts/prompt-helpers.ts, packages/ui5-application-inquirer/test/unit/prompts/prompt-helpers.test.ts
When `promptOpt?.hide` is a function, the condition `!promptOpt?.hide` is returning false 
Correcting the condition to either check if it's a function or boolean value and assign it once
=> fix(ui5-app-inq): correct hide fn logic

.changeset/seven-rice-heal.md, packages/preview-middleware/src/base/flp.ts, packages/preview-middleware/test/unit/base/__snapshots__/flp.test.ts.snap, packages/preview-middleware/test/unit/base/flp.test.ts
Currently the virtual card generator endpoint does not work in case the preview uses a (non virtual) local flp html file. This is fixed in this PR.
=> Fix/preview middleware/cards generator with static flp html

.changeset/smart-onions-mate.md, packages/fiori-annotation-api/src/cds/adapter.ts, packages/fiori-annotation-api/test/unit/__snapshots__/fiori-service.test.ts.snap, packages/fiori-annotation-api/test/unit/fiori-service.test.ts
Correctly replace `/` with `.` for CDS paths when they are used for text replacement, because there conversion logic from `@sap-ux/cds-odata-annotation-converter` is not called.
=> fix(fiori-annotation-api): replace text content for cds paths

.changeset/two-mirrors-travel.md, packages/odata-service-writer/src/index.ts, packages/odata-service-writer/src/update.ts, packages/odata-service-writer/test/unit/index.test.ts
Adds option to only update annotation and metadata XML files (service refresh) without any changes to the YAML files.
=> feat: Option to only update annotation and metadata files

.changeset/stale-carrots-think.md, packages/axios-extension/src/abap/abap-service-provider.ts, packages/axios-extension/src/abap/adt-catalog/generators/ui-service-generator.ts, packages/ui-service-sub-generator/src/app/utils.ts
https://github.com/SAP/open-ux-tools/issues/3291
- hardcoded content type is no longer valid and has changed
- use content type from generator config retrieved in generator flow
=> fix(ui-service-generator): use accept header for content request from generator config

.changeset/beige-dogs-rush.md, packages/preview-middleware/src/base/flex.ts
After restricting what files are processed as changes in #3301 variant changes were excluded and were no longer shown in Adaptation Editor.
=> fix(preview-middleware): missing variant changes

.changeset/thirty-balloons-pay.md, packages/abap-deploy-config-sub-generator/src/app/index.ts, packages/cf-deploy-config-sub-generator/src/app/index.ts
Yeoman environment property `conflicter.force` is still required when running deploy config standalone
=> fix(deploy-gens): re-add conflicter.force prop for yui standalone

.changeset/new-sloths-develop.md, packages/axios-extension/src/abap/lrep-service.ts, packages/axios-extension/test/abap/lrep-service.test.ts
Fix for: #3238
* Disable internally the encoding of url parameters set in the `get system info` api call.
* Make a small refactoring - in the `merge app descriptor variant` api call we also disable the encoding.
Testing done:
* Add unit tests.
* Manually verified.
=> fix(axios): Disable System info params encoding

.changeset/funny-owls-protect.md, packages/preview-middleware-client/src/flp/init.ts, packages/preview-middleware-client/src/flp/initCdm.ts, packages/preview-middleware-client/test/unit/flp/__snapshots__/init.test.ts.snap, packages/preview-middleware-client/test/unit/flp/init.test.ts, packages/preview-middleware-client/test/unit/flp/initCdm.test.ts
The latest ushell changes break enhanced homepage loading when using UI5 version 1.137 and above. This fix ensures custom CDN-related ushell configuration is provided before the container is required, following ushell team recommendations.
- Addresses breaking changes introduced in recent ushell updates
- Maintains compatibility with UI5 1.137+ versions
- Implements ushell-recommended configuration order
=> fix(preview-middleware): enhancedhomepage loading issues from UI5 v1.137

.changeset/spicy-icons-type.md, packages/abap-deploy-config-inquirer/src/prompts/validators.ts, packages/abap-deploy-config-inquirer/src/service-provider-utils/transport-config.ts, packages/abap-deploy-config-inquirer/test/prompts/validators.test.ts, packages/abap-deploy-config-inquirer/test/service-provider-utils/transport-config.test.ts, packages/adp-flp-config-sub-generator/src/app/index.ts, packages/cf-deploy-config-inquirer/src/prompts/app-router-prompts.ts, packages/deploy-tooling/src/base/deploy.ts, packages/inquirer-common/src/error-handler/error-handler.ts, packages/odata-service-inquirer/src/prompts/prompt-helpers.ts
https://github.com/SAP/open-ux-tools/issues/3264
- Replace the generic cert error types with the actual error so the specific texts can be generated
- Updates tests
- Update `inquirer-common` `ErrorHandler` log prefix to be configurable
- Updates all instances of `new ErrorHandler` where a logger is not provided, to use the consumer module name as prefix
=> fix: abap-deploy-config-inquirer - Use more specific GA link texts for cert errors.

.changeset/hot-cows-provide.md, packages/app-config-writer/src/common/ui5-yaml.ts, packages/app-config-writer/test/unit/preview-config/ui5-yaml.test.ts
Currently there's a devDependency to preview-middleware in app-config-writer but actually it is needed at runtime. This PR fixes the dependency.
=> fix(app-config-writer): preview middleware dependency

.changeset/early-boxes-vanish.md, packages/ui-components/src/components/UIDialog/UIDialog.tsx, packages/ui-components/test/unit/components/UIDialog.test.tsx
Problem - overlay background for dialogs used buildin color from fluentui instead of vscode theme variable.
Appllied corrected version proposed by Goran:
```
background: 'var(--vscode-editor-background)',
opacity: 0.8
```
Light theme:
Dark theme:
=> fix(ui-components): UIDialog: Override FluentUI overlay background with VSCode theme variable

.changeset/three-ladybugs-boil.md, packages/odata-service-inquirer/src/prompts/connectionValidator.ts, packages/odata-service-inquirer/src/prompts/datasources/sap-system/credentials/questions.ts, packages/odata-service-inquirer/test/unit/prompts/sap-system/new-system/questions.test.ts
- When a validate connection is made for on prem (basic auth) - we need to assign the userdisplay name. Same is done for BTP systems https://github.com/SAP/open-ux-tools/blob/3c63deb8df253bfc9b607727e4361daa53cfe75a/packages/odata-service-inquirer/src/prompts/connectionValidator.ts#L673
- Also updates the `userDisplayName` this when system credentials are updated for an existing system
=> fix(odata-inquirer): ensure user display name is assigned to backend system

.changeset/slow-wasps-hope.md, .changeset/tiny-cougars-return.md, packages/abap-deploy-config-inquirer/src/prompts/questions/confirm.ts, packages/abap-deploy-config-inquirer/src/types.ts, packages/abap-deploy-config-inquirer/test/prompts/questions/confirm.test.ts, packages/abap-deploy-config-sub-generator/src/app/questions.ts, packages/abap-deploy-config-sub-generator/test/app.test.ts, packages/abap-deploy-config-sub-generator/test/unit/app/questions.test.ts, packages/cf-deploy-config-inquirer/src/prompts/prompts.ts, packages/cf-deploy-config-inquirer/src/types.ts, packages/cf-deploy-config-inquirer/test/index.test.ts, packages/cf-deploy-config-inquirer/test/prompts.test.ts, packages/cf-deploy-config-sub-generator/src/app/questions.ts, packages/deploy-config-sub-generator/test/app/app.test.ts
Internal high bug 35240
Reverts change made here https://github.com/SAP/open-ux-tools/pull/3444/files#diff-24301133b22fc485c7fb65d11b3e76c2150400123d73802940fe378e8b378ebdR13
`overwrite` prompt causing conflict as there is an existing prompt in ABAP deploy config inquirer with same name
Added a note to help prevent such case in the future
=> fix(deploy-config): fix conflict of overwrite prompt name

.changeset/smooth-bobcats-watch.md, packages/inquirer-common/package.json, packages/inquirer-common/src/prompts/helpers.ts, packages/inquirer-common/src/translations/inquirer-common.i18n.json, packages/inquirer-common/test/unit/prompts/fixtures/metadataV4WithAggregateTransforms.xml, packages/inquirer-common/test/unit/prompts/helpers.test.ts, packages/odata-service-inquirer/src/prompts/edmx/entity-helper.ts, packages/odata-service-inquirer/src/prompts/edmx/questions.ts, pnpm-lock.yaml
internal s4 issue 449
- move entity helpers for filtering aggregation based entities to inquirer common to enable re use by other modules
- moved `getDefaultTableType` from questions.ts to entityHelper.ts as it makes more sense to be there
- no change to functions/logic
- added tests in inq-common for moved helpers
=> feat(odata-service-inq): move entity helpers to inq-common

packages/ui-prompting/.storybook/addons/preview.tsx, packages/ui-prompting/.storybook/addons/register.ts
Issue to fix sonar issue:
Solution - use component name approach:
No changelog - it does not affect release code, only related to storybook examples(storybook addon to see answers preview)
=> fix: sonar issue for prompting storybook examples

.changeset/strong-adults-mix.md, packages/ui-prompting/src/components/Inputs/Select/Select.tsx, packages/ui-prompting/src/types.ts, packages/ui-prompting/stories/List.story.tsx, packages/ui-prompting/test/unit/components/Inputs/Select.test.tsx
Currently in questions we set default value like -> https://github.com/SAP/open-ux-tools/blob/main/packages/fe-fpm-writer/src/building-block/prompts/questions/table.ts#L83
where default is actual value.
Request was that we should allow to pass index based value for `list` type question, like:
```
return {
type: 'list',
name: 'aggregationPath',
defaultIndex: 1,
choices: project
}
```
=> feat(ui-prompting): Support index-based default values for 'list' type questions.

.changeset/tricky-ways-beam.md, packages/annotation-generator/jest.setup.js, packages/annotation-generator/src/generation.ts, packages/annotation-generator/test/data/cds-incidents/.gitignore, packages/annotation-generator/test/data/cds-incidents/app/project1/annotations.cds, packages/annotation-generator/test/data/cds-incidents/app/project1/package.json, packages/annotation-generator/test/data/cds-incidents/app/project1/ui5.yaml, packages/annotation-generator/test/data/cds-incidents/app/project1/webapp/i18n/i18n.properties, packages/annotation-generator/test/data/cds-incidents/app/project1/webapp/manifest.json, packages/annotation-generator/test/data/cds-incidents/app/services.cds, packages/annotation-generator/test/data/cds-incidents/db/schema.cds, packages/annotation-generator/test/data/cds-incidents/package.json, packages/annotation-generator/test/data/cds-incidents/srv/services.cds, packages/annotation-generator/test/unit/__snapshots__/cds-generation.test.ts.snap, packages/annotation-generator/test/unit/cds-generation.test.ts
There was a type mismatch to what `targetType` of a navigation property was resolved to by `@sap-ux/annotation-converter`. It was returning empty object instead of `EntityType`.
=> fix(annotation-generator): annotations are not generated if navigation property can't be resolved

.changeset/tiny-eels-invent.md, packages/adp-tooling/src/types.ts, packages/adp-tooling/src/writer/index.ts, packages/generator-adp/package.json, packages/generator-adp/src/add-annotations-to-odata/index.ts, packages/generator-adp/src/app/index.ts, packages/generator-adp/src/utils/subgenHelpers.ts, packages/generator-adp/src/utils/templates.ts, packages/generator-adp/test/unit/add-annotations-to-odata/index.test.ts, packages/generator-adp/test/unit/utils/subgenHelpers.test.ts, packages/generator-adp/test/unit/utils/templates.test.ts, packages/generator-adp/tsconfig.json, pnpm-lock.yaml
Fix for #3547.
- Changes the composeWith call namespace of `@sap-ux/adp-flp-config-sub-generator` to the bundled `@sap/fiori:adp-flp-config`.
- Fixes the template problem when ADP generator is bundled inside of `@sap/generator-fiori`.
=> fix: ADP Generator templates / sub-generator resolution

.changeset/angry-panthers-wash.md, packages/abap-deploy-config-inquirer/src/prompts/questions/auth.ts, packages/abap-deploy-config-inquirer/src/prompts/validators.ts, packages/abap-deploy-config-inquirer/test/prompts/validators.test.ts, packages/adp-tooling/src/base/constants/index.ts
Fix for #3562.
- Enhances the password prompt validation (when in BAS and a flag is passed) to update the isS4HC prompt state. This state update makes the cloud-specific prompts visible.
Also, includes this fix:
- Temporarily hide application variants from the application list. Due to an issue in the App Index API, application variants are listed as available for the Adaptation Project. This will cause issues if users select such an application variant.
=> fix: Deploy Config generator does not show cloud-specific prompts for ADP when login is required

packages/fiori-mcp-server/package.json, packages/fiori-mcp-server/test/unit/server.test.ts
Skip test that is using a hard coder version number
- each patch version will change the version and this may come from other modules direct and indirect
=> fix(test): version used in test cannot be hardcoded

packages/fiori-mcp-server/src/tools/functionalities/controller-extension/index.ts, packages/fiori-mcp-server/src/tools/functionalities/functionalities.ts, packages/fiori-mcp-server/src/tools/functionalities/generate-fiori-ui-app/generate-fiori-ui-app.ts, packages/fiori-mcp-server/src/tools/functionalities/page/add-page.ts, packages/fiori-mcp-server/src/tools/functionalities/page/application.ts, packages/fiori-mcp-server/src/tools/functionalities/page/delete-page.ts, packages/fiori-mcp-server/src/tools/get-functionality-details.ts, packages/fiori-mcp-server/src/tools/index.ts, packages/fiori-mcp-server/src/tools/list-functionalities.ts, packages/fiori-mcp-server/src/tools/output-schema/get-functionality-details.json, packages/fiori-mcp-server/src/tools/output-schema/list-functionality.json, packages/fiori-mcp-server/src/types.ts, packages/fiori-mcp-server/test/unit/server.test.ts, packages/fiori-mcp-server/test/unit/tools/__snapshots__/list-functionalities.test.ts.snap, packages/fiori-mcp-server/test/unit/tools/functionalities/controller-extension/index.test.ts, packages/fiori-mcp-server/test/unit/tools/functionalities/generate-fiori-ui-app/generate-fiori-ui-app.test.ts, packages/fiori-mcp-server/test/unit/tools/functionalities/page/__snapshots__/index.test.ts.snap, packages/fiori-mcp-server/test/unit/tools/functionalities/page/index.test.ts, packages/fiori-mcp-server/test/unit/tools/get-functionality-details.test.ts, packages/fiori-mcp-server/test/unit/tools/list-functionalities.test.ts
We noticed that sometimes tools are called with functionality id. As enhancement - we can be more precise and rename property `id` to `functionalityId` for tool `list-functionality` and `get-functionality-details`.
=> feat: rename property `id` to `functionalityId`

packages/fiori-mcp-server/src/tools/list-fiori-apps.ts, packages/fiori-mcp-server/src/tools/output-schema/list-fiori-apps.json, packages/fiori-mcp-server/src/types.ts, packages/fiori-mcp-server/test/unit/server.test.ts, packages/fiori-mcp-server/test/unit/tools/list-fiori-apps.test.ts
enhance output of `list-fiori-apps` tool:
1. Rename `path` -> `appPath` -> in all tools inputs `appPath` name is used;
2. Add `projectPath` property
3. Delete `type` property
4. Add `projectType` property - return if it is CAP or EDMX project
5. rename `version` to `oDataVersion`
6. update output schema based on changes for `list-fiori-apps` output intefrace
=> feat(mcp-server): enhance list fiori apps tool

.changeset/flat-suits-allow.md, packages/serve-static-middleware/README.md, packages/serve-static-middleware/src/base/servestatic.ts, packages/serve-static-middleware/src/base/types.ts, packages/serve-static-middleware/test/ui5/middleware.test.ts
Add a new config option `keepCacheBusterInUrl` to the serve-static-middleware to revert the new default that ignores the cache buster part of the URL.
=> feat(serve-static-middleware): make servestatic ignore cachebuster in URLs

.changeset/large-tips-hang.md, packages/abap-deploy-config-inquirer/src/prompts/questions/abap-target.ts, packages/abap-deploy-config-inquirer/src/translations/abap-deploy-config-inquirer.i18n.json, packages/abap-deploy-config-inquirer/test/prompts/questions/abap-target.test.ts
Related to internal issue 35496
Adjust the message indicating to the user, the host being referenced is a virtual host and shouldn't prevent them from continuing on with the wizard.
=> fix(abap-deploy-config-inquirer): adjust deployment message

.changeset/itchy-crabs-bake.md, packages/abap-deploy-config-inquirer/src/prompts/validators.ts, packages/abap-deploy-config-inquirer/test/prompts/validators.test.ts, packages/adp-tooling/src/base/constants/index.ts
Fix for #3594.
- Adds a check when the package has two project types. Then, we allow the user to continue with deployment.
Also,
- Removes this temporary fix, hiding application variants from the application list. Due to an issue in the App Index API (which is now fixed), application variants are listed as available for the Adaptation Project. This will cause issues if users select such an application variant.
=> fix: Deploy Config generator does not allow package with CloudReady and OnPremise project types

.changeset/seven-dolphins-teach.md, packages/fiori-mcp-server/CHANGELOG.md, packages/fiori-mcp-server/README.md, packages/fiori-mcp-server/src/server.ts, packages/fiori-mcp-server/src/tools/index.ts, packages/fiori-mcp-server/src/types/basic.ts, packages/fiori-mcp-server/src/types/input.ts, packages/fiori-mcp-server/src/types/output.ts, packages/fiori-mcp-server/test/unit/server.test.ts, packages/fiori-mcp-server/test/unit/tools/__snapshots__/index.test.ts.snap, packages/fiori-mcp-server/test/unit/tools/index.test.ts
Update MCP to use snake case instead of kebab case in MCP tool names. Rename `doc_search` to `search_docs`.
=> MCP - more consistent tool names

.changeset/hip-wasps-impress.md, packages/abap-deploy-config-inquirer/src/prompts/questions/config/transport.ts, packages/abap-deploy-config-inquirer/test/prompts/questions/config/transport.test.ts, packages/ui-service-inquirer/test/__snapshots__/prompts.test.ts.snap
Related to the internal issue 33258.
Show an asterisk next to the Transport Request (mandatory) input.
=> fix(abap deploy config inquirer): 33258 asterisk for transport request

.changeset/hungry-ducks-begin.md, packages/abap-deploy-config-sub-generator/src/app/index.ts, packages/abap-deploy-config-sub-generator/src/utils/project.ts, packages/abap-deploy-config-sub-generator/test/unit/utils/project.test.ts
Fix for #3616.
- Adds a check to determine whether we are running as a sub-generator or part of the ADP generator and read from disk or from mem-fs, respectively.
=> fix: "lrep" property is not added when the deploy config is created from within the ADP Generator

.changeset/wicked-plums-check.md, packages/adp-flp-config-sub-generator/src/app/index.ts, packages/adp-flp-config-sub-generator/src/app/types.ts, packages/adp-flp-config-sub-generator/src/utils/appWizardCache.ts, packages/adp-flp-config-sub-generator/test/app.test.ts, packages/adp-flp-config-sub-generator/test/utils/appWizardCache.test.ts
#3692
* Introduces an additional property persisted in AppWizard cache that indicates if credential prompts were already shown. If the property is set to `true` the credential prompts are added as a step in Yeoman UI to prevent issues with the navigation.
=> fix: Wrong navigation between steps in FLP Configuration generator for ADP

.changeset/gold-boxes-kick.md, packages/abap-deploy-config-sub-generator/src/app/index.ts, packages/abap-deploy-config-writer/src/file.ts, packages/abap-deploy-config-writer/src/index.ts, packages/abap-deploy-config-writer/src/scripts.ts, packages/abap-deploy-config-writer/src/types.ts, packages/abap-deploy-config-writer/test/unit/__snapshots__/index.test.ts.snap, packages/abap-deploy-config-writer/test/unit/file.test.ts, packages/abap-deploy-config-writer/test/unit/index.test.ts, packages/create/src/cli/add/deploy-config.ts
Fix for #3634.
- Adds `build` script for all projects, like it was before.
- Removes `build` script from `undeploy` script from ADP projects only.
=> fix: Missing build script for ADP onPremise projects leads to error during deployment

.changeset/tall-rats-poke.md, packages/fiori-mcp-server/src/tools/services/text-embedding.ts
fix "Error [ERR_REQUIRE_ESM]" when starting fiori mcp server e.g. Nodejs 22.8.0
=> fix mcp server start-up
