SAP/open-ux-tools

packages/common/src/package/utils.ts, packages/fiori-freestyle/src/index.ts, packages/fiori-freestyle/test/__snapshots__/basic.test.ts.snap, packages/odata-service/src/index.ts, packages/ui5-application/src/data/defaults.ts, packages/ui5-application/src/index.ts
Updates to not output mock updates where no metadata is provided
=> fix(FF): Updates FF to not generate mock outputs when no metadata provided

package.json, packages/common/package.json, packages/fiori-freestyle/package.json, packages/odata-service/package.json, packages/types/package.json, packages/ui5-application/package.json, packages/ui5-config/package.json, packages/yaml/package.json
* Update versions of all modules to `v0.9.0`
=> chore: update versions of all modules to v0.9.0

packages/odata-service-writer/src/data/defaults.ts, packages/odata-service-writer/test/unit/index.test.ts, packages/types/src/odataService.ts, packages/ui5-config/src/middlewares.ts
=> fix(odata-service): handle undefined service url path

.changeset/tender-kangaroos-give.md, packages/fiori-freestyle-writer/templates/worklist/extend/webapp/i18n/i18n.properties, packages/fiori-freestyle-writer/test/__snapshots__/index.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/worklist.test.ts.snap, packages/fiori-freestyle-writer/test/worklist.test.ts
Fixes: https://github.com/SAP/open-ux-tools/issues/168
Add missing condition to i18n template, update test to cover
=> fix(fiori-freestyle-writer): Add condition to i18n template, modify test

README.md
* Update the main `README` file to add a pipeline status badge as a quick indicator of the build status.
=> chore: update readme with pipeline status badge

README.md, docs/CODE_OF_CONDUCT.md
Fixing #189 by adding missing sections:
- code of conduct pointing to a code of conduct document
- requirements
- contributing pointing to our dev guidelines
=> Add sections required by SAP

.changeset/forty-starfishes-punch.md, packages/ui5-config/src/index.ts, packages/ui5-config/src/middlewares.ts, packages/ui5-config/src/types.ts, packages/ui5-config/src/ui5-config.ts, packages/ui5-config/test/__snapshots__/index.test.ts.snap, packages/ui5-config/test/index.test.ts, packages/yaml/src/yaml-document.ts, packages/yaml/test/yaml-document.test.ts
Proposal to enhance the `ui5-config` module to allow adding the `abap-deploy-task` required for `ui5-deploy.yaml` in Fiori projects.
@ullasholla @IainSAP @devinea fyi
=> feat: enhanced ui5-config to also add abap-deploy middleware

.changeset/fluffy-wolves-compete.md, packages/ui5-application-writer/templates/optional/eslint/.eslintrc, packages/ui5-application-writer/test/__snapshots__/options.test.ts.snap
#213
replaces https://github.com/SAP/open-ux-tools/pull/210
=> chore(ui5-app) - update eslint ignorePatterns in generated apps

.changeset/kind-deers-peel.md, packages/fiori-freestyle-writer/templates/common/add/webapp/test/flpSandbox.html, packages/fiori-freestyle-writer/templates/common/add/webapp/utils/locate-reuse-libs.js, packages/fiori-freestyle-writer/test/__snapshots__/basic.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/index.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/listdetail.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/worklist.test.ts.snap
Copy FE changes from tool-suite #17610 to FF. Improve stability of bootstrap.
Applied fix based on https://stackoverflow.com/questions/403967/how-may-i-reference-the-script-tag-that-loaded-the-currently-executing-script
=> chore(FF-writer) - Apply stability changes from FE for test app bootstrap

.changeset/good-planes-compete.md, packages/ui5-application-writer/src/data/defaults.ts, packages/ui5-application-writer/test/data.test.ts
https://github.com/SAP/open-ux-tools/issues/290
Fix `frameworkUrl` logic.
Add unit tests.
=> fix(ui5-application-writer): use correct framework url #290

.changeset/tricky-radios-draw.md, packages/store/package.json, pnpm-lock.yaml
- fixes simple-get vulnerability
=> fix(security): upgrade keytar

.changeset/tasty-lies-promise.md, .changeset/twelve-cooks-fry.md, packages/fiori-freestyle-writer/test/__snapshots__/basic.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/index.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/listdetail.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/worklist.test.ts.snap, packages/odata-service-writer/test/__snapshots__/index.test.ts.snap, packages/odata-service-writer/test/unit/index.test.ts, packages/ui5-application-writer/src/index.ts, packages/ui5-application-writer/test/__snapshots__/index.test.ts.snap, packages/ui5-application-writer/test/__snapshots__/options.test.ts.snap, packages/ui5-config/src/middlewares.ts, packages/ui5-config/src/types.ts, packages/ui5-config/src/ui5-config.ts, packages/ui5-config/test/__snapshots__/index.test.ts.snap
For TBI https://github.com/SAP/open-ux-tools/issues/333
- Remove version from ui5-config
- Update TS types
- Update tests/snapshots
=> Tbi/ui5version in yaml/17765

.github/CODEOWNERS
This PR does the following:
- Add Codeowners PER modules (existing as of today)
Here are the new/updated teams [https://github.com/orgs/SAP/teams?query=ux-tools](https://github.com/orgs/SAP/teams?query=ux-tools)
=> feat(CODEOWNERS): add codeowners per module

.changeset/quick-queens-approve.md, packages/ui5-application-writer/src/data/defaults.ts, packages/ui5-application-writer/src/data/index.ts, packages/ui5-application-writer/test/data.test.ts, packages/ui5-application-writer/test/validators.test.ts
Fixes https://github.com/SAP/open-ux-tools/issues/345
=> fix(ui5-application-writer): Fixes ui5.package defaults merging

packages/fiori-elements-writer/test/__snapshots__/ovp.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/worklist.test.ts.snap, packages/fiori-elements-writer/test/ovp.test.ts, packages/fiori-elements-writer/test/worklist.test.ts, packages/odata-service-writer/templates/extend/manifest.json, packages/odata-service-writer/test/__snapshots__/index.test.ts.snap, packages/odata-service-writer/test/index.test.ts
https://github.com/SAP/open-ux-tools/issues/353
Also fixes variable version in `fiori-elements-writer` test which would otherwise block subsequent PRs
=> fix(odata-service-writer): Fix for annotations technical uri encoding

.changeset/lucky-houses-sneeze.md
Missed changeset in previous commit.
=> changeset(fiori-elements-writer): Missed cset in previous commit

.changeset/rich-monkeys-attack.md, .husky/pre-commit, packages/fiori-elements-writer/src/data/defaults.ts, packages/fiori-elements-writer/src/data/templateAttributes.ts, packages/fiori-elements-writer/src/index.ts, packages/fiori-elements-writer/src/translations/fiori-elements-writer.i18n.json, packages/fiori-elements-writer/src/types.ts, packages/fiori-elements-writer/src/validate.ts, packages/fiori-elements-writer/templates/v2/alp/extend/webapp/manifest.json, packages/fiori-elements-writer/templates/v2/lrop/extend/webapp/manifest.json, packages/fiori-elements-writer/templates/v2/ovp/extend/webapp/manifest.json, packages/fiori-elements-writer/templates/v2/worklist/extend/webapp/manifest.json, packages/fiori-elements-writer/templates/v4/lrop/extend/webapp/manifest.json, packages/fiori-elements-writer/test/__snapshots__/lrop.test.ts.snap, packages/fiori-elements-writer/test/alp.test.ts, packages/fiori-elements-writer/test/common.ts, packages/fiori-elements-writer/test/lrop.test.ts, packages/fiori-elements-writer/test/ovp.test.ts, packages/fiori-elements-writer/test/unit/defaults.test.ts, packages/fiori-elements-writer/test/unit/validate.test.ts
Fixes for:
https://github.com/SAP/open-ux-tools/issues/407 - consolidate types to remove unused and doc
https://github.com/SAP/open-ux-tools/issues/408 - default reuse libs to false
=> fix(fiori-elements-writer):fixes #407(types issues) #408(reuse libs off)

.changeset/flat-tigers-bake.md, packages/fiori-elements-writer/test/__snapshots__/lrop.test.ts.snap, packages/fiori-elements-writer/test/lrop.test.ts, packages/ui5-application-writer/src/data/defaults.ts, packages/ui5-application-writer/src/types.ts, packages/ui5-application-writer/templates/core/webapp/manifest.json, packages/ui5-application-writer/test/data.test.ts, packages/ui5-application-writer/test/index.test.ts
Implements feature:  https://github.com/SAP/open-ux-tools/issues/480
- Adds support for writing new (since manifest version 42) `sap.app.sourceTemplate.toolsId` property to `manifest.json`.
- Adds unit and integration tests
=> feature(ui5-application-writer): Adds `toolsId` to `sap.app.sourceTemplate` setting in `manifest.json`

.changeset/ten-points-film.md, packages/fiori-elements-writer/src/data/defaults.ts, packages/fiori-elements-writer/test/__snapshots__/lrop.test.ts.snap, packages/fiori-elements-writer/test/lrop.test.ts, packages/fiori-freestyle-writer/src/defaults.ts, packages/fiori-freestyle-writer/test/__snapshots__/basic.test.ts.snap, packages/fiori-freestyle-writer/test/basic.test.ts
https://github.com/SAP/open-ux-tools/issues/487
- Ensure `sourceTemplate.toolsId` is written when `sourceTemplate.id` or `sourceTemplate.version` are not provided.
- Adds tests to cover
=> fix(f-e-w/f-f-w):`sourceTemplate.toolsId` not written

.changeset/loud-chicken-yawn.md, packages/fiori-freestyle-writer/templates/basic/extend/webapp/manifest.json, packages/fiori-freestyle-writer/test/__snapshots__/basic.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/index.test.ts.snap, packages/fiori-freestyle-writer/test/basic.test.ts, pnpm-lock.yaml
Fix for #500
Noticed this while trying to use the latest version in easy-ui5
=> Fix issue in generated route in freestyle template

.changeset/mean-singers-accept.md, packages/fiori-elements-writer/templates/common/add/webapp/test/flpSandbox.html, packages/fiori-elements-writer/test/__snapshots__/alp.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/feop.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/lrop.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/ovp.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/worklist.test.ts.snap, pnpm-lock.yaml
Fix for: https://github.com/SAP/open-ux-tools/issues/502
- Move script closing tag to correct position in template
- Update snapshots
- Manual test that `changes_loader.js` is loading
=> fix(fiori-elements-writer): Fix for changes_loader.js not loading

.changeset/bright-cameras-refuse.md, package.json, packages/backend-proxy-middleware/package.json, packages/ui5-proxy-middleware/package.json
Required to be able to list them on https://bestofui5.org/
Issue: https://github.com/ui5-community/bestofui5-data/issues/31
=> add author to package.json for middlewares

.changeset/khaki-pumas-run.md, packages/backend-proxy-middleware/src/base/proxy.ts, packages/backend-proxy-middleware/test/base/proxy.test.ts
Fixes https://github.com/SAP/open-ux-tools/issues/558
=> fix(backend-proxy-middleware): set credentials from .env file

.changeset/chilly-dogs-call.md, packages/backend-proxy-middleware/src/base/proxy.ts, packages/backend-proxy-middleware/test/base/proxy.test.ts
Fixes https://github.com/SAP/open-ux-tools/issues/575
=> fix(backend-proxy-middleware): support direct OData service url in BAS

.changeset/ten-cows-lick.md, packages/backend-proxy-middleware/src/base/proxy.ts, packages/backend-proxy-middleware/src/base/types.ts, packages/backend-proxy-middleware/test/base/proxy.test.ts
Follow up of https://github.com/SAP/open-ux-tools/pull/576
=> fix(backend-proxy-middleware): add url to type DestinationBackendConfig

.changeset/brave-ducks-shave.md, packages/ui5-application-writer/src/data/defaults.ts, packages/ui5-config/src/ui5config.ts, packages/ui5-config/test/__snapshots__/index.test.ts.snap, packages/ui5-config/test/index.test.ts
Trim `themelib` property value.
https://github.com/SAP/open-ux-tools/issues/590
=> feat(ui5 application writer): trim themelib configuration property

docs/version-overrides.md, package.json, pnpm-lock.yaml
Reverts https://github.com/SAP/open-ux-tools/pull/601
=> chore(deps): revert glob-parent override

.changeset/few-pears-remain.md, packages/backend-proxy-middleware/src/base/proxy.ts, packages/backend-proxy-middleware/test/base/proxy.test.ts, packages/btp-utils/src/destination.ts, packages/btp-utils/test/destination.test.ts
Fixes: https://github.com/SAP/open-ux-tools/issues/608
=> fix(backend-proxy-middleware): fix handling of full url destinations

.changeset/strong-glasses-fix.md, packages/fiori-freestyle-writer/templates/basic/add/webapp/controller/App.controller.js, packages/fiori-freestyle-writer/test/__snapshots__/basic.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/index.test.ts.snap
Reported at https://github.com/ui5-community/generator-ui5-project/issues/55
=> fixed wrong app controller name

.changeset/grumpy-pants-juggle.md, examples/odata-cli/README.adoc, examples/odata-cli/src/activities.ts, examples/odata-cli/src/index.ts, examples/odata-cli/src/targets.ts, examples/odata-cli/src/types.ts, packages/axios-extension/src/abap/lrep-service.ts, packages/axios-extension/test/abap/lrep-service.test.ts
Contains:
- fix for #635 
- fix for #636
- fix to use `$tmp` when no package is provided
- enhancement of `examples/odata-cli` to also have a better way to debug issues like #636
=> Fixing multiple issues with the layered repository service

.changeset/curvy-badgers-brush.md, packages/fe-fpm-writer/templates/page/custom/1.84/ext/View.xml, packages/fe-fpm-writer/templates/page/custom/1.94/ext/View.xml, packages/fe-fpm-writer/test/integration/__snapshots__/index.test.ts.snap, packages/fe-fpm-writer/test/integration/index.test.ts, packages/fe-fpm-writer/test/unit/page/__snapshots__/custom.test.ts.snap
=> Fix for #618

.changeset/cyan-hounds-burn.md, packages/fe-fpm-writer/test/test-input/basic-ts/package.json, packages/fe-fpm-writer/test/test-input/basic-ts/tsconfig.json, packages/fiori-elements-writer/test/__snapshots__/fpm.test.ts.snap, packages/fiori-freestyle-writer/templates/listdetail/add/webapp/Component.ts, packages/fiori-freestyle-writer/templates/listdetail/add/webapp/controller/List.controller.ts, packages/fiori-freestyle-writer/templates/listdetail/add/webapp/controller/ListSelector.ts, packages/fiori-freestyle-writer/templates/worklist/add/webapp/controller/Worklist.controller.ts, packages/fiori-freestyle-writer/test/__snapshots__/basic.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/listdetail.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/worklist.test.ts.snap, packages/ui5-application-writer/templates/optional/typescript/package.json, packages/ui5-application-writer/templates/optional/typescript/tsconfig.json, packages/ui5-application-writer/test/__snapshots__/options.test.ts.snap
https://github.com/SAP/open-ux-tools/issues/621#issuecomment-1228672136
=> Improving the quality of the generated TS code

.changeset/wild-bugs-compare.md, packages/fe-fpm-writer/src/action/index.ts, packages/fe-fpm-writer/src/column/index.ts, packages/fe-fpm-writer/src/common/types.ts, packages/fe-fpm-writer/src/common/validate.ts, packages/fe-fpm-writer/src/page/custom.ts, packages/fe-fpm-writer/src/section/index.ts, packages/fe-fpm-writer/src/view/index.ts, packages/fe-fpm-writer/test/unit/__snapshots__/section.test.ts.snap, packages/fe-fpm-writer/test/unit/column.test.ts, packages/fe-fpm-writer/test/unit/page/custom.test.ts, packages/fe-fpm-writer/test/unit/section.test.ts, packages/fiori-elements-writer/src/index.ts
=> Fixing issue with wrong type of min ui5 version in fe-fpm-writer

.changeset/khaki-students-destroy.md, packages/fiori-elements-writer/templates/v2/common/add/webapp/test/changes_loader.ts, packages/fiori-elements-writer/templates/v2/common/add/webapp/test/changes_preview.ts, packages/fiori-elements-writer/test/__snapshots__/lrop.test.ts.snap, packages/fiori-elements-writer/test/lrop.test.ts
fix for #676
Because of the ignore here 
https://github.com/SAP/open-ux-tools/blob/main/packages/fiori-elements-writer/src/index.ts#L102
the js files are not copied. Adding a TS copy of the files so that the copy works. 
transpiling middleware removes the comments but otherwise seems ok. 
Added a test to cover the case
=> fix(fe-writer) Add missing JS files(changes_loader and changes_preview ) as ts files

.changeset/nice-bats-eat.md, packages/fiori-elements-writer/package.json, packages/fiori-elements-writer/src/index.ts, packages/fiori-elements-writer/src/packageConfig.ts, packages/fiori-elements-writer/src/types.ts, packages/fiori-elements-writer/test/__snapshots__/lrop.test.ts.snap, packages/fiori-elements-writer/test/lrop.test.ts, pnpm-lock.yaml
Adds OPA test generation to fiori-elements-writer.
https://github.com/SAP/open-ux-tools/issues/680
=> tbi(fiori-elements-writer): Integrate ui5 test writer

.changeset/orange-gorillas-kiss.md, packages/fe-fpm-writer/templates/page/custom/1.94/ext/View.xml, packages/fe-fpm-writer/test/integration/__snapshots__/index.test.ts.snap, packages/fe-fpm-writer/test/unit/page/__snapshots__/custom.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/fpm.test.ts.snap
=> tbi(fe-fpm-writer):683 Adds required namespace

.changeset/bright-months-provide.md, packages/ui-components/.eslintrc, packages/ui-components/src/components/Icons.tsx, packages/ui-components/src/components/UIDialog/UIDialog.tsx, packages/ui-components/src/components/UIFlexibleTable/UIFlexibleTable.scss, packages/ui-components/src/components/UIFlexibleTable/UIFlexibleTable.tsx, packages/ui-components/src/components/UIFlexibleTable/UIFlexibleTableRowNoData.tsx, packages/ui-components/src/components/UIFlexibleTable/types.ts, packages/ui-components/src/utilities/DeepMerge.ts, packages/ui-components/stories/UIFlexibleTable.story.tsx, packages/ui-components/test/unit/components/UIFlexibleTable.test.tsx
Updates for ui-components
1. New icons and no data component for table
=> add: new icons and table no data component

CONTRIBUTING.md, docs/Guidelines.md
=> Enhancing contribution guidelines

.changeset/cold-comics-chew.md, packages/ui-components/src/components/UIButton/UIDefaultButton.tsx
Fix: add style for disabled split button divider.
=> cherrypick UIDefaultButton fix TS/pull/21665

.changeset/lucky-readers-sit.md, packages/ui-components/src/components/UITable/types.ts
Export fluentui types used in UITable for easier consumption
=> chore(UI-Components) Export fluentui types used in UITable

.changeset/slimy-birds-fail.md, packages/environment-check/src/checks/get-installed.ts
=> fix(env-check): fix npm root command

.changeset/light-socks-film.md, packages/ui-components/src/components/UILink/UILink.tsx, packages/ui-components/stories/UILink.story.tsx, packages/ui-components/test/unit/components/UILink.test.tsx
Adding requested new property "secondary" for UILink component.
Difference between primary and secondary is only coloring:
=> feat(ui-components): new property "secondary" for UILink component

.changeset/purple-cats-beg.md, docs/version-overrides.md, package.json, pnpm-lock.yaml
More info at https://github.com/advisories/GHSA-f8q6-p94x-37v3
=> [SECURITY] override for minimatch for two modules that use the vulnerable version

.changeset/moody-bags-lay.md, packages/ui-components/package.json
See https://github.com/SAP/open-ux-tools/issues/755
Fix for `peerDependencies` in `@sap-ux/ui-components`.
=> fix(ui5-components): correct peer dependencies

packages/ui-components/src/components/UIPersona/UIPersona.tsx, packages/ui-components/src/components/UIPersona/index.tsx, packages/ui-components/src/components/index.tsx, packages/ui-components/stories/UIPersona.story.tsx, packages/ui-components/test/unit/components/UIPersona.test.tsx
=> feat(ui-components): add UIPersona

.changeset/light-melons-help.md, packages/axios-extension/package.json, packages/fe-fpm-writer/package.json, pnpm-lock.yaml
Security vulnerability reported for the @xmldom/xmldom dependency https://github.com/advisories/GHSA-crh6-fp67-6883
=> chore: Upgrade @xmldom/xmldom dependency to v0.8.4

.changeset/olive-sheep-jog.md, packages/fiori-elements-writer/templates/v2/common/add/webapp/test/changes_loader.js, packages/fiori-elements-writer/templates/v2/common/add/webapp/test/changes_loader.ts, packages/fiori-elements-writer/templates/v2/common/add/webapp/test/changes_preview.js, packages/fiori-elements-writer/templates/v2/common/add/webapp/test/changes_preview.ts, packages/fiori-elements-writer/test/__snapshots__/alp.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/lrop.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/ovp.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/worklist.test.ts.snap, packages/fiori-elements-writer/test/unit/templates.test.ts
#769 
Updates the Regex for the trusted hosts in changes_loader.js/ts and changes_preview.js/ts
=> fix(fiori-elements-writer): update trusted hosts in templates

.changeset/polite-insects-shave.md, .changeset/real-buttons-develop.md, packages/ui5-config/src/ui5config.ts, packages/ui5-config/test/__snapshots__/index.test.ts.snap, packages/ui5-config/test/index.test.ts, packages/yaml/src/yaml-document.ts, packages/yaml/test/yaml-document.test.ts
Adding functionality required to update yaml configurations.
- add mode to `updateAt()` to allow overwriting yaml nodes (https://github.com/SAP/open-ux-tools/commit/b2b075c967cec69b9317a57dd90d5900ec517f34)
- expose this functionality also in `ui5-config` as new function `updateCustomMiddleware()` (https://github.com/SAP/open-ux-tools/commit/255aa4a0adadbb9fbea4a8303f0c361b38c6d08a)
- allow to set `metadata` and `type` to yaml configuration (https://github.com/SAP/open-ux-tools/commit/255aa4a0adadbb9fbea4a8303f0c361b38c6d08a)
=> feat: enhance yaml features

.changeset/fair-donkeys-switch.md, package.json, packages/environment-check/package.json, packages/environment-check/src/checks/destination.ts, packages/environment-check/src/output/markdown.ts, pnpm-lock.yaml
#788
Consume bas-sdk with OAuth2UserTokenExchange auth type support.
=> fix(env-check): bump bas-sdk version to support oauth2usertokenexchange auth type

.changeset/kind-pianos-act.md, packages/ui-components/src/components/UITreeDropdown/UITreeDropdown.scss, packages/ui-components/src/components/UITreeDropdown/UITreeDropdown.tsx, packages/ui-components/stories/UITreedropdown.story.tsx
=> feat(ui-components) - ui-treedropdown add error message handling

.changeset/spotty-tables-smash.md, docs/version-overrides.md, package.json, pnpm-lock.yaml
Issue: tools-suite #22655 and #22663
=> fix(security): upgrade decode-uri-component

.changeset/long-bulldogs-juggle.md, packages/axios-extension/package.json, packages/backend-proxy-middleware/package.json, packages/ui5-proxy-middleware/package.json, pnpm-lock.yaml
Issue: tools-suite #22655
supertest and express upgraded to get later version of qs
=> fix(security): upgrade qs

.changeset/violet-bottles-sip.md, packages/logger/package.json, pnpm-lock.yaml
Align deps with versions in tools-suite
=> chore(logger) update winston deps

.changeset/olive-pillows-cheat.md, packages/fiori-elements-writer/test/__snapshots__/feop.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/fpm.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/lrop.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/basic.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/listdetail.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/worklist.test.ts.snap, packages/ui5-application-writer/templates/optional/typescript/package.json, packages/ui5-application-writer/test/__snapshots__/options.test.ts.snap
fix for https://github.com/SAP/open-ux-tools/issues/764
=> chore - TS writers update to "ui5-tooling-transpile": "^0.2.1" 

.changeset/real-readers-grab.md, packages/environment-check/src/checks/get-installed.ts, packages/environment-check/test/checks/get-installed.test.ts
TBI: #866 
- Removes hardcoded BAS generator search paths
- Adds NODE_PATH search paths
- Update/adds tests
=> tbi(environment-check): search node path for installed gens

packages/fiori-freestyle-writer/templates/worklist/add/webapp/controller/BaseController.ts, packages/fiori-freestyle-writer/templates/worklist/add/webapp/model/formatter.ts, packages/fiori-freestyle-writer/test/__snapshots__/worklist.test.ts.snap
fix https://github.com/SAP/open-ux-tools/issues/880
=> fix(fiori-freestyle-writer) align formatter name with JS template

.changeset/selfish-gorillas-confess.md, packages/ui-components/src/components/UIComboBox/UIComboBox.tsx, packages/ui-components/src/components/UITable/UITable-helper.tsx, packages/ui-components/src/components/UITable/UITable.tsx, packages/ui-components/src/components/UITable/types.ts, packages/ui-components/stories/UITable.story.tsx, packages/ui-components/test/unit/components/UITable.test.tsx
Changed UITable's boolean select into a more generic combobox
=> feat(21552): make UITable's combobox more generic

packages/fiori-freestyle-writer/templates/listdetail/add/webapp/controller/List.controller.ts, packages/fiori-freestyle-writer/test/__snapshots__/listdetail.test.ts.snap
=> suggestions for improvements

.changeset/light-impalas-destroy.md, packages/fiori-freestyle-writer/templates/worklist/add/webapp/controller/Object.controller.ts, packages/fiori-freestyle-writer/templates/worklist/add/webapp/controller/Worklist.controller.ts, packages/fiori-freestyle-writer/test/__snapshots__/worklist.test.ts.snap
=> fix worklist template to be compatible with @ui5/cli v2

.changeset/five-cherries-tease.md, packages/fiori-freestyle-writer/templates/listdetail/add/webapp/controller/Detail.controller.ts, packages/fiori-freestyle-writer/templates/listdetail/add/webapp/controller/List.controller.ts, packages/fiori-freestyle-writer/templates/listdetail/add/webapp/controller/ListSelector.ts, packages/fiori-freestyle-writer/test/__snapshots__/listdetail.test.ts.snap, packages/fiori-freestyle-writer/test/common.ts
fix https://github.com/SAP/open-ux-tools/issues/882 
- Add additional tests for build script 
- Replace Optional chaining
should be reverted as part of https://github.com/SAP/open-ux-tools/issues/904
=> fix(freestyle-writer) replace Optional chaining to be compatible with ui5/cli v2

.changeset/cuddly-schools-walk.md, packages/fiori-freestyle-writer/templates/listdetail/add/webapp/controller/Detail.controller.ts, packages/fiori-freestyle-writer/templates/listdetail/add/webapp/controller/List.controller.ts, packages/fiori-freestyle-writer/test/__snapshots__/basic.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/listdetail.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/worklist.test.ts.snap, packages/fiori-freestyle-writer/test/basic.test.ts, packages/fiori-freestyle-writer/test/listdetail.test.ts, packages/fiori-freestyle-writer/test/worklist.test.ts, pnpm-lock.yaml
fix #882
- Add more tests for TypeScript with ui5 1.108.x in FF writer
- Fix ts templates accordingly
=> fix(freestyle-writer) Add more tests for TypeScript with ui5 1.108.x and fix ts templates

.changeset/webpack576.md, packages/ui-components/package.json, pnpm-lock.yaml
Issue: https://github.com/SAP/open-ux-tools/security/dependabot/5
dependabot listed a vulnerability that gets closed by the given pull request.
=> chore: upgrade webpack

.changeset/strange-crabs-ring.md, packages/ui-components/src/components/Icons.tsx
New icons
-Refresh
-RefreshSmall
-ExpandNodes
-ContractNodes
-ContractNodesSmall
=> Addition of new icons

.changeset/gentle-dolls-reply.md, packages/ui-components/src/components/index.tsx
=> feat(ui-components) add uiseparator to index

.changeset/soft-grapes-crash.md, packages/axios-extension/src/auth/connection.ts, packages/axios-extension/test/auth/connection.test.ts, packages/deploy-tooling/README.md, packages/deploy-tooling/src/base/deploy.ts, packages/deploy-tooling/src/types/index.ts
Fix for https://github.com/SAP/open-ux-tools/issues/989
- Updated unit tests
- Updated readme.md with logging information
Command
```
./bin/deploy --name ZJLFFLDEC1 --description 'EC1 Deployment JLong Cataog' --package '$TMP' --archive-folder /Users/Documents/packages/testjl/dist --url http://mytest.server:50000 --client 100 --verbose true
```
Console output
```
2023-04-24 16:33:22 info    abap-deploy-task: ZJLFFLDEC1 found on target system: false 
2023-04-24 16:33:23 error   abap-deploy-task: Request failed with status code 401 
...
2023-04-24 16:33:23 warn    abap-deploy-task: Deployment failed with authentication error. 
2023-04-24 16:33:23 info    abap-deploy-task: Please maintain correct credentials to avoid seeing this error
(see help: …
```
=> fix(deploy-config): Ensure request interceptor id is only removed when csrf token found

.changeset/bright-garlics-know.md, packages/fe-fpm-writer/templates/page/custom/1.84/ext/Controller.ts, packages/fe-fpm-writer/templates/page/custom/1.94/ext/Controller.ts, packages/fe-fpm-writer/test/integration/__snapshots__/index.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/fpm.test.ts.snap
https://github.com/SAP/open-ux-tools/issues/1000
Remove redundant commas fixes eslint issues.
=> fix(app-gen): fix lint issues in ts files

.changeset/two-panthers-laugh.md, packages/project-access/src/index.ts, packages/project-access/src/project/cap.ts, packages/project-access/src/project/index.ts, packages/project-access/src/types/cap/index.ts, packages/project-access/test/project/cap.test.ts
#1015 
Introduce new utility function for getting a CAP project environment.
=> feat(project-access): get CAP environment config

.changeset/five-fans-accept.md, packages/fe-fpm-writer/templates/app/Component.ts, packages/fe-fpm-writer/templates/page/custom/1.94/ext/Controller.ts, packages/fe-fpm-writer/test/integration/__snapshots__/index.test.ts.snap, packages/fiori-elements-writer/templates/common/add/webapp/Component.ts, packages/fiori-elements-writer/templates/v4/feop/add/webapp/Component.ts, packages/fiori-elements-writer/test/__snapshots__/feop.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/fpm.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/lrop.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/ovp.test.ts.snap, packages/fiori-freestyle-writer/.eslintignore, packages/fiori-freestyle-writer/templates/listdetail/add/webapp/Component.js, packages/fiori-freestyle-writer/templates/listdetail/add/webapp/controller/BaseController.ts, packages/fiori-freestyle-writer/templates/listdetail/add/webapp/controller/List.controller.js, packages/fiori-freestyle-writer/templates/worklist/add/webapp/Component.js, packages/fiori-freestyle-writer/templates/worklist/add/webapp/controller/BaseController.ts, packages/fiori-freestyle-writer/templates/worklist/add/webapp/controller/Worklist.controller.js, packages/fiori-freestyle-writer/test/__snapshots__/index.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/listdetail.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/worklist.test.ts.snap
https://github.com/SAP/open-ux-tools/issues/270
=> TBI - Clean up eslint warnings in generated projects

.changeset/new-crabs-invite.md, packages/axios-extension/src/abap/message.ts, packages/axios-extension/test/abap/message.test.ts
Fix for https://github.com/SAP/open-ux-tools/issues/1047
- updated test cases
- validated on SBAS
=> fix(axios-extension): log the level set by the response node

.changeset/tough-scissors-tap.md, packages/axios-extension/package.json, packages/axios-extension/src/abap/adt-catalog/adt-catalog-service.ts, packages/axios-extension/src/abap/adt-catalog/adt-schema-store.ts, packages/axios-extension/src/abap/adt-catalog/services/ato-service.ts, packages/axios-extension/src/abap/adt-catalog/services/filestore-service.ts, packages/axios-extension/src/abap/adt-catalog/services/list-package-service.ts, packages/axios-extension/src/abap/adt-catalog/services/transportcheck-service.ts, packages/odata-service-writer/package.json, pnpm-lock.yaml
https://github.com/NaturalIntelligence/fast-xml-parser/security/advisories/GHSA-6w63-h3fj-q4vw 
https://github.com/SAP/open-ux-tools/security/dependabot/12 
https://github.com/SAP/open-ux-tools/security/dependabot/13
Issue: https://github.com/SAP/open-ux-tools/issues/1062
Issue: tools-suite #25082
=> fix(security): upgrade fast-xml-parser

.changeset/chilled-geese-sniff.md, .changeset/stupid-boxes-approve.md, packages/axios-extension/src/abap/adt-catalog/services/transportcheck-service.ts, packages/axios-extension/test/abap/abap-adt-service.test.ts
#1083
Encodes the path in case there is a namespace
=> fix(axios-ext): encode transport request payload

.changeset/witty-carpets-prove.md, packages/deploy-tooling/README.md, packages/deploy-tooling/src/base/deploy.ts, packages/deploy-tooling/src/cli/config.ts, packages/deploy-tooling/src/cli/index.ts, packages/deploy-tooling/src/types/index.ts, packages/deploy-tooling/test/__mocks__/@sap-ux/axios-extension.ts, packages/deploy-tooling/test/__mocks__/index.ts, packages/deploy-tooling/test/test-input/ui5-deploy.yaml, packages/deploy-tooling/test/unit/base/deploy.test.ts, packages/deploy-tooling/test/unit/cli/config.test.ts, packages/deploy-tooling/test/unit/cli/index.test.ts
Fix for https://github.com/SAP/open-ux-tools/issues/1084
- tests updated
- changeset appended
=> fix(deploy-tooling): Support new parameter 'service' 

.changeset/neat-peaches-dream.md, packages/fiori-elements-writer/test/__snapshots__/lrop.test.ts.snap, packages/fiori-elements-writer/test/lrop.test.ts, packages/fiori-freestyle-writer/test/__snapshots__/listdetail.test.ts.snap, packages/fiori-freestyle-writer/test/listdetail.test.ts, packages/ui5-application-writer/src/data/defaults.ts, packages/ui5-application-writer/src/index.ts, packages/ui5-application-writer/src/types.ts, packages/ui5-application-writer/templates/optional/typescript/package.json, packages/ui5-application-writer/templates/optional/typescript/tsconfig.json, packages/ui5-application-writer/test/data.test.ts, packages/ui5-config/src/defaults.ts, packages/ui5-config/src/index.ts, packages/ui5-config/src/utils.ts, packages/ui5-config/test/utils.test.ts
As described in the [@sapui5/ts-types-esm README file](https://www.npmjs.com/package/@sapui5/ts-types-esm), `@sapui5/types` should be preferred for newer SAPUI5 versions.
This closes #999.
=> feat(ui5-writer): use @sapui5/types with UI5 1.113 and newer

packages/backend-proxy-middleware/README.md
* correct wrong code snippets
* added another example of how to use the middleware with multiple backends or paths
=> Correct code snippets in readme

.changeset/early-geese-drive.md, packages/deploy-tooling/README.md, packages/deploy-tooling/src/base/deploy.ts, packages/deploy-tooling/src/cli/index.ts, packages/deploy-tooling/test/unit/base/deploy.test.ts
=> feat(deploy-tooling): create transport for undeployment

.changeset/cyan-mugs-compete.md, packages/deploy-tooling/src/cli/index.ts, packages/deploy-tooling/test/unit/cli/index.test.ts
Fix for https://github.com/SAP/open-ux-tools/issues/1150
- removed username and password conflict
- cleanup test cases, they were not behaving as expected as mock was not being correctly reset
=> fix(deploy-tooling): Allow CLI username param with destination CLI param

.changeset/unlucky-clouds-perform.md, packages/fiori-elements-writer/templates/common/add/webapp/test/flpSandbox.html, packages/fiori-elements-writer/test/__snapshots__/alp.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/lrop.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/ovp.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/worklist.test.ts.snap
https://github.com/SAP/open-ux-tools/issues/1158
=> Tbi/app gen/session storage connector 23289

packages/ui5-proxy-middleware/README.md
Will hopefully help with confusions like #1073.
Just changing the readme, no changeset needed.
=> Improved ui5-proxy-middleware README

package.json, pnpm-lock.yaml, tsconfig.json
fixes error no1. & no.2 in https://github.com/SAP/open-ux-tools/issues/1164
=> fix project reference postinstall windows

.changeset/wicked-moles-guess.md
publish to npm was not successful after #1110
=> chore(ui5-config) publish module

.changeset/bright-hornets-travel.md, packages/fiori-elements-writer/test/__snapshots__/alp.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/feop.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/fpm.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/lrop.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/ovp.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/worklist.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/basic.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/index.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/listdetail.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/worklist.test.ts.snap, packages/preview-middleware/templates/flp/locate-reuse-libs.js, packages/ui5-application-writer/templates/optional/loadReuseLibs/webapp/test/locate-reuse-libs.js, packages/ui5-application-writer/test/__snapshots__/options.test.ts.snap
follow-up fixes from https://github.com/SAP/open-ux-tools/pull/1194
=> fix lint warnings in locate-reuse-libs.js

.changeset/tasty-terms-argue.md, packages/deploy-tooling/src/types/index.ts, packages/deploy-tooling/src/ui5/archive.ts, packages/deploy-tooling/src/ui5/index.ts, packages/deploy-tooling/test/test-input/ui5-deploy.yaml, packages/deploy-tooling/test/unit/cli/archive.test.ts
Fix for https://github.com/SAP/open-ux-tools/issues/1213
- tests updated
=> fix(deploy-tooling): Apply exclude parameter when generating zip file

renovate.json5
Noticed that https://github.com/SAP/open-ux-tools/pull/1239 should not have been created.
=> chore(renovate) - ignore fixture(s) folders.

.changeset/bright-plants-fail.md, packages/ui-components/src/components/UIFlexibleTable/UIFlexibleTable.scss, packages/ui-components/stories/UIFlexibleTable.story.tsx
Issue #1262
Before:
After fix:
=> fix(ui-components): UIFlexibleTable. Text of columns title is not fully visible

.changeset/old-poets-refuse11.md, .changeset/old-poets-refuse22.md
Add changesets for 
https://github.com/SAP/open-ux-tools/pull/1252
https://github.com/SAP/open-ux-tools/pull/1247
=> chore - Add changesets for merged PR's

.changeset/tricky-jars-rest.md, packages/ui-components/test/unit/components/UITable-helper.test.tsx
Fix for: https://github.com/SAP/open-ux-tools/actions/runs/6237138309/job/16930023948?pr=1294
- add some wiggle room for measuring setTimeout execution time.
=> chore(uic): re-fix the sleep function tests

.changeset/few-starfishes-speak.md
https://github.com/SAP/open-ux-tools/issues/1310
=> chore - fix publishing of modules missed in failed release build

.changeset/happy-grapes-return.md
Bumps `preview-middleware`, `adp-tooling` and `control-property-editor` to release the fix https://github.com/SAP/open-ux-tools/pull/1331
=> bump preview, adp and cpe packages

.changeset/shiny-goats-push.md, packages/adp-tooling/package.json, packages/preview-middleware/package.json, pnpm-lock.yaml
Makes express peer dependency for `adp-tooling` and `preview-middleware`
=> fix(middlewares): make express peer dependecy

.changeset/brown-baboons-attend.md, packages/fe-fpm-writer/templates/header-section/1.86/manifest.json, packages/fe-fpm-writer/test/unit/__snapshots__/header-section.test.ts.snap, packages/fe-fpm-writer/test/unit/header-section.test.ts
Correction for `templateEdit` property in manifest template which led to parsing errors during manifest update generation.
Previously generated manifest contents (see random comma under template definition):
```
{
"sap.ui5": {
"routing": {
"targets": {
"BookingObjectPage": {
"options": {
"settings": {
"content": {
"header": {
"facets": {
"CustomHeaderSection1": {
"template": "lropv4081623.ext.fragment.CustomHeaderSection1",
,
"title": "Custom Header Section",
"requestGroupId": "Heroes",
"flexSettings": {
"designtime": "Default"
}
}
}
}
}
}
}
}
}
}
}
}
```
Now:
```
{
"sap.ui5": {
"routing": {
"targets": {
"BookingObjectPage": {
"options": {
"settings": {
"content": {
"header": {
"facets": {
"CustomHeaderSection1": {
"template": "lropv4081623.ext.fragment.CustomHeaderSection1",
"title": …
```
=> Fix(fpm-writer): Custom header section edit fragment generation error

.changeset/forty-forks-grin.md, packages/ui-components/src/components/UIButton/UIDefaultButton.tsx
Fix the UISplitButton focus state, fix the style
=> fix(ui-components): fix focus state for the split button

.changeset/nasty-jobs-help.md, packages/preview-middleware-client/src/flp/init.ts, packages/preview-middleware-client/test/unit/flp/init.test.ts, packages/preview-middleware-client/types/sap.dt.d.ts
createRenderer method argument order must be maintained for maintenance versions.
=> fix: createRenderer method to support maintenance versions

.changeset/lemon-buses-sneeze.md
This is a changeset is for publishing the preview-middleware-client to consume it internally.
=> changeset for publishing preview-middleware

.changeset/lucky-rocks-juggle.md, packages/preview-middleware/src/base/flp.ts, packages/preview-middleware/test/unit/base/__snapshots__/flp.test.ts.snap
Adds LocalStorageConnector to `sandbox.html` so that app personalizations are kept across preview sessions
#1158
=> feat(preview-middleware): add LocalStorageConnector

.changeset/unlucky-adults-peel.md, packages/preview-middleware/src/index.ts
Exports the `FlpConfig` and `RtaConfig` types for usage in `@sap/ux-ui5-tooling`.
=> feat(preview-middleware): export FlpConfig and RtaConfig types

.changeset/spotty-files-provide.md, packages/ui-components/src/components/UIActionCallout/UIActionCallout.scss
#1409 
Make the UI Action Callout pop-up more visible with these style changes.
=> feat(UI components): 1409 change UI action callout control css

.changeset/pretty-geckos-vanish.md, packages/ui-components/src/components/UIButton/UISplitButton.tsx, packages/ui-components/stories/UIButton.story.tsx, packages/ui-components/test/unit/components/UISplitButton.test.tsx
Update UISplitButton state on props change
=> Fix(ui-components): UISplitButton state update

.changeset/friendly-roses-lie.md, packages/ui-components/src/components/Icons.tsx
update `header` and `layout` icons
=> fix(ui-components): update `header` and `layout` icons

.changeset/tasty-zoos-bathe.md, packages/odata-annotation-core/src/annotation-file.ts
=> fix: bug fix

.changeset/pink-clouds-switch.md, packages/control-property-editor/package.json, packages/control-property-editor/src/App.tsx, packages/control-property-editor/test/unit/App.test.tsx, pnpm-lock.yaml
Fixed issue where initial warning dialog was shown in CPE for APD projects
=> fix(cpe): do not show warning dialog

.changeset/stale-carrots-smoke.md, packages/adp-tooling/templates/project/package.json, packages/adp-tooling/test/unit/writer/__snapshots__/index.test.ts.snap
Fix for https://github.com/SAP/open-ux-tools/issues/1510
- updated test cases
-  validated on windows
- added changeset
=> fix(deploy-tooling): Correctly escape lrep flag

.changeset/angry-roses-draw.md, packages/fe-fpm-writer/src/column/index.ts, packages/fe-fpm-writer/src/column/types.ts, packages/fe-fpm-writer/src/common/types.ts, packages/fe-fpm-writer/src/section/index.ts, packages/fe-fpm-writer/src/section/types.ts, packages/fe-fpm-writer/templates/column/1.84/manifest.json, packages/fe-fpm-writer/templates/column/1.85/manifest.json, packages/fe-fpm-writer/templates/column/1.86/manifest.json, packages/fe-fpm-writer/templates/header-section/1.86/manifest.json, packages/fe-fpm-writer/templates/section/1.86/manifest.json, packages/fe-fpm-writer/templates/subsection/1.86/manifest.json, packages/fe-fpm-writer/test/unit/__snapshots__/column.test.ts.snap, packages/fe-fpm-writer/test/unit/__snapshots__/section.test.ts.snap, packages/fe-fpm-writer/test/unit/column.test.ts, packages/fe-fpm-writer/test/unit/section.test.ts
Added optional `fragmentName` property to use as keys in manifest templates.
=> feat: fragmentFile property for custom extensions

.changeset/silent-walls-whisper.md, packages/preview-middleware/src/base/flp.ts, packages/preview-middleware/test/unit/base/__snapshots__/flp.test.ts.snap
Fixes #1555
I also tested the setting with regular apps and it doesn't cause problems (it is actually correct, just not required)
=> Fix preview of adaption projects with decsriptor changes requiring a client-side merge

packages/ui5-info/package.json, pnpm-lock.yaml
Fixes https://github.com/advisories/GHSA-xvch-5gv4-984h
=> chore: fix critical dependency to minimist

package.json, pnpm-lock.yaml
=> chore(deps): update pnpm to v8.14.0

.changeset/heavy-socks-rhyme.md, .changeset/plenty-carrots-act.md, packages/axios-extension/src/abap/ui5-abap-repository-service.ts, packages/axios-extension/test/abap/ui5-abap-repository-service.test.ts
#1257
Adds an additional log at the end to clarify the URL may require an update to point to the deployed app
=> fix(axios-ext): adds additional log for deployment

.changeset/curvy-apes-joke.md, packages/odata-vocabularies/src/resources/index.ts, packages/odata-vocabularies/test/__snapshots__/loader.test.ts.snap, packages/odata-vocabularies/test/loader.test.ts
replace alias ODataJSON with JSON
add unit tests
=> fix(odata-vocabularies): replace alias ODataJSON with JSON

.changeset/red-beans-cover.md, packages/cds-annotation-parser/src/transformer/ast.ts, packages/cds-annotation-parser/test/data/invalid/terms/case-3/assignment.txt, packages/cds-annotation-parser/test/data/invalid/terms/case-3/ast.json, packages/cds-annotation-parser/test/data/invalid/terms/case-3/cst.json
consider ALL potential vocabulary aliases, also the ones for additional analytical terms 
unit tests
=> fix(cds-anno-parser): consider ALL potential vocabulary aliases

.changeset/shiny-worms-knock.md, packages/odata-vocabularies/src/resources/com.sap.cds.vocabularies.AnalyticsDetails.ts, packages/odata-vocabularies/src/resources/com.sap.cds.vocabularies.ObjectModel.ts, packages/odata-vocabularies/test/__snapshots__/loader-cds-analytics.test.ts.snap
Update Vocabularies Containing Cds Specific Analytics Annotations
=> OData Vocabularies: Update Vocabularies Containing Cds Specific Analytics Annotations

packages/odata-annotation-core-types/README.md
=> chore: fix package name in readme

.changeset/afraid-guests-deliver.md, packages/cds-odata-annotation-converter/src/printer/csdl-to-cds.ts, packages/cds-odata-annotation-converter/test/printer/__snapshots__/csdl-to-cds.test.ts.snap, packages/cds-odata-annotation-converter/test/printer/csdl-to-cds.test.ts
=> fix: refactor print target

.changeset/curvy-fans-reflect.md, packages/ui-components/src/components/Icons.tsx
Addition of Icon for App info Page. Needed for new dev efforts.
=> Addition of Icon for App Info Page

.changeset/new-glasses-share.md, packages/fiori-elements-writer/src/data/defaults.ts, packages/fiori-elements-writer/src/data/templateAttributes.ts, packages/fiori-elements-writer/src/index.ts, packages/fiori-elements-writer/src/packageConfig.ts, packages/fiori-elements-writer/test/common.ts
https://github.com/SAP/open-ux-tools/issues/1689
- Adds exports to support move to open ux tools
- Fix lint warnings
=> tbi(fiori-elements-writer): Adds exports

.changeset/sweet-paws-play.md, packages/store/README.md, packages/store/src/secure-store/index.ts, packages/store/test/unit/secure-store/index.test.ts
Module `@sap-ux/store` is storing setting and keys to file system or operating system specific secure storage. With this pull request, we add functionality that allows to disable access to secure storage via environment variable `FIORI_TOOLS_DISABLE_SECURE_STORE`.
=> feat(store): allow to disable secure store access

.changeset/ten-plants-care.md
Bump patch version for preview-middleware. Missed in previous PR
https://github.com/SAP/open-ux-tools/pull/1728
=> fix: update preview-middleware patch for cpe

package.json, packages/adp-tooling/package.json, packages/control-property-editor-common/package.json, packages/control-property-editor/package.json, packages/create/test/fixtures/ui5-deploy-config/package.json, packages/fe-fpm-writer/test/test-input/integration/basic-lrop-app/js/package.json, packages/feature-toggle/package.json, packages/jest-runner-puppeteer/package.json, packages/mockserver-config-writer/test/fixtures/no-ui5-mock-config/package.json, packages/odata-annotation-core-types/package.json, packages/odata-annotation-core/package.json, packages/odata-entity-model/package.json, packages/odata-vocabularies/package.json, packages/system-access/package.json, packages/xml-odata-annotation-converter/package.json, pnpm-lock.yaml
Required for #1751
I did not add a changeset on purpose because the change does not affect anything we release.
=> Upgrading `rimraf` to remove problematic dependency to `minimatch`

.changeset/chatty-poems-burn.md
=> fix: changeset fix

.changeset/loud-eels-judge.md, packages/inquirer-common/src/index.ts, packages/inquirer-common/src/prompts/helpers.ts, packages/inquirer-common/test/unit/prompts/helpers.test.ts, packages/ui5-application-inquirer/src/prompts/prompt-helpers.ts
Export extendAdditionalMessages from inquirer common module
=> export extendAdditionalMessages from inquirer common module

.changeset/stupid-eyes-greet.md, packages/preview-middleware/README.md, packages/preview-middleware/src/base/flp.ts, packages/preview-middleware/src/types/index.ts, packages/preview-middleware/test/unit/base/__snapshots__/flp.test.ts.snap, packages/preview-middleware/test/unit/base/flp.test.ts
=> Allow adding tiles pointing to remotely available apps in the preview-middleware

.changeset/late-pumas-marry.md, packages/reload-middleware/README.md, packages/reload-middleware/src/base/constants.ts
The appdescr_variant file extension added to the default set of watched files
=> feat: appdescr_variant extension watched by default

.changeset/large-planets-wonder.md, packages/control-property-editor/src/ws-middleware.ts
=> fix: CPE websocket over https

.changeset/fresh-walls-give.md, packages/telemetry/src/tooling-telemetry/telemetry-settings.ts
Fix sonar issue about Array.reduce() call missing default value.
Link to original sonar issue:
https://sonarcloud.io/project/issues?resolved=false&severities=BLOCKER,CRITICAL,MAJOR,MINOR&sinceLeakPeriod=true&types=BUG&id=SAP_open-ux-tools&open=AY6jPjnTed7kdlBgm2p4&tab=code
=> fix sonar issue

.changeset/proud-students-repeat.md, packages/environment-check/src/checks/service-checks.ts, packages/environment-check/src/translations/env-check.i18n.json, packages/environment-check/test/checks/service-checks.test.ts, packages/environment-check/test/output/__snapshots__/markdown.test.ts.snap, packages/environment-check/test/output/markdown.test.ts
Update the current Environment Check to give more details about error code 403 about missing authorizations.
Update the message to include link to Guided Answers: https://ga.support.sap.com/dtp/viewer/index.html#/tree/3046/actions/45995:45996:50742:46000:57266
=> feat(environment-check): transport request 403 env check

.changeset/moody-windows-look.md, packages/fiori-elements-writer/test/__snapshots__/alp.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/feop.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/fpm.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/lrop.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/ovp.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/worklist.test.ts.snap, packages/odata-service-writer/src/index.ts, packages/odata-service-writer/test/__snapshots__/index.test.ts.snap, packages/ui5-config/test/__snapshots__/index.test.ts.snap, packages/ui5-config/test/index.test.ts
#1735 
ui5-mock.yaml is generated with the annotations config based on manifest
=> fix(mock-server-config): annotation config on generation

.changeset/sharp-ways-float.md, packages/ui-components/src/components/UICheckbox/UICheckbox.tsx, packages/ui-components/stories/UICheckbox.story.tsx, packages/ui-components/test/unit/components/UICheckbox.test.tsx
Fixes disabled UICheckbox styling issues mentioned in: https://github.com/SAP/open-ux-tools/issues/1776
=> fix: Disabled UICheckbox styling

.changeset/brown-planets-help.md, packages/preview-middleware/templates/test/qunit.js, packages/preview-middleware/test/unit/base/__snapshots__/flp.test.ts.snap
Set  qunit autostart to false as recommended by @matz3 [here](https://github.com/SAP/open-ux-tools/pull/1726/files#r1549565997)
=> fix(preview-middleware): set qunit autostart to false

.changeset/seven-experts-teach.md, packages/axios-extension/src/abap/lrep-service.ts, packages/axios-extension/src/abap/message.ts, packages/axios-extension/src/abap/ui5-abap-repository-service.ts, packages/axios-extension/src/index.ts, packages/axios-extension/test/abap/lrep-service.test.ts, packages/deploy-tooling/src/base/deploy.ts
- Abstracts the existing logic for logging the body of the axios response to console, exports it and uses for LREP.
Fix for https://github.com/SAP/open-ux-tools/issues/1807
=> fix: (deploy-tooling): valid error messages for adaptation projects

.changeset/slow-hairs-raise.md, packages/preview-middleware/src/base/flp.ts
Fixes https://github.com/SAP/open-ux-tools/issues/1815
=> fix(preview-middleware-client): support connect and express api

.changeset/dull-rockets-rush.md, packages/ui5-library-reference-inquirer/README.md, packages/ui5-library-reference-inquirer/src/prompts/prompts.ts, packages/ui5-library-reference-inquirer/src/translations/ui5-library-reference-inquirer.i18n.json, packages/ui5-library-reference-inquirer/test/unit/__snapshots__/ui5-library-reference-inquirer.test.ts.snap, packages/ui5-library-reference-inquirer/test/unit/prompts/__snapshots__/prompts.test.ts.snap, packages/ui5-library-reference-inquirer/test/unit/prompts/prompts.test.ts, packages/ui5-library-reference-inquirer/test/unit/ui5-library-reference-inquirer.test.ts
Fixes prompt choices for projects and libs
i18n fix
Read me correction
=> feat(ui5-lib-ref): prompt choice fix

.changeset/happy-melons-compete.md, packages/inquirer-common/src/types.ts, packages/ui5-library-reference-inquirer/README.md, packages/ui5-library-reference-inquirer/package.json, packages/ui5-library-reference-inquirer/src/choices.ts, packages/ui5-library-reference-inquirer/src/index.ts, packages/ui5-library-reference-inquirer/src/prompts/prompts.ts, packages/ui5-library-reference-inquirer/test/unit/choices.test.ts, packages/ui5-library-reference-inquirer/test/unit/prompts/prompts.test.ts, pnpm-lock.yaml
#1800
fix additionalMessages and update readme
=> fix(ui5-ref-lib): fix additionalMessages and update readme

docs/tools-offline-instructions/info/extensions.json, docs/tools-offline-instructions/info/globalModules.json, docs/tools-offline-instructions/info/projectModules.json
Adding package and version information which can be used to create a bundle for offline usage of SAP Fiori tools.
=> feat: add version info for offline usage

.changeset/bright-radios-build.md, packages/project-access/src/constants.ts, packages/project-access/src/index.ts
https://github.com/SAP/open-ux-tools/issues/1799
=> tbi(project-access): add missing fiori tools settings enum

.changeset/eight-steaks-reply.md, packages/fiori-elements-writer/src/data/defaults.ts, packages/fiori-elements-writer/src/index.ts, packages/fiori-elements-writer/templates/v2/alp/extend/webapp/manifest.json, packages/fiori-elements-writer/templates/v2/lrop/extend/webapp/manifest.json, packages/fiori-elements-writer/templates/v4/lrop/extend/webapp/manifest.json, packages/fiori-elements-writer/test/__snapshots__/lrop.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/worklist.test.ts.snap, packages/fiori-elements-writer/test/unit/defaults.test.ts
Fix passing the Table Type Parameters to the writer
=> Fiori Elements - Further table type updates

.changeset/six-dolphins-deny.md, packages/fiori-elements-writer/templates/v2/lrop/extend/webapp/manifest.json, packages/fiori-elements-writer/templates/v2/worklist/extend/webapp/manifest.json, packages/fiori-elements-writer/test/__snapshots__/lrop.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/worklist.test.ts.snap, packages/fiori-elements-writer/test/lrop.test.ts, packages/fiori-elements-writer/test/worklist.test.ts
Fix for #1870 
- Updates v2 worklist template to include table type setting
- Add test to cover
=> fix(fiori-elements-writer): Add v2 worklist table type

.changeset/modern-tigers-remain.md, packages/preview-middleware-client/src/adp/init.ts, packages/preview-middleware-client/test/unit/adp/init.test.ts, packages/preview-middleware/src/base/flp.ts
Enable telemetry for adaptation project
=> feat: enable telemetry for adaptation project

docs/tools-offline-instructions/info/projectModules.json
Update file `docs/tools-offline-instructions/info/projectModules.json` which is used in scripts to make SAP Fiori tools offline available.
=> chore(tools-offline): update list of project dependencies

docs/version-overrides.md, package.json, packages/ui-components/package.json, pnpm-lock.yaml
- upgrade storybook
- in order to be able to remove the ip overrride
Issue: https://github.com/SAP/open-ux-tools/issues/1767
=> fix(security): remove ip override

.changeset/many-beers-knock.md, packages/deploy-tooling/src/base/config.ts, packages/deploy-tooling/src/cli/index.ts, packages/deploy-tooling/src/ui5/index.ts, packages/deploy-tooling/test/unit/base/config.test.ts, packages/ui5-config/src/index.ts, packages/ui5-config/src/utils.ts, packages/ui5-config/test/utils.test.ts
#1880 
- Moves replaceEnvVariables and respective tests out of deploy-tooling to ui5-config
=> tbi(deploy-tooling): move replaceEnvVariables to ui5-config

.changeset/few-pugs-protect.md, packages/btp-utils/package.json, packages/btp-utils/src/app-studio.ts, packages/btp-utils/test/app-studio.test.ts, packages/btp-utils/tsconfig.json, packages/control-property-editor/src/actions.ts, packages/control-property-editor/src/index.tsx, packages/control-property-editor/src/middleware.ts, packages/control-property-editor/src/slice.ts, packages/control-property-editor/src/ws-middleware.ts, packages/control-property-editor/test/unit/appIndex.test.ts, packages/preview-middleware/package.json, packages/preview-middleware/src/base/flp.ts, packages/preview-middleware/templates/flp/editor.html, packages/preview-middleware/test/unit/base/__snapshots__/flp.test.ts.snap, packages/preview-middleware/tsconfig.json, packages/reload-middleware/package.json, packages/reload-middleware/src/base/livereload.ts, packages/reload-middleware/src/ui5/middleware.ts, packages/reload-middleware/test/unit/base/livereload.test.ts, packages/reload-middleware/tsconfig.json, pnpm-lock.yaml
Livereload is served from a different url in SBAS. Changed CPE coding to correctly handle such scenarios.
=> fix: preview reload in sbas

.changeset/rare-dodos-stare.md, packages/adp-tooling/src/index.ts
Export migrate adaptation tooling function 
[TBI - Create a separate Adaptation template file writer for Migration #1901](https://github.com/SAP/open-ux-tools/issues/1901)
=> feat(adp-tooling): export migrate adt

.changeset/five-hairs-hide.md, packages/axios-extension/src/abap/adt-catalog/generators/index.ts, packages/axios-extension/src/abap/adt-catalog/index.ts, packages/axios-extension/src/abap/adt-catalog/services/businessobjects-service.ts, packages/axios-extension/src/abap/index.ts, packages/axios-extension/test/abap/abap-adt-service.test.ts
https://github.com/SAP/open-ux-tools/issues/1920
=> fix(axios-extension): use correct param for business object request, add exports

.changeset/cold-coats-do.md, packages/project-access/src/constants.ts, packages/project-access/src/types/info/index.ts, packages/ui5-config/src/index.ts
- Add const `SchemaName` that contain Fiori Tools File System (ftfs) schema.
- Export `ODataVersion` as alias to `NonNullable<ManifestNamespace.Setting['odataVersion']>`
- Export `CustomItem` from `ui5-config`
=> fix: small changes to simplify consumption

.changeset/small-dancers-hunt.md, .vscode/launch.json, packages/adp-tooling/src/writer/index.ts, packages/adp-tooling/test/unit/writer/__snapshots__/index.test.ts.snap
Only copy the ui5.yaml, package.json and .gitignore files to the project to be migrated.
=> Fix Adaptation migration

.changeset/slow-lizards-shake.md, .vscode/launch.json, packages/system-access/package.json, packages/system-access/src/base/connect.ts, packages/system-access/test/__mocks__/@sap-ux/axios-extension.ts, packages/system-access/test/__mocks__/@sap-ux/btp-utils.ts, packages/system-access/test/unit/base/connect.test.ts, pnpm-lock.yaml
Fixes #1951 by doing a test request during initialization and if it fails with a 401, prompt the user for credentials.
=> fix: destination with basic auth issue

.changeset/thick-geese-live.md, packages/fiori-elements-writer/templates/v2/common/add/webapp/test/changes_loader.ts, packages/fiori-elements-writer/test/__snapshots__/lrop.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/ovp.test.ts.snap
Fix "Uncaught TypeError: Assignment to constant variable." in changes_loader.ts
=> Fix "Uncaught TypeError: Assignment to constant variable." in changes_loader.ts

.changeset/chatty-apricots-occur.md, packages/fe-fpm-writer/src/action/index.ts, packages/fe-fpm-writer/src/action/types.ts, packages/fe-fpm-writer/test/unit/__snapshots__/action.test.ts.snap, packages/fe-fpm-writer/test/unit/action.test.ts
Added custom action feature within custom section.
=> feat: Custom action within custom section

.changeset/healthy-dragons-poke.md, packages/deploy-tooling/src/base/deploy.ts, packages/deploy-tooling/test/unit/base/deploy.test.ts
#2003
Updates transport requst description, and truncate it if it exceeds 60 character limit
=> fix(deploy-tooling): update (and truncate) transport request description

.changeset/plenty-geckos-add.md, packages/cds-odata-annotation-converter/package.json, packages/cds-odata-annotation-converter/test/setup.ts, pnpm-lock.yaml
=> fix: facade version

.changeset/poor-adults-wonder.md, .changeset/sharp-dolls-exercise.md, packages/fiori-annotation-api/src/fiori-service.ts
expose vocabulary service to use outside of the package.
=> fix: update access modifier

.changeset/unlucky-pumpkins-double.md, packages/adp-tooling/src/base/change-utils.ts, packages/adp-tooling/test/unit/base/change-utils.test.ts
https://github.com/SAP/open-ux-tools/issues/2106
- Incorrect change mapping for 'reference' property for Adaptation Project's writers
=> fix: Incorrect change mapping for 'reference' property for Adaptation Project's writers

.changeset/nice-jars-bake.md, packages/project-access/src/project/service.ts
https://github.com/SAP/open-ux-tools/issues/2112
- Bump @sap-ux/project-access version to consume filterDataSourcesByType function
=> fix: Release version of @sap-ux/project-access with filterDataSourcesByType

.github/workflows/codeql-analysis.yml, .github/workflows/lint.yml, .github/workflows/pipeline.yml, .github/workflows/reuse-compliance.yml, packages/preview-middleware/test/integration/preview/preview.spec.ts
- pnpm setup in pipeline is failing. Update GH Actions. 
- skip integration tests for older versions. Bug created to investigate https://github.com/SAP/open-ux-tools/issues/2121
=> chore - Update actions - fix broken pipeline

.changeset/kind-snails-boil.md, packages/environment-check/src/output/markdown.ts, packages/environment-check/src/translations/env-check.i18n.json, packages/environment-check/src/types.ts, packages/environment-check/test/output/__snapshots__/markdown.test.ts.snap
#2141 
New ordering of environment check results in bas:
New order:
1. Destination Details
2. Messages
3. All Destinations (minimised by default, in a dropdown)
=> feat(environment-check): update order, destinations in dropdown

.changeset/friendly-swans-bow.md, packages/adp-tooling/src/writer/options.ts, packages/adp-tooling/test/unit/writer/__snapshots__/index.test.ts.snap, packages/preview-middleware/README.md, packages/ui5-config/src/middlewares.ts, packages/ui5-config/src/types/middlewares.ts, packages/ui5-config/src/ui5config.ts
Fix for #2145 
- Configure custom middlewares in ui5.yaml in correct way
=> fix: generate correct ui5.yaml for adp

packages/ui5-application-writer/src/options.ts
https://github.com/SAP/open-ux-tools/issues/2031
Moved adding of `sap-ux` logic based on `projectType` to feature implementation instead of containing the logic in optional feature logic under `ui5-application-writer`
Addressing [comment](https://github.com/SAP/open-ux-tools/pull/2102#discussion_r1673596529)
=> Refactor: Move sap-ux Logic Based on projectType to Feature Implementation

.changeset/new-radios-raise.md, packages/project-access/src/index.ts, packages/project-access/src/project/index.ts, packages/project-access/src/project/search.ts
Fix for https://github.com/SAP/open-ux-tools/issues/2007
- required by new modules but doing this early so we can do some local testing
=> fix(project-access): export findCapProjectRoot

packages/fiori-annotation-api/test/unit/virtual-fs.ts
Other unrelated [PR ](https://github.com/SAP/open-ux-tools/pull/2180) is failing because [test cds layering](https://github.com/SAP/open-ux-tools/blob/main/packages/fiori-annotation-api/test/unit/fiori-service.test.ts#L525) is failing with error:
```
ENOENT: no such file or directory, stat '/home/runner/work/open-ux-tools/open-ux-tools/packages/fiori-annotation-api/test/data/cds/layering/node_modules/@types/sap__cds'
```
Also I can reproduce it locally with latest main branch.
After debugging - `open-ux-tools/packages/fiori-annotation-api/test/data/cds/layering/node_modules/@types/sap__cds' is shown for me as symbolic link with unexisting path:
As fix - adding additional check to avoid error.
=> fix: failing test

.changeset/grumpy-pens-learn.md, packages/project-access/src/project/info.ts, packages/project-access/test/project/minUI5Version.test.ts
Reverts SAP/open-ux-tools#2206 based on the review comment https://github.com/SAP/open-ux-tools/pull/2206#issuecomment-2263348220
=> Revert "fix(#2173): consider variables in minUI5Version"

.changeset/three-colts-count.md, docs/version-overrides.md, examples/odata-cli/package.json, package.json, packages/axios-extension/package.json, packages/odata-service-inquirer/package.json, packages/odata-service-writer/package.json, packages/project-access/package.json, pnpm-lock.yaml
Issue: tools-suite/issues/30768
Issue: https://github.com/SAP/open-ux-tools/security/dependabot/110
=> fix(security): update fast-xml-parser

.github/workflows/pipeline.yml
Hopefully fix sonarcloud failures in release build
=> Update pipeline.yml - extend timeout

.changeset/great-buttons-look.md, packages/preview-middleware-client/src/adp/controllers/BaseDialog.controller.ts, packages/preview-middleware-client/src/adp/utils.ts, packages/preview-middleware-client/test/unit/adp/controllers/AddFragment.controller.test.ts
Fixes #2209.
This issue is a symptom of a larger issue where we do not have correct types for RTA commands and flex objects. I started updating the types, but it turned out it would require more effort and we should not block this fix by that, so I made a separate TBI for that #2220.
=> fix: add xml fragment

.changeset/stale-squids-argue.md, packages/ui5-info/src/ui5-version-fallback.ts, packages/ui5-info/test/__snapshots__/ui5-version-info.test.ts.snap, packages/ui5-info/test/commands.test.ts
https://github.com/SAP/open-ux-tools/issues/2232
- Updates fallbacks
- Updates snapshots
=> fix(ui5-info): Fixes out of date ui5-version fallbacks

.changeset/itchy-melons-end.md, packages/control-property-editor/src/panels/properties/HeaderField.tsx, packages/control-property-editor/test/unit/panels/properties/HeaderField.test.tsx
Fixed copy to clipboard caching old values.
Also fixed sonar issues in the file.
=> fix(cpe): copy to clipboard

.changeset/fluffy-months-provide.md, docs/version-overrides.md, package.json, packages/environment-check/package.json, pnpm-lock.yaml
- remove all overrides as no longer required
- update modules to get axios updates
Issue: tools-suite/issues/30924
Issue: https://github.com/SAP/open-ux-tools/security/dependabot/118
=> fix(security): update axios overrides

.changeset/friendly-trees-admire.md, packages/fiori-elements-writer/test/__snapshots__/alp.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/feop.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/fpm.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/lrop.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/ovp.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/worklist.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/basic.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/index.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/listdetail.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/worklist.test.ts.snap, packages/ui5-application-writer/templates/optional/loadReuseLibs/webapp/test/locate-reuse-libs.js, packages/ui5-application-writer/test/__snapshots__/options.test.ts.snap
=> fix(ui5-application-writer) backward support for older ui5 versions

.changeset/green-plums-pay.md, packages/abap-deploy-config-inquirer/package.json, pnpm-lock.yaml
Fix for https://github.com/SAP/open-ux-tools/issues/2128
- remove inquirer package
=> fix(abap-deploy-config-inquirer ): remove inquirer package

.changeset/weak-mugs-eat.md, nx.json
Update nx.json for (sub) generator modules with `generators` as the `outDir`
=> chore(ui5-lib): update nx.json for generators

.changeset/clean-meals-care.md
preview middleware was not part of changeset for preview middleware client fix https://github.com/SAP/open-ux-tools/pull/2430 🙈
=> preview middleware version bump

.changeset/blue-waves-joke.md, packages/ui-components/src/components/UIComboBox/UIComboBox.tsx, packages/ui-components/src/components/UIDropdown/UIDropdown.tsx, packages/ui-components/stories/UICombobox.story.tsx, packages/ui-components/stories/UIDropdown.story.tsx, packages/ui-components/test/unit/components/UICombobox.test.tsx, packages/ui-components/test/unit/components/UIDropdown.test.tsx
UIComboBox and UIDropdown support custom renderers for dropdown items via the `onRenderOption` and `onRenderItem` properties
=> feat: UIComboBox and UIDropdown support custom renderers for dropdown items via the `onRenderOption` and `onRenderItem` properties

.changeset/few-items-hunt.md, packages/ui-components/src/components/Icons.tsx
- Add `UIunregisterIcons` to unregister custom icons already register
- Add `UIsetIconOptions` to set some options for icons like disable warning especially useful for clear unit test
=> feat(ui-c): add UIsetIconOptions and UIunregisterIcons

.changeset/shaggy-planets-exercise.md, packages/control-property-editor/package.json
=> fix: revert major version update

.changeset/wet-ducks-smile.md, packages/launch-config/src/launch-config-crud/read.ts, packages/launch-config/test/launch-config-crud/read.test.ts, packages/launch-config/test/test-data/utils.ts
Fix for type error when launch.json file is empty.
=> fix(launch-config): type error for empty json

.changeset/sixty-tips-drop.md, packages/odata-vocabularies/src/resources/Org.OData.Aggregation.V1.ts, packages/odata-vocabularies/src/resources/Org.OData.Authorization.V1.ts, packages/odata-vocabularies/src/resources/Org.OData.Capabilities.V1.ts, packages/odata-vocabularies/src/resources/Org.OData.Core.V1.ts, packages/odata-vocabularies/src/resources/Org.OData.JSON.V1.ts, packages/odata-vocabularies/src/resources/Org.OData.Measures.V1.ts, packages/odata-vocabularies/src/resources/Org.OData.Repeatability.V1.ts, packages/odata-vocabularies/src/resources/Org.OData.Temporal.V1.ts, packages/odata-vocabularies/src/resources/Org.OData.Validation.V1.ts, packages/odata-vocabularies/src/resources/com.sap.vocabularies.Analytics.v1.ts, packages/odata-vocabularies/src/resources/com.sap.vocabularies.CDS.v1.ts, packages/odata-vocabularies/src/resources/com.sap.vocabularies.CodeList.v1.ts, packages/odata-vocabularies/src/resources/com.sap.vocabularies.Common.v1.ts, packages/odata-vocabularies/src/resources/com.sap.vocabularies.Communication.v1.ts, packages/odata-vocabularies/src/resources/com.sap.vocabularies.DataIntegration.v1.ts, packages/odata-vocabularies/src/resources/com.sap.vocabularies.DirectEdit.v1.ts, packages/odata-vocabularies/src/resources/com.sap.vocabularies.Graph.v1.ts, packages/odata-vocabularies/src/resources/com.sap.vocabularies.HTML5.v1.ts, packages/odata-vocabularies/src/resources/com.sap.vocabularies.Hierarchy.v1.ts, packages/odata-vocabularies/src/resources/com.sap.vocabularies.ODM.v1.ts, packages/odata-vocabularies/src/resources/com.sap.vocabularies.PDF.v1.ts, packages/odata-vocabularies/src/resources/com.sap.vocabularies.PersonalData.v1.ts, packages/odata-vocabularies/src/resources/com.sap.vocabularies.Session.v1.ts, packages/odata-vocabularies/src/resources/com.sap.vocabularies.UI.v1.ts, packages/odata-vocabularies/test/vocabulary-service.test.ts
- update odata and sap-ux vocabularies
=> fix: updateVocabularies

.changeset/blue-plants-wonder.md, packages/backend-proxy-middleware/package.json, packages/control-property-editor/package.json, packages/ui5-proxy-middleware/package.json, pnpm-lock.yaml
Issue: tools-suite/issues/31736
=> fix(security): upgrade http-proxy-middleware

.changeset/bright-students-rhyme.md, packages/fiori-elements-writer/test/__snapshots__/alp.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/feop.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/fpm.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/lrop.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/ovp.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/worklist.test.ts.snap, packages/ui5-application-writer/src/data/defaults.ts, packages/ui5-application-writer/src/data/index.ts, packages/ui5-application-writer/test/__snapshots__/options.test.ts.snap, packages/ui5-application-writer/test/data.test.ts
https://github.com/SAP/open-ux-tools/issues/2487
Remove @sap/ux-specification from package.json in generated apps
Update tests and snapshot to reflect these changes.
Remove code no longer used
=> tbi: remove @sap/ux-specification from generated apps

.changeset/tricky-dogs-grab.md, packages/ui-components/src/components/UIFlexibleTable/UIFlexibleTable.tsx, packages/ui-components/src/components/UIFlexibleTable/types.ts, packages/ui-components/test/unit/components/UIFlexibleTable.test.tsx
Add aria-label for UIFlexibleTable `Add Row` Button
=> fix: add aria-label for UIFlexibleTable Add Row Button

.changeset/spicy-beds-destroy.md, packages/fiori-elements-writer/test/__snapshots__/alp.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/feop.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/fpm.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/lrop.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/ovp.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/worklist.test.ts.snap, packages/fiori-freestyle-writer/templates/common/add/1.120.0/webapp/model/models.js, packages/fiori-freestyle-writer/templates/common/add/1.71.0/webapp/model/models.js, packages/fiori-freestyle-writer/test/__snapshots__/basic.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/index.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/listdetail.test.ts.snap, packages/fiori-freestyle-writer/test/__snapshots__/worklist.test.ts.snap, packages/fiori-freestyle-writer/test/basic.test.ts, packages/ui5-application-writer/templates/optional/loadReuseLibs/1.120.0/webapp/test/locate-reuse-libs.js, packages/ui5-application-writer/templates/optional/loadReuseLibs/1.71.0/webapp/test/locate-reuse-libs.js, packages/ui5-application-writer/test/__snapshots__/options.test.ts.snap
https://github.com/SAP/open-ux-tools/issues/2297
Fix lint issues in 
`./packages/fiori-freestyle-writer/templates/common/add/1.71.0/webapp/model/models.js`
`./packages/fiori-freestyle-writer/templates/common/add/1.120.0/webapp/model/models.js`
`./packages/ui5-application-writer/templates/optional/loadReuseLibs/1.71.0/webapp/test/locate-reuse-libs.js`
`./packages/ui5-application-writer/templates/optional/loadReuseLibs/1.120.0/webapp/test/locate-reuse-libs.js`
=> Fix lint issue in templates

.changeset/kind-hornets-fry.md, packages/launch-config/src/launch-config-crud/create.ts, packages/launch-config/src/translations/launch-config.i18n.json, packages/launch-config/test/launch-config-crud/create.test.ts
Cleanup Logs: Fixed Log Message and Removed Redundant Error Entry from launch config i18n.json
=> Corrected Log Message & Removed Unused Error Entry

.changeset/chatty-clocks-change.md, .changeset/plenty-peaches-rhyme.md, packages/odata-service-inquirer/src/i18n.ts, packages/odata-service-inquirer/src/prompts/connectionValidator.ts, packages/odata-service-inquirer/src/prompts/datasources/sap-system/service-selection/service-helper.ts, packages/odata-service-inquirer/src/prompts/datasources/sap-system/system-selection/prompt-helpers.ts, packages/odata-service-inquirer/src/prompts/datasources/sap-system/system-selection/questions.ts
Fix for #2574 
- Removes console log statements
- Adds some missing jsdoc
=> Removes console log statement, adds some missing jsdoc

.changeset/few-ways-marry.md, packages/abap-deploy-config-inquirer/src/prompts/questions/abap-target.ts, packages/abap-deploy-config-inquirer/test/prompts/questions/abap-target.test.ts
Fix for https://github.com/SAP/open-ux-tools/issues/2608
=> fix(abap-deploy-config-inquirer): ensure scp prompt state is maintained

.changeset/large-kangaroos-notice.md, packages/abap-deploy-config-inquirer/src/prompts/helpers.ts, packages/abap-deploy-config-inquirer/test/fixtures/targets.ts, packages/abap-deploy-config-inquirer/test/prompts/helpers.test.ts, packages/abap-deploy-config-inquirer/test/prompts/questions/abap-target.test.ts
https://github.com/SAP/open-ux-tools/issues/2570
Fixes issue with `Source System` being added to multiple systems
=> fix(abap-deploy-inquirer): fix source system labelling

.changeset/nervous-windows-lay.md, packages/feature-toggle/src/constants.ts
New more granular toggles needs to be added ahead of Fiori AI release
=> feat(ai): add new toggles for ai

.changeset/funny-cars-raise.md, packages/btp-utils/package.json, packages/cf-deploy-config-writer/package.json, packages/inquirer-common/package.json, packages/odata-service-inquirer/package.json, pnpm-lock.yaml
Align https://www.npmjs.com/package/@sap/cf-tools version across all modules.
=> fix: align cf-tools version

.changeset/config.json, .github/workflows/pipeline.yml
Adds verification of change sets as a broken change set will be otherwise merged to main and block all subsequent publishing.
=> Update pipeline.yml to verify changeset in PR build

.changeset/tasty-phones-dress.md, packages/jest-environment-ui5/src/env/ui5Environment.js, packages/jest-environment-ui5/src/index.js, packages/jest-environment-ui5/src/utils/ui5MappingStrategy.js, packages/jest-environment-ui5/test/unit/__snapshots__/ui5MappingStrategy.test.js.snap, packages/jest-environment-ui5/test/unit/ui5Environment.test.js, packages/jest-environment-ui5/test/unit/ui5MappingStrategy.test.js
Previously this file was missing and in some scenario it is required.
=> fix: we now properly generate a sap-ui-version.json for ui5 mapping

.github/workflows/pipeline.yml
- Uses https://github.com/andstor/file-existence-action to test for changeset files existing before running the cset status
- Tested with no cset, empty cset, cset with changes, multiple csets and invalid csets
=> Adds conditional changeset file validation

packages/fiori-elements-writer/test/__snapshots__/alp.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/feop.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/fpm.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/lrop.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/ovp.test.ts.snap, packages/fiori-elements-writer/test/__snapshots__/worklist.test.ts.snap, packages/ui5-application-writer/test/__snapshots__/options.test.ts.snap
Oddly #2684 build passed without these updates
=> chore - update snapshots missed in PR #2684

.changeset/sweet-drinks-vanish.md
Changeset for the reload-middleware change added in https://github.com/SAP/open-ux-tools/pull/2618
=> changeset for reload-middleware

.changeset/mean-boxes-compare.md, packages/preview-middleware-client/src/adp/quick-actions/fe-v2/lr-enable-semantic-date-range-filter-bar.ts, packages/preview-middleware-client/src/adp/quick-actions/simple-quick-action-base.ts, packages/preview-middleware-client/src/cpe/quick-actions/utils.ts, packages/preview-middleware-client/test/unit/adp/quick-actions/fe-v2.test.ts
#2722 incorrectly changed the source of the `useDateRangeType` value.
=> fix: semantic date range quick action

.changeset/thin-trainers-sniff.md, packages/odata-service-inquirer/src/translations/odata-service-inquirer.i18n.json
Updates error message for alp v4 with no aggregate based entities
=> fix(odata-inq): update alp v4 error text

.changeset/wild-spiders-turn.md, packages/control-property-editor/src/panels/quick-actions/QuickAction.scss, packages/ui-components/src/components/UIContextualMenu/_variables.scss, packages/ui-components/src/components/UISearchBox/UISearchBox.tsx
Improved readability of disabled actions in quack actions submenus, expanded space between quick  action links
=> fix: ui styles improvements in cpe

.changeset/swift-walls-obey.md, packages/preview-middleware-client/src/flp/enableFakeConnector.ts, packages/preview-middleware-client/test/unit/flp/enableFakeConnector.test.ts
=> fix(preview-middleware-client):parameter type for fakeLrep create function

.changeset/strange-spiders-destroy.md, docs/version-overrides.md, examples/ui-prompting-examples/package.json, package.json, packages/adp-tooling/package.json, packages/backend-proxy-middleware/package.json, packages/cards-editor-middleware/package.json, packages/control-property-editor/package.json, packages/preview-middleware/package.json, packages/reload-middleware/package.json, packages/serve-static-middleware/package.json, packages/ui-prompting/package.json, packages/ui5-proxy-middleware/package.json, pnpm-lock.yaml
- upgrade express
- upgrade path-to-regexp
- upgrade @storybook/addons
- upgrade store2
=> fix(security): security findings from github

.changeset/orange-cheetahs-mate.md, packages/odata-service-inquirer/src/index.ts, packages/odata-service-inquirer/test/unit/index-api.test.ts
https://github.com/SAP/open-ux-tools/issues/2879
- add param to set isYUI in PromptState
=> feat(odata-service-inq): add param to set isYUI in promptState

.changeset/seven-carrots-sparkle.md, packages/fiori-elements-writer/src/translations/fiori-elements-writer.i18n.json, packages/fiori-elements-writer/src/writeAnnotations.ts, packages/fiori-elements-writer/test/unit/writeAnnotations.test.ts
https://github.com/SAP/open-ux-tools/pull/2849
Add error handling to fiori elements writer while generating annotations.
=> Add error handling write annotation

.changeset/witty-plants-explode.md, packages/fiori-annotation-api/src/fiori-service.ts, packages/fiori-annotation-api/test/unit/fiori-service.test.ts, packages/fiori-annotation-api/test/unit/projects.ts
=> fix: cds compile error with memfs

.changeset/giant-seals-leave.md, packages/control-property-editor/src/panels/outline/OutlinePanel.scss, packages/control-property-editor/src/panels/outline/Tree.tsx, packages/control-property-editor/test/unit/panels/outline/OutlinePanel.test.tsx
Use UIContextualMenu component for sap.ui.extensionpoint types node for showing menus
=> fix: unify contextmenu component for extensionPoint node

.changeset/bright-spoons-hammer.md, packages/cf-deploy-config-writer/src/cf-writer/app-config.ts, packages/cf-deploy-config-writer/src/mta-config/index.ts, packages/cf-deploy-config-writer/src/mta-config/mta.ts, packages/cf-deploy-config-writer/src/translations/cf-deploy-config-writer.i18n.json, packages/cf-deploy-config-writer/test/unit/index-app.test.ts, packages/cf-deploy-config-writer/test/unit/index-base.test.ts
Fix for https://github.com/SAP/open-ux-tools/issues/2912
- Try re-save mta again if an error is found
- Add additional logging
- Increase timeout
=> fix(cf-deploy-config-writer): add new logging and introduce a retry to save mta

.changeset/plenty-crews-obey.md, packages/deploy-config-generator-shared/src/prompts/index.ts, packages/deploy-config-generator-shared/src/translations/deploy-config-generator-shared.i18n.json, packages/deploy-config-generator-shared/test/prompts/index.test.ts, packages/flp-config-sub-generator/src/app/index.ts, packages/flp-config-sub-generator/test/app.test.ts
Fix for https://github.com/SAP/open-ux-tools/issues/2916
=> fix(flp): fix spelling prompt name

.changeset/spotty-points-exercise.md, packages/project-access/src/index.ts, packages/project-access/src/project/index.ts
export [getI18nBundles](https://github.com/SAP/open-ux-tools/blob/main/packages/project-access/src/project/i18n/read.ts#L31) function
=> feat(project-access): export `getI18nBundles` function

.changeset/late-schools-ring.md, packages/preview-middleware-client/src/adp/ui/ExtensionPoint.fragment.xml
#2924
- Add stable Ids in ExtensionPoint form
=> feat: add stable ids to form elements

.changeset/nice-starfishes-invite.md, packages/ui-components/src/components/UIButton/UIActionButton.tsx
=> fix(ui-components): UIButtonAction set margin left icon to zero

.changeset/slimy-coats-hide.md, packages/odata-service-writer/src/data/annotations.ts, packages/odata-service-writer/src/update.ts, packages/odata-service-writer/test/unit/index.test.ts
https://github.com/SAP/open-ux-tools/issues/2938
=> fix(odata-service-writer): write metadata.xml from update

.changeset/late-beers-fail.md, packages/axios-extension/src/index.ts
Export `patchTls` from `sap-ux/axios-extension`  to improve reusability
=> Export `patchTls` from `sap-ux/axios-extension`

.changeset/swift-emus-rule.md, packages/adp-tooling/src/translations/adp-tooling.i18n.json
Feat for #2986.
- Changes i18n text for dropdown prompt for "Add Local Annotation File" manifest change wizard.
=> feat: Change "Add Local Annotation File" wizard dropdown option text in `@sap-ux/adp-tooling`

.changeset/wet-queens-design.md, packages/preview-middleware-client/src/adp/quick-actions/common/add-new-subpage.ts
Removed feature toggle check in Add Subpage CPE quick action
=> feat: removed feature toggle

.changeset/thin-flowers-act.md, packages/annotation-generator/package.json, packages/cds-annotation-parser/package.json, packages/cds-odata-annotation-converter/package.json, packages/environment-check/package.json, packages/fiori-annotation-api/package.json
chore - Add repository metadata in package.json
=> chore - Add repository metadata in package.json

package.json, pnpm-lock.yaml
Clean the nx-cache when cleaning the dist folder.
=> Clear nx cache when cleaning dist folders.

package.json, pnpm-lock.yaml
Useful script to check for npm dependencies that are using different versions across modules.
=> add check-dependency-version-consistency script

.changeset/empty-wolves-vanish.md, packages/ui5-proxy-middleware/src/base/utils.ts, packages/ui5-proxy-middleware/test/base/utils.test.ts
=> fix(ui5-proxy-middleware): adjust response type

.changeset/bright-cars-kiss.md, packages/guided-answers-helper/src/index.ts, packages/guided-answers-helper/test/unit/index.test.ts, packages/repo-app-import-sub-generator/package.json, packages/repo-app-import-sub-generator/src/prompts/prompts.ts, packages/repo-app-import-sub-generator/src/translations/repo-app-import-sub-generator.i18n.json, packages/repo-app-import-sub-generator/src/utils/validators.ts, packages/repo-app-import-sub-generator/test/utils/validators.test.ts, packages/repo-app-import-sub-generator/tsconfig.json, pnpm-lock.yaml
Related to [PR](https://github.com/SAP/open-ux-tools/pull/3110)
- Added GA Help Link https://ga.support.sap.com/dtp/viewer/index.html#/tree/3046/actions/63911%20as%20opposed%20to%20https://ga.support.sap.com/dtp/viewer/index.html#/tree/3046/actions/45995:63911
- Addressed [comment](https://github.com/SAP/open-ux-tools/pull/3110#discussion_r2044062594) in PR
=> Added GA Help Link to `@sap-ux/repo-app-import-sub-generator`

.changeset/lucky-pans-sleep.md, packages/repo-app-import-sub-generator/src/translations/repo-app-import-sub-generator.i18n.json
Reviewed the relevant ADT Quick Deploy UI texts.
=> ADT Quick Deploy UI Text Review

.changeset/shiny-pigs-breathe.md, packages/feature-toggle/src/constants.ts
Add feature toggle for fiori-ai to enable RAP generation
toggle is called 'sap.ux.help.testBetaFeatures.enableFioriAIRapGeneration'
=> feat: add fiori-ai rap generation toggle

.changeset/beige-islands-turn.md, packages/preview-middleware/templates/flp/cdm.html, packages/preview-middleware/templates/flp/sandbox.html, packages/preview-middleware/templates/flp/sandbox2.html, packages/preview-middleware/test/unit/base/__snapshots__/config.test.ts.snap, packages/preview-middleware/test/unit/base/__snapshots__/flp.test.ts.snap
fix(preview-middleware) fix template spacing (avoids breaking test snapshots in tools-suite)
follow-on from https://github.com/SAP/open-ux-tools/pull/3167
=> fix(preview-middleware) fix template spacing

.changeset/giant-keys-lie.md, packages/fiori-elements-writer/src/index.ts, packages/fiori-elements-writer/test/__snapshots__/lrop.test.ts.snap, packages/fiori-elements-writer/test/lrop.test.ts
- Checks for `appOptions.useVirtualPreviewEndpoints` and updates the `htmlTarget` used in the OPA tests accordingly
=> fix(fe-writer): fix html target for opa tests when using virtual endpoints

.changeset/bright-ants-perform.md, packages/create/README.md, packages/create/src/cli/add/cards-generator.ts, packages/create/test/unit/cli/add/cards-generator.test.ts
Adjust create readme from cards-editor to cards-generator
=> fix(create): update create readme for cards-generator

.changeset/pretty-pumpkins-rest.md, packages/repo-app-import-sub-generator/src/app/app-config.ts, packages/repo-app-import-sub-generator/src/app/index.ts, packages/repo-app-import-sub-generator/src/app/types.ts, packages/repo-app-import-sub-generator/src/prompts/prompt-helpers.ts, packages/repo-app-import-sub-generator/src/prompts/prompt-state.ts, packages/repo-app-import-sub-generator/src/prompts/prompts.ts, packages/repo-app-import-sub-generator/src/utils/constants.ts, packages/repo-app-import-sub-generator/src/utils/validators.ts, packages/repo-app-import-sub-generator/test/app-config.test.ts, packages/repo-app-import-sub-generator/test/prompts/prompt-helpers.test.ts, packages/repo-app-import-sub-generator/test/prompts/prompt-state.test.ts, packages/repo-app-import-sub-generator/test/prompts/prompts.test.ts, packages/repo-app-import-sub-generator/test/utils/validators.test.ts
Fix ui5-deploy.yaml (and ui5*.yaml) to set the url, client and destination.
=> Fix deployment config for download ADT App

.changeset/dry-boxes-bathe.md, packages/axios-extension/README.adoc, packages/axios-extension/src/factory.ts, packages/axios-extension/test/factory.test.ts, packages/deploy-tooling/README.md
Reverts SAP/open-ux-tools#3254
Issues found on BAS CLI, needs further inveestigation.
=> Revert "2279/remove feature toggle"

packages/fiori-generator-shared/src/translations/fiori-generator-shared.i18n.json
Reviewed `packages/fiori-generator-shared/src/translations/fiori-generator-shared.i18n.json`.
=> Fiori Generator Shared Text Review

packages/launch-config/src/translations/launch-config.i18n.json
Reviewed `packages/launch-config/src/translations/launch-config.i18n.json`.
=> Launch Config Text Review

packages/deploy-config-generator-shared/src/translations/deploy-config-generator-shared.i18n.json, packages/deploy-config-sub-generator/src/translations/deploy-config-sub-generator.i18n.json
Reviewed `packages/deploy-config-generator-shared/src/translations/deploy-config-generator-shared.i18n.json` and `packages/deploy-config-sub-generator/src/translations/deploy-config-sub-generator.i18n.json`.
=> Deploy Config Text Review

.changeset/rude-olives-do.md, packages/cf-deploy-config-inquirer/src/prompts/validators.ts, packages/cf-deploy-config-inquirer/test/validators.test.ts
Edit the error message for long Windows paths.
=> fix(cf-deploy-config-inquirer): long path warning

.changeset/gold-panthers-travel.md, packages/ui5-application-inquirer/src/translations/ui5-application-inquirer.i18n.json, packages/ui5-application-inquirer/test/unit/prompts/__snapshots__/prompts.test.ts.snap, packages/ui5-application-inquirer/test/unit/prompts/prompts.test.ts
Follow-on from https://github.com/SAP/open-ux-tools/pull/3383
=> Align text on mta message and non mta deploy config

.changeset/warm-moons-return.md, packages/fiori-app-sub-generator/src/types/constants.ts
Fix for https://github.com/SAP/open-ux-tools/issues/3425
=> Update FLP text

.changeset/smart-zoos-care.md, packages/repo-app-import-sub-generator/src/utils/updates.ts, packages/repo-app-import-sub-generator/test/__snapshots__/app.test.ts.snap
- Updated manifest merging logic to ensure only css: [] is set in `sap.ui5.resources`.
- snapshot update
=> set only css: [] in manifest to fix ui5 linting issue

.changeset/curly-months-perform.md, packages/axios-extension/src/abap/catalog/base.ts, packages/axios-extension/src/abap/catalog/v4-catalog-service.ts, packages/axios-extension/test/abap/catalog/v4-catalog-service.test.ts, packages/axios-extension/test/abap/mockResponses/v4RecommendedServiceGroupsPage-1.json, packages/axios-extension/test/abap/mockResponses/v4RecommendedServiceGroupsPage-2.json, packages/axios-extension/test/abap/mockResponses/v4RecommendedServiceGroupsPage-3.json, packages/axios-extension/test/abap/mockResponses/v4RecommendedServiceGroupsPage-4.json, packages/axios-extension/test/abap/mockResponses/v4ServiceGroupsPage-1.json, packages/axios-extension/test/abap/mockResponses/v4ServiceGroupsPage-2.json, packages/axios-extension/test/abap/mockResponses/v4ServiceGroupsPage-3.json, packages/axios-extension/test/abap/mockResponses/v4ServiceGroupsPage-4.json, packages/odata-service-inquirer/src/prompts/datasources/sap-system/service-selection/service-helper.ts
Addresses : #3472 
- Adds calculated paging approach for v4 service group requests, in addition to serial `@nextlink` approach
- New implementation of on by defalt but previous implementation remains available as an option
- Updates tests to cover
- Adds performance logging to `odata-service-inquirer`
=> tbi(axios-extension): Improves v4 services load times

.changeset/tricky-tomatoes-glow.md, packages/preview-middleware-client/src/adp/quick-actions/common/add-controller-to-page.ts, packages/preview-middleware-client/src/adp/quick-actions/simple-quick-action-base.ts
Fixes for sonar reported issue "Invalid loop. Its body allows only one iteration." 
https://sonarcloud.io/project/issues?open=AZhhKa-hvDTRnrolq4Nq&id=SAP_open-ux-tools
https://sonarcloud.io/project/issues?open=AZhhKbEvvDTRnrolq4Nr&id=SAP_open-ux-tools
=> fix: sonar issue "Invalid loop. Its body allows only one iteration."

.changeset/few-ghosts-smile.md, packages/backend-proxy-middleware/src/ext/bsp.ts, packages/backend-proxy-middleware/test/ext/bsp.test.ts
Make bsp path in backend proxy config case insensitive
=> fix(backend-proxy-middleware): make bsp path case insensitive

.changeset/wicked-jokes-begin.md, packages/fiori-mcp-server/README.md, packages/fiori-mcp-server/src/tools/functionalities/generate-fiori-ui-app/command.ts, packages/fiori-mcp-server/src/tools/functionalities/generate-fiori-ui-app/generate-fiori-ui-app.ts, packages/fiori-mcp-server/test/unit/tools/functionalities/generate-fiori-ui-app/generate-fiori-ui-app.test.ts
feat: add timeout configuration for MCP server and ensure absolute service paths
=> fix(mcp): add timeout configuration for MCP server and ensure absolute service paths

.changeset/smart-ladybugs-explode.md, packages/fiori-docs-embeddings/src/scripts/build-embeddings.ts, packages/fiori-docs-embeddings/test/build-embeddings.test.ts, packages/fiori-mcp-server/src/tools/services/vector-simple.ts, packages/fiori-mcp-server/test/unit/tools/services/vector-simple.test.ts
Refactored embeddings to reduce table size and update mcp server to read DB tables.
=> Fix issues with publish embeddings

.changeset/two-camels-cough.md, examples/simple-generator/package.json, package.json, packages/abap-deploy-config-inquirer/package.json, packages/app-config-writer/package.json, packages/axios-extension/package.json, packages/btp-utils/package.json, packages/deploy-tooling/package.json, packages/environment-check/package.json, packages/fiori-app-sub-generator/package.json, packages/fiori-mcp-server/package.json, packages/inquirer-common/package.json, packages/odata-service-inquirer/package.json, packages/odata-vocabularies/package.json, packages/reload-middleware/package.json, packages/telemetry/package.json, packages/ui-service-sub-generator/package.json, packages/ui5-config/package.json, packages/ui5-info/package.json, pnpm-lock.yaml
- override for ux-specification
=> fix(security): upgrade axios

pnpm-lock.yaml
- https://github.com/SAP/open-ux-tools/security/dependabot/243
Issue: ux-engineering#35838
=> fix(security): upgrade tar-fs in lock file

.changeset/rotten-camels-deliver.md, packages/ui-components/src/components/Icons.tsx
- Updated the icon for the Page component
- Updated the icon for the Building Block component
=>  Update Icons for Page and Building Block

.changeset/lazy-hotels-carry.md, packages/cds-odata-annotation-converter/package.json, packages/fiori-annotation-api/package.json, packages/fiori-annotation-api/test/unit/avt/__snapshots__/metadata.test.ts.snap, pnpm-lock.yaml
Consume new cds-compiler-facade
=> chore: update  cds-compiler-facade dependency
